### ISSUE TITLE
Occorre aggiornare i testi indicando Pubblica Amministrazione invece di PA

### ISSUE THREAD

**Issue by didoo** [italia-it/designer.italia.it#10]
Nelle Linee Guida è chiaramente indicato che va utilizzato un linguaggio più vicino al cittadino. Viene suggerito "Sciogliete sempre le abbreviazioni e le sigle", e portato come esempio "Pubblica Amministrazione" al posto di PA:
http://design.italia.it/linee-guida/usabilita/contenuti/ 
Poi però nella maggior parte della guida stessa, la sigla PA appare decine di volte in forma compatta. Per coerenza occorre seguire i principi e le indicazioni della guida, altrimenti a cosa serve una guida? :)

**Comment by emilio55** [comment]
Non mi attarderei nel chiedere il rispetto della regola pur giusta. La sigla PA è diffusa ed entrata nel senso comune e comunemente intesa. Tra l'altro l'uso della sigla impedisce di appesantire troppo le pagine in cui ripetere troppe volte pubbliche amministrazioni (che vanno indicate sempre al plurale e con la minuscola)  rende più lenta la scrittura/lettura.

**Comment by claudiopro** [comment]
@emilio55 sono d'accordo con @didoo, se la guida prescrive _"Sciogliete sempre le abbreviazioni e le sigle"_, PA va espanso, altrimenti la regola va qualificata come opzionale.

**Comment by emilio55** [comment]
@claudiopro capisco IWA, FMI,, MEF, UX, UCD, ma che facciamo con INPS (Istituto Nazionale della Previdenza Sociale), INAIL (Istituto Nazionale contro gli Infortuni sul Lavoro) , ecc., dai!

**Comment by claudiopro** [comment]
@emilio55 citando @didoo:

> Per coerenza occorre seguire i principi e le indicazioni della guida, altrimenti a cosa serve una guida? :)

**Comment by GianniSinni** [comment]
Opterei per seguire quanto indicato nella Linee guida: pubblica amministrazione sempre per esteso. Cosa diversa per gli acronimi e le sigle di uso comune, preferibilmente sciogliendo la prima ricorrenza della pagina.
Sulle "regole di stile" c'è da fare ancora un po' di lavoro.

**Comment by emilio55** [comment]
Caro Gianni, ad essere rigorosi e un po' pignoli, allora solo "pubbliche amministrazioni" in quanto la pubblica amministrazione, intesa come nome collettivo di tutti gli enti pubblici, *non esiste*, tranne nel caso indichi un ente specifico..

**Comment by didoo** [comment]
La leggibilità non è appesantita da testi estesi, anzi: nel caso di acronimi non facilmente riconoscibili il cervello deve comunque convertire in parole l'acronimo, quindi il "carico cognitivo" è probabilmente maggiore. E aumenta comunque l'inclusività, altro principio generale delle linee guida (qualcuno potrebbe non sapere/capire/ricordare che PA è usato come abbreviazione di Pubblica Amministrazione).
Quello che al contrario si può fare è evitare di usare troppe volte la parola Pubblica Amministrazione (si rischia fra l'altro l'auto-referenzialità)

**Comment by fiaschi** [comment]
Pull Requests fatte.

**Comment by decarola** [comment]
Cambiare la regola di stile e prorre di:
- usare le versioni estese
- in alternativa, per via delle troppe ripetizioni, usare il tag `abbr`? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr
`<abbr title="Pubblica Amministrazione">PA</abbr>`

**Comment by fiaschi** [comment]
Versione estesa la prima volta e <abbr> nelle ripetizioni?

**Comment by gunzip** [comment]
ok per me

**Comment by gunzip** [comment]
abbiamo sciolto l'acronimo (a parte che nel titolo del progetto :)))
