### ISSUE TITLE
Trattare di sicurezza

### ISSUE THREAD

**Issue by CesareGallotti** [italia-it/designer.italia.it#104]
Coglierei l'occasione per parlare di sicurezza, visto che si parla molto di "privacy (o security) by design". Qui "design" intende "rappresentazione grafica" e non "progetto complessivo".

Restando sulla rappresentazione grafica, tratterei di: rendere chiare le modalità di registrazione e di accesso, rendere chiaro quando un utente ha acceduto o meno all'area riservata con le proprie credenziali, rendere sempre disponibile un pulsante di disconnessione (e chiarire cosa succede se qualcuno chiude il browser senza usarlo). 

Ovviamente si potrebbe cogliere l'occasione per approfondire i temi della sicurezza trattando di funzionalità e meccanismi tecnologici, ma forse questo sarebbe fuori tema.

**Comment by gunzip** [comment]
potrebbe rientrare nel task fornire dei template per gli elementi descritti nelle [modalità attuative di SPID](http://www.agid.gov.it/sites/default/files/circolari/spid-modalita_attuative_v1.pdf) (da pag. 37)

**Comment by umbros** [comment]
Nei template SPID per Service Provider è stato sviluppato un bottone SPID, con username o nome utente che, con un menù a tendina, permette diverse attività per la gestione dell'utenza e ovviamente il logout. La gestione degli utenti sarà completamente demandata agli IDP (Identity Provider) e quindi Registrazione e attività di gestione utenza non saranno più presenti sui portali. I template per IDP saranno rilasciati solo agli Identity Provider mentre i template e widget per SP (service provider) saranno pubblici.

**Comment by gunzip** [comment]
Allora, più che trattare di sicurezza (che forse è un po' fuorviante come label) direi, pattern di interazione per service design sulla falsa riga da quanto fatto su https://www.gov.uk/service-manual/user-centred-design/resources/patterns. quindi integare indicazioni su pattern per login / logout / feedback utent (è già in cantiere).
