### ISSUE TITLE
Rivedere lo stile dei tag <a> con class=btn 

### ISSUE THREAD

**Issue by MaoX17** [italia-it/designer.italia.it#106]
Salve a tutti,
sto provando a sviluppare una web-application seguendo le linee guida.
Quando però inserisco un tag "a" con class=btn, dopo aver cliccato sul pulsante il colore del testo diventa celeste, impedendo una ottimale visione del testo stesso.
es.
< a href="visualizza.php" class="btn btn-success" role="button">Atti in pubblicazione </ a >
inizialmente è ok, ma dopo aver cliccato il link, se torno sulla pagina, il colore del testo diventa celeste e con lo sfondo è verde è praticamente illeggibile.
Lo stesso per tutti gli altri tipi di btn
Per un caso simile devo modificare il css con un 
a:visited {
    color:white;
}
oppure si può inserire una modifica che valga per tutti?
Spero di non aver sbagliato io qualcosa.

Grazie
Saluti

**Comment by gunzip** [comment]
@MaoX17 è vero, c'è un "bug" nello stile dei template, vanno rivisti i colori dei link visitati con classi ```btn``` (per ora ```<a class="btn btn-link">``` potrebbe essere un'alternativa)

Inserisco il task tra quelli da fare.

**Comment by MaoX17** [comment]
Grazie @gunzip 
Non so se sono già state fatte le modifiche, perchè mi risulta ancora presente il bug
(v. issue #98  in cui ho inserito il link a un mio primo progetto che frutta le linee guida)
In quel progetto ogni notte aggiorno i css dal repository github.

Grazie ancora
Saluti

**Comment by gunzip** [comment]
dovrebbe esser corretto ora #117

**Comment by MaoX17** [comment]
Perfetto grazie!
