### ISSUE TITLE
Chiarimento larghezza contenuti

### ISSUE THREAD

**Issue by Commedia** [italia-it/designer.italia.it#108]
Dalle vostre linee guida, come pure da quanto indicato da Bootstrap, la classe container blocca la larghezza massima a 1170px.

E' corretto assumere che la larghezza della pagina (intesa come contenuti, al di là degli elementi grafici) sia di 1170px ?

Chiedo conferma perché su governo.it ci sono alcune sezioni che non rispettano tale comportamento.

![maxwidth](https://cloud.githubusercontent.com/assets/16287076/11777623/d75204e4-a24f-11e5-8a75-c30b41f2211f.jpg)

**Comment by webgrafia** [comment]
Rispetto alle misure indicate c'è un refuso sulle linee guida che stiamo correggendo.
Ti anticipo che la larghezza massima della classe container sarà di 1440px, non i 1170 indicati nelle Linee Guida e definiti da bootstrap.

**Comment by gunzip** [comment]
@Commedia la pagina http://designer.italia.it/linee-guida/griglie/ è stata rivista
