### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by Commedia** [italia-it/designer.italia.it#109]
Su governo.it sembrerebbe esserci una gallery differente (di immagini o video) per ogni news.

Dal momento che stiamo realizzando il nuovo lavoro.gov.it, potremmo utilizzare una gallery per tipologia (quindi una galleria video e una galleria immagini) al fine di evitarne la proliferazione?

Eventualmente potremmo filtrarne i contenuti in base ai tag.

**Comment by Fraq1974** [comment]
La progettazione esecutiva e la raccolta dei requisiti lato editore sono fondamentali per definire la scelta più consona alle esigenze. Le gallery presenti su Governo rispondono a una specifica richiesta di gestione editoriale da parte della redazione che si occupa dei contenuti, non sono un modello vincolante. Quindi la vostra scelta è corretta se è funzionale.
