### ISSUE TITLE
Rivedere i Principi Generali alla luce dei principi espressi in GOV.UK

### ISSUE THREAD

**Issue by didoo** [italia-it/designer.italia.it#11]
Suggerisco vadano rivisti i Principi Generali della guida, tenendo conto dell'esempio GOV.UK/GDS: 
https://www.gov.uk/design-principles
https://www.gov.uk/guidance/content-design/writing-for-gov-uk

Nota: chiaramente si vede che l'ispirazione è quella (ad esempio "Disegno coerente, non uniforme", vs. "Be consistent, not uniform") ma credo occorra spingersi oltre nell'adottare gli stessi principi (al punto da considerare una traduzione pari pari: in caso contrario, occorrerebbe giustificare per quale motivo uno dei principi espressi da GOV.UK non è applicabile a Italia.it

**Comment by didoo** [comment]
Stefano Bussolon mi suggerisce questa risorsa, che mi sembra molto interessante (suppongo questa issue non sia risolvibile solo con un paio di commenti e di pull-requests, occorre una discussione aperta e che coinvolga il numero maggiore possibile di contributor).

http://www.bussolon.it/blog/2015/10/guida-alle-linee-guida.html

**Comment by didoo** [comment]
Qui il link al progetto U.S. Web Design Standards suggerito da @groundrace:
https://github.com/18F/web-design-standards
Citando il Readme del progetto: _The U.S. Web Design Standards is a library of open source UI components and a visual style guide for U.S. federal government websites._

**Comment by didoo** [comment]
Qui un link all'utilizzo e accessibilità dei form:
http://govuk-elements.herokuapp.com/form-elements/

**Comment by gunzip** [comment]
Principi e strategie sono stati rivisitati:
http://designer.italia.it/linee-guida/il-progetto/
http://designer.italia.it/linee-guida/il-progetto/strategie/

secondo quanto prodotto nell'ambito della consultazione pubblica sulle
"Linee Guida per il design dei servizi: principi e strategie":
http://www.agid.gov.it/playbook-servizi/

Tra le tematiche: 

- condivisione di competenze, software, dati, infrastrutture e linee guida
- inclusione e progettazione centrata sull'utente
- necessità di creare servizi usabili e attraenti
- monitoraggio e data-driven innovation
- comunicazione efficace tra PA e cittadini
- adozione di metodologia *agile*
- sicurezza e privacy
