### ISSUE TITLE
Burger menu e javascript

### ISSUE THREAD

**Issue by Commedia** [italia-it/designer.italia.it#110]
Disabilitando il javascript, il burger menu in alto a sinistra diventa del tutto non accessibile su governo.it

**Comment by sabas** [comment]
http://stackoverflow.com/questions/22153388/bootstrap-no-script-fall-back-for-drop-down-button

**Comment by gunzip** [comment]
@Commedia grazie per la segnalazione, verrà fixato in una prossima release
