### ISSUE TITLE
incongruenza su lunghezza della linea

### ISSUE THREAD

**Issue by saiballo** [italia-it/designer.italia.it#111]
Segnalo anche una incongruenza abbastanza singolare. Nelle linee guida si parla di 75 caratteri come lunghezza massima di ogni riga.

E' un requisito che tutti conosciamo da tempo e sappiamo anche che applicarlo significa disegnare un layout specifico per evitare che ci siano "buchi" o spazi troppo ampi nella pagina.

E' abbastanza singolare però che il sito che dovrebbe rappresentare un esempio di applicazione delle linee guida (governo.it) abbia righe comprese tra 90 e 95 caratteri. Come dire: il primo sito che dovrebbe rispettare la legge è anche il primo che non la segue.

Aggiungo anche che secondo me, tralasciando la solita ricerca citata, una lunghezza di 90/95 caratteri è assolutamente leggibile se affiancata ad una interlinea ed una grandezza di font adatta, non sarebbe il caso di prendere una decisione più chiara?

Che senso ha obbligare un limite di 75 se poi nessuno lo rispetta? E se lo portassimo a 90/95 caratteri?

**Comment by webgrafia** [comment]
Confermiamo che la lunghezza massima di ogni riga deve essere di 75 caratteri. Le difformità presenti su Governo.it (che riguardano alcuni breakpoint intermedi) verranno a breve sistemate per rispettare il requisito.

**Comment by gunzip** [comment]
Chiudo riportando qualche riferimento suggerito da @GianniSinni

Su questo tema abbiamo ampia bibliografia univoca:

>U.S. Web Design Standards
https://playbook.cio.gov/designstandards/visual-style/
>Line length: Controlling the length of lines of text in extended copy makes reading more comfortable by helping readers’ eyes flow easily from one line to the next. Somewhere between 50 and 75 characters per line is broadly considered to be a readable line length, while 66 characters is considered the ideal. Other factors beyond line length also affect reading comfort. Text with more space between lines can have somewhat longer line length. Also, contexts in which users will not be reading long passages of text (such as footnotes or alerts) can safely be set with somewhat longer lines as well.

Gov.uk
http://govuk-elements.herokuapp.com/typography/#typography-body-copy
>make sure lines of text don't exceed 75 characters, as they become harder to read beyond that point

Sulla leggibilità in generale

- http://baymard.com/blog/line-length-readability
- http://webtypography.net/2.1.2

**Comment by renatius** [comment]
Ciao @webgrafia 

al momento però la max-width degli elementi contenenti righe è espressa in rem (55rem per essere esatti). Questo ha come effetto quello di renderla dipendente unicamente dalla dimensione del font del root element. Nel caso delle linee guida, visto che questo è dichiarato con font-size 10px, tutti i contenitori (p, ul, h1, etc..) hanno max-width uguale a 550px, **indipendentemente** dalle dimensioni del carattere effettivo impiegato.

Visto che la ratio è invece legato al numero di caratteri per riga, sarebbe meglio specificare la max-width in relazione alla dimensione del font presente nell'elemento, cioè in em. 

Se assumiamo, come fa webtypography (http://webtypography.net/2.1.2) - *che, incidentalmente, non fa quello che predica* ;) -  che in media la larghezza del carattere sia .5em, la max-width dovrebbe quindi essere posta a circa 37em. 

In realtà, considerata la frequenza dei caratteri in Italiano, e la metrica dei caratteri in Titillium un valore che meglio rispetta l'idea di una max-length di 75 caratteri è approx 30em 31em.

**Comment by gunzip** [comment]
@renatius ottima osservazione e info, me ne occupo asap per quanto riguarda il sito delle LG.

per quanto riguarda invece le modifiche ai template scaricabili stiamo procrastinandole a una fase in cui avremmo definito meglio le integrazioni / modifiche ai testi nonché definito il formato degli asset #29

**Comment by gunzip** [comment]
#114
