### ISSUE TITLE
Fascia blu notte "Governo Italiano"

### ISSUE THREAD

**Issue by Commedia** [italia-it/designer.italia.it#112]
Su http://design.italia.it/ la fascia blu notte in alto è allineata usando "col-md-1 col-md-offset-3", il che si sposa bene con il layout a 2 colonne del sito.

Dal momento che lavoro.gov.it non avrà un layout a 2 colonne, possiamo derogare allineando centralmente il blocco logo+Governo Italiano ? 

![esempio](https://cloud.githubusercontent.com/assets/16287076/11780844/4fbd604e-a265-11e5-95e9-52a529f0b2dd.png)

**Comment by milesimarco** [comment]
Credo sia necessario rivedere il tutto anche e soprattutto a fronte del fatto che le Pubbliche Amministrazioni non avranno bisogno della seconda fascia orizzontale in figura ma piuttosto un menù di navigazione.

**Comment by gunzip** [comment]
Anticipo qui un tema che merita una issue dedicata:

per le PA centrali è consigliato l'utilizzo del menu verticale a comparsa (visibile al momento solo su governo.it) per una serie di motivi:

1. è il pattern più popolare, nonché già assimilato, per l'utilizzo su dispositivi mobile
2. è più scalabile del menu orizzontale che può contenere solo un numero limitato di voci
3. al menu orizzontale è in ogni caso necessaria un'alternativa su mobile, considerando anche il fatto che non esiste "on hover"
4. il menu orizzontale aperto con numerose voci (tipici della PA) costringe a impaginazioni "a colonna" disorientanti

**Comment by mariocariello** [comment]
per quanto riguarda il menu orizzontale, trovo molto interessante la soluzione utilizzata sal MEF http://mef.gov.it

**Comment by mariocariello** [comment]
www.mef.gov.it

**Comment by gunzip** [comment]
#19
