### ISSUE TITLE
line-height dovrebbe essere indicata senza unità

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#115]
Nel css delle Linee guida la line-height degli elementi **p** ed **li** è specificata in rem. 

es:
![cattura](https://cloud.githubusercontent.com/assets/2411296/11811492/13dc8196-a336-11e5-8932-19667cb4198f.PNG)

Come già descritto per la max-width nella issue #111, questo ha l'effetto di rendere la line-height alta esattamente 28px e quindi non aderente alle specifiche contenute nelle Linee guida che fissano l'interlinea invece a circa il 150% del font-size usato (vedi sezione Tipografia).

Sarebbe quindi preferibile se la line-height venisse invece espressa in maniera dimensionless, in modo da essere legata alla dimensione del font effettivamente utilizzato.

es: line-height: 1.5;

Incidentalmente, gli elementi .lg-callout codificati senza elementi p interni usano invece l'interlinea ereditata da Bootstrap che è vicina a 1.43.  

riferimenti:
https://css-tricks.com/almanac/properties/l/line-height/
http://practicaltypography.com/line-spacing.html

**Comment by renatius** [comment]
un esempio di elemento .lg-callout dove il testo non è inserito dentro un elemento **p** è ad esempio questo:

![cattura](https://cloud.githubusercontent.com/assets/2411296/11812316/791234fc-a33b-11e5-8cab-f3d394047514.PNG)

**Comment by gunzip** [comment]
accolta, #116  

la lascio aperta, va corretta anche in 

```
_examples.scss:      line-height: 8rem;
_navigation.scss:      line-height: 2rem;
_navigation.scss:      line-height: 2rem;    
_navigation.scss:      line-height: 2.4rem;    
_navigation.scss:    line-height: 4rem;
_variables.scss:$line-height-h1:          8.6rem;
_variables.scss:$line-height-h2:          7.2rem;
_variables.scss:$line-height-h3:          4.8rem;
_variables.scss:$line-height-h4:          2.8rem;
_variables.scss:$line-height-h5:          2.8rem;
_variables.scss:$line-height-h6:          2.8rem;
_variables.scss:$badge-line-height:           2rem;
```

(l'effetto ottenuto è tuttavia "compliant" alle LG poiché anche il font-size è attualmente fisso, es. 28px = 150% circa di 18px)
