### ISSUE TITLE
Un bell'avatar per l'account github

### ISSUE THREAD

**Issue by nicola** [italia-it/designer.italia.it#12]
Dato che credo che ci guarderanno in molti :)

**Comment by dottorblaster** [comment]
Upvoting :)

**Comment by paolobarberis** [comment]
Si ^^

**Comment by GianniSinni** [comment]
Arriva presto :)

**Comment by italia-it** [comment]
@GianniSinni l'ho impostata (non fa un po' germania ? =)

**Comment by webnicola** [comment]
Se ci aggiungiamo la bandiera italiana alla base una riga 2/3 pixel...

**Comment by darkmartin** [comment]
**de** sembra la sigla internazionale della Germania piuttosto che l'abbreviazione di design, ero convinto che la sintesi del progetto potesse anche essere **.it**

**Comment by fiaschi** [comment]
Concordo con @darkmartin

**Comment by GianniSinni** [comment]
.it è la sigla di Italia Login. 
Consideriamo il sistema nel suo complesso. Nell'idea di sistema 2 lettere caratterizzano i vari ambiti. 
de= design sv=sviluppo id=spid  ...

**Comment by bussolon** [comment]
In effetti non è banale esprimere, in una icona, i concetti di design o di linee guida.
Credo che, in un approccio ucd, de sia estremamente fuorviante

**Comment by hzeta** [comment]
DIt - Design Italia

**Comment by darkmartin** [comment]
Se l'idea è quella di utilizzare un sistema di sigle e abbreviazioni, stile applicazioni Adobe, il sistema andrebbe quantomeno esplicitato e spiegato il suo razionale, specie all'utente che lo associa istintivamente alla sigla linguistica. I miei € 0,02.

**Comment by iperdiscount** [comment]
Propongo anche qui, LiGuIT (Linee Guida Italia): due lettere sono veramente poche per un progetto così articolato. Manca il design ma a quello ci penserà l'icona.

**Comment by bussolon** [comment]
Benchmark:

* [Government Digital Service](https://github.com/alphagov): ![](https://avatars3.githubusercontent.com/u/596977?v=3&s=200)
* [Swiss](https://github.com/swiss): ![](https://avatars1.githubusercontent.com/u/7151325?v=3&s=200)
* [18F](https://github.com/18F): ![](https://avatars3.githubusercontent.com/u/6233994?v=3&s=200)

**Comment by paolobarberis** [comment]
<img width="380" alt="italia_login_sd_def_pdf__pagina_1_di_66_" src="https://cloud.githubusercontent.com/assets/1193903/11346612/ba9976ee-921d-11e5-9383-ed2c361e492a.png">

oppure solo la i col punto a sinistra

che ne dite?

**Comment by fiaschi** [comment]
D.it ?

**Comment by nicola** [comment]
Il logo "de" che abbiamo adesso non va bene.

O quello di @paolobarberis o un semplice blu, nessuna scritta per evitare collisioni con altri nomi, brand, identità (o una bella bandiera semplice semplice)

**Comment by davideoliva** [comment]
Anche a me sembra indicato D.it o de.it... una cosa così.
![design_it](https://cloud.githubusercontent.com/assets/827450/11365735/c9558732-92a8-11e5-9a83-71e3cb02ca7a.png)

**Comment by gunzip** [comment]
d.it con il punto in alto a sx ?

**Comment by davideoliva** [comment]
@gunzip con il punto in alto a sx di "it" a me piace di più.
![design_it](https://cloud.githubusercontent.com/assets/827450/11371279/02c2b8f4-92c8-11e5-9991-752970469781.png)
.. :)

**Comment by gunzip** [comment]
a me va bene (perchè la d è più grande delle altre due lettere ? =)

@GianniSinni, @paolobarberis che ne dite ?

**Comment by davideoliva** [comment]
@gunzip è così nel font... :)

![ex_titillium](https://cloud.githubusercontent.com/assets/827450/11372036/a94048a6-92cb-11e5-9dfb-3c4d0174ae44.png)

**Comment by paolobuono** [comment]
A me piacerebbe vedere il tricolore da qualche parte, basta anche una piccola banda spessa un paio di pixel, in alto o a sinistra. Il punto non lo capisco, sembra quasi che stia cadendo dalla i. 
Qualcuno ha pensato a ".it", con il punto in basso e il puntino sulla i?

**Comment by davideoliva** [comment]
@paolobuono eh il tricolore forse sarebbe bene metterlo, ma non è che poi si appesantisce il tutto? Il punto (prima di .it) è così anche sul sito. Immagino sia un tratto distintivo del progetto.

**Comment by M3kH** [comment]
<it/>

**Comment by M3kH** [comment]
Perseguitando l'idea dell'**it**/**.it** ; visto che a molti DE ha fatto storcere un po il naso per un 'made in Italy'.

Mi sono venute tre proposte al volo, abbiate pieta, spazi andrebbero riempiti meglio, e i colori della bandiera dovrebbero essere da pantone.
Magari un'altro font, ma per adesso ho orgogliosamente scelot [monoid](http://larsenwork.com/monoid/):
![designer-it_01](https://cloud.githubusercontent.com/assets/651290/11413854/6eb1e112-93ee-11e5-8d2f-aa3f5ba92a59.png)
![designer-it_02](https://cloud.githubusercontent.com/assets/651290/11413853/6eaf6202-93ee-11e5-981d-5776732325c3.png)
![designer-it_03](https://cloud.githubusercontent.com/assets/651290/11413972/e434b67a-93ef-11e5-82b2-b7b61232d670.png)

Si protebbe aggiungere un motto sotto 'Designer Italia'.
Cosa ne pensate?

**Comment by paolobuono** [comment]
Toglierei le parentesi angolari, less is better. Lavorerei su quello proposto da paolobarberis, aggiungendo il tricolore, magari non lungo tutto un lato, da vedere l'effetto. lascerei il punto sulla i. Per la d di designer si potrebbe pensare ad uno strumento usato dai designer, una penna per esempio, che potrebbe essere messa al posto della i, in modo da richiamare la parola, o altro simbolo evocativo.

**Comment by paolobarberis** [comment]
@gunzip va bene anche così ma forse lavorerei su una o due lettere

**Comment by GianniSinni** [comment]
Andiamo sul classico, dunque
![icona-it-quadrato](https://cloud.githubusercontent.com/assets/15969789/11429487/dd03943c-9478-11e5-83b5-d02cf98e3d21.png)

**Comment by italia-it** [comment]
andata

**Comment by davideoliva** [comment]
Bello!

**Comment by M3kH** [comment]
Non vorrei sembrare rompiscatole,
Ma il punto non è allineato con la corpo della i, sporge leggermente in alto.

È il raggio dei bordi arrotondati ha qualcosa che non va, inoltre ad non essere congruente tra sopra e sotto.

Un poco OT.
In questa issue come in tante altre viene in ballo il gusto personale. Di cui questo repository ne sarà sempre pieno.

I metodi di 'selezione'/'decisione' non sembrano chiari. Secondo me non fare chiarezza su quest'ultimo allontana collaboratori o nuove idee/input. Posso aprire una issue a riguardo? O ci sono gerarchie per cui risulterebbe un'insulto?
