### ISSUE TITLE
Considerare di integrare la sezione accessibilità con esempi concreti

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#120]
Si potrebbe partire da una traduzione succinta di
https://www.marcozehe.de/2015/12/14/the-web-accessibility-basics/

e/o qualcosa di più avanzato
http://heydonworks.com/practical_aria_examples

**Comment by renatius** [comment]
Altri link

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques?mc_cid=41d8a26eaf&mc_eid=c16f4682d9

http://a11yproject.com/patterns/?mc_cid=41d8a26eaf&mc_eid=c16f4682d9

**Comment by MaoX17** [comment]
Perchè non prevedere anche, per ogni pagina, una visualizzazione testuale tipo la "modalità lettura" di firefox?
Ho provato a fare un esempio su http://albotest.provincia.prato.it/
Per ogni pagina, cliccando su pulsante "IperAccessibile" la pagina stessa viene visualizzata in modalità testuale.
Magari può essere utile per agevolare l'accessibilità senza complicarsi troppo la vita.
Che ne pensate?

**Comment by jdeyla** [comment]
IMHO sinceramente trovo poco utile la completa perdita di design in un progetto in cui il design è al centro e c'è un grande rispetto dell'accessibilità, della conformità agli standard ecc. 
Se il codice è usato bene, i colori anche, non c'è niente di meglio di un bel sito  per far capire come l'accessibilità non ha un grosso impatto estetico, ma è qualcosa che sta dietro.
Io preferirei veder sparire le versioni solo testo, solo audio ecc. in favore di siti conformi ma ricchi nell'aspetto e nelle funzionalità.

Per tornare al thread proposto da @gunzip : si potrebbe pensare a una guida succinta, ma c'è così tanta letteratura in giro e così tanti esempi aggiornati legati direttamente WCAG 2, che noi in Emilia.Romagna, abbiamo deciso di smettere di mantenere la nostra versione di linee guida. Se si fa qualcosa del genere, si deve poi anche mantenere nel tempo: chi se ne potrebbe fare carico?

**Comment by gunzip** [comment]
@jdeyla vero, tuttavia temo che limitarsi a prescrivere "fate riferimento alle wcag e ai tanti esempi che sono in giro (in inglese)" scoraggi i meno volenterosi. spesso basterebbe anche solo un po' più di attenzione per ottenere molto con poco. forse vale la pena almeno ribadire alcuni punti che spesso vengono trascurati (es. sito navigabile tramite tastiera), magari tramite una checklist (in italiano ;) del tipo http://a11yproject.com/checklist.html, non troppo difficile da manutenere.

**Comment by jdeyla** [comment]
@gunzip hai certamente ragione, ma il problema è che quando fornisci una lista riassuntiva, poi c'è chi si ferma alla lista, e pensa di essere conforme. 

Però basterebbe collegare le[ tecniche sufficienti della WCAG 2](https://www.w3.org/WAI/WCAG20/quickref/?currentsidebar=%23col_customize&levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl&techniques=advisory%2Cfailures&hidesidebar=true) come approfondimento, e si capirebbe, che è solo una lista sintetica e non esaustiva.

Quella checklist non è male, noi oggi dall'approccio per elementi html/css/js, siamo tornati a quello per requisiti e diamo una lista distinta in requisiti base e avanzati.  A quelli base associamo un minimo di indicazioni su cosa fare o non fare [quindi "checklistabile"].
La distinzione tra base e avanzata è semplice: prendendo le wcag 2, abbiamo individuato alcuni requisiti che se non rispettati, diventano cerrtamente un ostacolo insormontabile per almeno una disabilità (es. lampeggiamento: epilessia, contrasto colori/ingrandimento: problemi gravi vista; ecc.).

- Colori: Comprensibile in B/N	
- Colori – Contrasto corretto
- Link e controlli – Utilizzabili(tastiera + struttura + label) 
- Multimedia – Alternative
- Multimedia – Flash (> 3 al sec.)
- Multimedia – No audio (se + 3 secondi)	
- Script - Direttamente accessibili
- Testo - Adattabilità
- Tempo – Regolabile

Questa lista e questi requisiti noi li manuteniamo (internamente) perchè sono nel documento di verifica della conformità che facciamo per ogni sito/ applicazione che riusciamo a governare

**Comment by gunzip** [comment]
checklist per controlli custom https://w3c.github.io/aria-in-html/#checklist

**Comment by giovanisp** [comment]
@jdeyla puoi condividere i punti della vostra checklist e i criteri per stabilire i requisiti "bloccanti" ?

**Comment by jdeyla** [comment]
I criteri sono semplici, già li proponemmo al tavolo che doveva decidere i requisiti, partendo dal presupposto che 400 e passa controlli a pagina erano poco sostenibili.

L'idea è quella di **partire dalle disabilità**, individuando per ciascuna **i requisiti realmente bloccanti** pr la navigazione su web. Quelli necessari e sufficienti all'accesso, non quelli che migliorano la fruizione. 

Perciò, riprendendo l'ordine precedente:
- **Daltonismo**, problemi percezione colore: Bianco e nero
Riferimenti: Requisiti 3.3, 4.1; WCAG  1.3.3, 1.4.1
-Altri problemi legati alla **percezione colori**: Contrasto
Riferimenti: Requisiti 4.3; WCAG 1.4.3
- Link e controlli utilizzabili (anche navigazione da tastiera, per alcune disabilità motorie)
Riferimenti: Requisiti 3.1, 5.1, 5.2, 11.2; WCAG 1.3.1, 2.1.1, 2.1.2,3.3.2
- **cecità** e "sordità" : alternativi
Riferimenti: Requisiti1.1; WCAG 1.1.1
- **epilessia fotosensibile**: flash >3 sec
Riferimenti: Requisiti 7.2; WCAG 2.3.2
- ** cecità** interferenza bloccante per gli ausili: no audio se >3 sec
Riferimenti: Requisiti 4.2; WCAG 1.4.2
- ** disabilità motorie** ma anche altre questioni legate alla compatiblità futura: Script accessibili
Riferimenti: Requisiti 8.7, 12.2; WCAG 2.4.7,4.1.2
- **problemi vista**: adattabilità
Riferimenti: Requisiti 4.4; WCAG 1.4.4
-** per tutti**, perchè a chi usa gli ausili serve più tempo: tempo regolabile
Riferimenti: Requisiti 6.1, 6.2; WCAG 2.2.2

Ricordo che, la nostra checklist li comprende comunque tutti, perchè per legge li dobbiamo verificare tutti, ma quelli della lista li verifichiamo sempre, gli altri a campione.

**Comment by gunzip** [comment]
aggiungo come riferimento e memo 

http://www.validatore.it/vamola_validator/checker/index.php

**Comment by gunzip** [comment]
esempi di utilizzo del markup "corretto" (es. wai-aria) sono / verranno integrati nel toolkit:
https://italia-it.github.io/ita-web-toolkit/

grazie @jdeyla per le segnalazioni.
