### ISSUE TITLE
Linee guida siti verticali e siti di agenzie governative

### ISSUE THREAD

**Issue by Commedia** [italia-it/designer.italia.it#124]
Come dobbiamo comportarci con siti verticali tipo http://www.garanziagiovani.gov.it/ e siti di agenzie governative come può essere http://www.agenziaentrate.gov.it/

Ci sono o ci saranno delle linee guida specifiche? Vanno uniformati alle linee guida di governo.it?

**Comment by carloreggiani** [comment]
Integro il quesito di Commedia aggiungendo "Ordini/Collegi Professionali" (enti pubblici non economici): in molti enti provinciali si sta mettendo mano in questi mesi ai siti web per adeguarli alla normativa della "Amministrazione Trasparente" e con l'occasione stanno partendo vari progetti di rinnovamento dei siti. 

E' possibile prevedere delle linee guida anche per queste realtà?

**Comment by agidgov** [comment]
Al momento non vi sono indicazioni specifiche per i siti tematici e le Agenzie.

Nello specifico, la roadmap delle Linee Guida prevede, in una prima fase, l’adeguamento dei [siti dei Ministeri](http://indicepa.gov.it/ricerca/n-risultati-percategoria.php?keysearch=&categoria=C1&chicambia=CERCA_PERCAT#R2)

Si raccomanda in ogni caso di sviluppare il sito seguendo le *[best practice](https://github.com/italia-it/designer.italia.it/search?utf8=%E2%9C%93&q=%22si+deve%22)* internazionali. 

Il colore #0066CC è riservato agli header delle PA centrali.

A giugno 2016 verranno rilasciate indicazioni visuali per i siti web delle PA locali.

**Comment by elenabol** [comment]
esistono quindi  linee guida per i siti dei ministeri? nello specifico dobbiamo lavorare sui siti degli istituti periferici del ministero beni culturali ( MiBACT)

**Comment by agidgov** [comment]
per i siti delle PAC, dato lo stato prototipale delle LG, e poiché risulta utile nel convergere verso elementi visuali condivisi, AgID collabora tramite contatto diretto

**Comment by gunzip** [comment]
#131

**Comment by giovanisp** [comment]
@agidgov novità sugli aggiornamenti delle linee guida ?

**Comment by agidgov** [comment]
Le linee guida contengno (e conterrano)

1. indicazioni trasversali alle diverse tipologie di sito (principi di accessibilità e usabilità): dovrebbero (nel caso dell'accessibilità levare il condizionale) esser applicate da subito
2. elementi di visual design: indicazioni su layout, tipografia, utilizzo dei colori, stile di form / bottoni, ...: dovrebbero esser applicati quanto possibile le LG saranno ampliate con materiale HTML/CSS in modo da facilitarne l'adozione
3. elementi che caratterizzano una identità trasversale a tutte le PA (layout di header / footer): a stretto giro verranno integrate nei testi indicazioni più precise
4. elementi che caratterizzano una identità peculiare alla tipologia di PA: attualmente l'unico argomento che ricade in questa categoria è la prescrizione del colore #0066cc per i siti istituzionali delle PA centrali

anticipiamo qui, informalmente e per raccogliere feedback, che la direzione è la seguente: prescrivere un layout per l'header simile a quello visibile su funzionepubblica.gov.it / governo.it in merito a

- fascia superiore con indicazione della PA vigilante (o afferente nel caso di siti tematici)
- posizionamento logo (possibilmente svg)
- nome amministrazione **in formato testuale**
- posizionamento icone social
- search box

per quanto riguarda il menu saranno previste alcune tipologie

- hamburger menu (con scritta 'menu' sotto l'icona di apertura)
- menu orizzontale 'semplice' (sulla falsa riga di quello visibile su governo.it)
- mega menu orizzontale con un numero limitato di voci (max 5) simile a quello visibile sul sito del mef

(e versioni repsonsive corrispondenti)

da evitare: menu a tendina 'on hover'

**Comment by digitigrafo** [comment]
ti segnalo che l'url http://funzionepubblica.gov.it non ha il redirect su http://www.funzionepubblica.gov.it

**Comment by danimog** [comment]
Una domanda: per quanto riguarda i siti dei parchi nazionali occorre uniformarsi alle presenti linee guida? e se sì considerati come le amministrazioni locali? 
grazie

**Comment by gunzip** [comment]
si, sono valide anche per i parchi nazionali. 

> e se sì considerati come le amministrazioni locali ?

non sono considerati come PAC (ovvero, **non** devono attenersi alla palette di colori per le PA centrali)

sarebbe interessante se chi si sta occupando del rifacimento di un sito di uno dei parchi potesse condividere la struttura dei menu e il percorso che ha portato a definirla.
