### ISSUE TITLE
Progressive enhancement nel header

### ISSUE THREAD

**Issue by bertob** [italia-it/designer.italia.it#125]
Con Javascript deattivato il header rimane nel suo iniziale, ovvero alto ~200px. Di conseguenza il resto del sito diventa difficile da leggere perchè è in gran parte coperto dal header.

**Comment by gunzip** [comment]
"in gran parte" a quale risoluzione dello schermo ? mi risultano 140px di altezza solo su desktop.

**Comment by bertob** [comment]
Ci sono un sacco di portatili con risuluzione 1366x768 o simile. In quei casi 200px sono più di un quarto dell'altezza (non parlando del fatto che il browser viewport di solito non è tutta l'altezza dello schermo).

**Comment by gunzip** [comment]
committato #142. è un workaround (considerando la priorità non altissima :) 
se ok lascio chiusa la issue.
