### ISSUE TITLE
Sistema cromatico

### ISSUE THREAD

**Issue by Madmartigan81** [italia-it/designer.italia.it#127]
Salve a tutti, nella sezione "Tipografia > Scelta del colore" si consiglia l’adozione di un sistema cromatico del testo dove i seguenti:

- Colore link visitato #428fdb;
- Colore testo evidenziato #b2ebed;
- Colore alert #ff0000 (WCAG 2 AA Compliant (18pt+) only);

per colore sfondo 1 #f0f0f0 (Colore sfondo 1), risultano non WCAG 2 AA Compliant, ovvero non garantiscono un rapporto di contrasto minimo tra testo e sfondo di 4,5:1 (AA), come stabilito dalle specifiche di accessibilità.
Per Colore di sfondo #FFFFFF (bianco), i risultati sono i medesimi, tutti con rapporto di contrasto minimo tra testo e sfondo inferiore a 4,5:1.

Volevo domandare se ciò sia voluto o meno, ovvero se le specifiche di accessibilità si riferiscono soltanto al testo "normale" e quindi non ai link.

Grazie

**Comment by gunzip** [comment]
grazie per la segnalazione, stiamo riontrollando tutti i colori, compresi quelli dei bottoni

**Comment by gunzip** [comment]
a latere segnalo che su http://designer.italia.it/linee-guida/tipografia/ i colori sono già stati sottoposti a una prima revisione
