### ISSUE TITLE
Link errato su design.italia.it

### ISSUE THREAD

**Issue by wanbinkimoon** [italia-it/designer.italia.it#129]
Il link che da design.italia.it punta a questa repo è sbagliato in più punti:
1. nel paragrafo della home
2. nel triangolo con il logo github
3. nella call a contribuire sopra al footer

in tutti e tre i casi il link punta a https://github.com/italia-it/design.italia.it e non https://github.com/italia-it/designER.italia.it

**Comment by gunzip** [comment]
vero, grazie. errore nel deploy, dovrebbe essere corretto ora.
