### ISSUE TITLE
Unità di misura testo poco idonea allo scopo

### ISSUE THREAD

**Issue by wanbinkimoon** [italia-it/designer.italia.it#130]
L'unità di misura del testo scelta per esprimere i pesi delle tag nella sezione tipografia è un'unità incompatibile con lo standard css. 
`sp` è un unità di misura usata da google per i sistemi android attualmente non applicabile agli standard web css3

**Comment by gunzip** [comment]
vero, la sezione tipografia è totalmente in revisione, ovvero verrano indicate

- una dimensione minima per ogni breakpoint presente nella sezione griglie
- le formattazioni *consigliate* svincolate dal markup

nel mentre imposto l'unità a px.
