### ISSUE TITLE
Considerare un paragrafo con indicazioni per siti tematici

### ISSUE THREAD

**Issue by saiballo** [italia-it/designer.italia.it#131]
una PA centrale che abbia necessità di un minisito esterno al portale (magari per un evento particolare o per lanciare un servizio speciale) deve usare i colori istituzionali nell'header oppure no (non considerandolo quindi un sito della PA centrale) ?

**Comment by Fraq1974** [comment]
Questione interessante e che a breve sarà molto diffusa.
Header e footer vanno gestiti in uniformità, altrimenti non si capisce dove si è. 
Immaginiamo che ci sia anche un login SPID, è necessario restare dentro colori e organizzazione della testata. 
Probabilmente è buona prassi evitare il proliferare di minisiti ragionando, dove possibile, su un' integrazione nei siti di riferimento . 
A valle di questo, se ho login SPID non posso star fuori e a maggior ragione debbo ragionare sulla possibilità che il servizio sia DENTRO quelli della PA centrale, non altrove; se non ho login SPID ho comunque da gestire la questione del riferimento alla realtà nella quale sto lavorando.
Ragioniamo sempre sul fatto che non è obbligatorio ma se si vuole fare ordine è preferibile dare le coordinate all'utente e se si tratta di servizi non vanno "disseminati" ma messi in ordine con un punto di accesso.

**Comment by saiballo** [comment]
grazie per la risposta Francesca. Concordo con tutto quello che dici ma come sicuramente saprai la difficoltà maggiore non è tanto tecnica quanto far capire ai vari dipartimenti l'importanza di rientrare tutti nello stesso portale. e purtroppo su questo non abbiamo una norma forte che ci aiuti.

Nella PA dove sto lavorando, ogni ufficio vuole distinguersi dagli altri e quindi è un continuo proliferare di minisiti senza una minima coerenza stilistica... ormai abbiamo una galassia di siti e sitarelli che è difficile anche gestire

**Comment by gunzip** [comment]
chiudo la issue. in genere la leva sui dipartimenti si realizza (anche) in una questione economica (se il minisito va nel budget della PA ne va tenuto chiaramente conto).
