### ISSUE TITLE
Integrazioni utilizzo immagini

### ISSUE THREAD

**Issue by Strae** [italia-it/designer.italia.it#132]
Cioè con le linee guida per l'accessibilità come l'obbligo dell'attributo alt valorizzato per i non vedenti etc...
È una dimenticanza o non essendo una cosa prettamente di design è volutamente mancante?

**Comment by gunzip** [comment]
è già menzionato qui http://design.italia.it/linee-guida/accessibilita/ dove tra l'altro si prescrive la conformità alle wcag liv. aa.
 
tuttavia sarebbe utile un paragrafo sull'utilizzo delle immagini con un *si dovrebbe evitare l'utilizzo di immagini decorative*, ovvero di tutte quelle immagini che non aggiungono nulla al contenuto testuale, appesantendo la pagina graficamente e come byte da scaricare. proviamo a integrarlo.

**Comment by mariocariello** [comment]
Buongiorno a tutti, volevo suggerire la gestione delle immagini nelle pagine che usa il sito www.theguardian.com.
per esempio questo articolo:
http://www.theguardian.com/world/2016/apr/28/indonesia-firing-squads-year-after-bali-nine-executions
la cosa interessante è che ogni immagine ha i suoi bottoni social e che è possibile condividere lo stesso articolo con diverse immagini a seconda del bottone che si clicca sotto l'immagine che si vuole condividere
![2016-04-28_152844](https://cloud.githubusercontent.com/assets/12431034/14887393/eeb351a8-0d55-11e6-9ed3-a7a8b6e224a5.jpg)
![2016-04-28_152823](https://cloud.githubusercontent.com/assets/12431034/14887392/eeb203de-0d55-11e6-9619-73edb975b538.jpg)
