### ISSUE TITLE
Validazione CSS W3C

### ISSUE THREAD

**Issue by fortimic** [italia-it/designer.italia.it#134]
A causa dell'utilizzo di Bootstrap i CSS risultano non validi per il W3C, anche se scritti correttamente.

https://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fdesign.italia.it%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=it

Bootstrap risponde cosi a questo problema:

> Generally speaking, we don't worry about W3C validation. Practically speaking, it honestly doesn't make much sense to strive for it in most production environments if industry accepted practices are viewed as errors. All the CSS we use is valid, and while some lines are hacks (* for IE7, \9 for IE7-9, etc), it all renders as expected. I'm sure much of this will be cleaned up as we drop legacy browser support (I see lots of hiccups for the IE hacks).

> You're conflating two separate issues—validation doesn't mean accessibility. I have little to no interest in ensuring we pass validation at this time. However, I'm very keen on being as accessible as possible.   

Ai fini degli adempimenti di legge è obbligatoria la validazione dei CSS?
Dobbiamo togliere il logo della validazione dei CSS dai nostri siti, oppure verrà fatto qualcosa per "sistemare" i css?

**Comment by gunzip** [comment]
spunto interessante, vedremo se/come formalizzare l'argomento nelle LG

informalmente: non è necessario che un CSS sia valido. la validazione è importante laddove un errore pregiudica una funzionalità. oggi i browser sono più "resilienti" e spesso non si verifica il caso.

personalmente ritengo i loghi della validazione un po' "retrò", per quanto mi riguarda si potrebbero togliere ovunque, considerato anche che non aggiungono nulla che possa interessare al cittadino...

BTW

- [usa](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fstandards.usa.gov%2F&profile=css3&usermedium=all&warning=1&vextwarning=&lang=it)
- [uk](https://jigsaw.w3.org/css-validator/validator?uri=gov.uk&profile=css3&usermedium=all&warning=1&vextwarning=&lang=it)

non è prevista (non lo sarà mai ?) una revisione del CSS del sito per renderlo valido.

**Comment by gunzip** [comment]
ulteriori sviluppi in #91

**Comment by darkmartin** [comment]
Potrebbe essere utile formalizzare la posizione, giusto perché in fase di review dell'accessibilità quello del parsing è uno dei controlli che vengono fatti – e sappiamo benissimo che l'accessibilità di un contenuto non dipende dalla presenza dell'attributo `border-radius` nel css.

**Comment by jdeyla** [comment]
La questione è interessante, non banale e formalmente pesante, ma **forse una soluzione c'è**, una strada potrebbe essere questa:

La **validazione del codice è un requisito generale** (Parsing) necessario ad esempio  per evitare ambiguità nel codice (se ho due elementi con id uguale, gli ausili hanno problemi) e le WCAG 2 dicono questo https://www.w3.org/TR/WCAG20-TECHS/general.html#G134 

**Come vedrete, non si parla di validatori CSS**,  perchè si parla solo del linguaggio con cui si scrive la struttura. Quello infatti può creare problemi. La validazione aiuta ad individuarli prima.

**La mancanza della richiesta della validazione del codice CSS**, nelle specifice WCAG 2, non può essere una svista, ed è ciò che **apre la strada a Bootstrap**. Se non è specificato, possiamo considerarlo non necessario. 
Un framework quindi potrebbe risultare accettabile (per legge quindi ammissibile) se rispettasse tutte le tecniche CSS: https://www.w3.org/TR/WCAG20-TECHS/css.html

Sbaglio?

**Comment by gunzip** [comment]
abbiamo introdotto una pagina http://designer.italia.it/linee-guida/dispositivi/ in cui, nel paragrafo finale, viene espresso il concetto

**Comment by jdeyla** [comment]
Beh allora cambiate quel paragrafo. 
Perchè c'è una legge dello Stato che dice che devi rispettare dei requisiti, e se non chiarisci la questione in modo formale, non puoi scrivere su un documento dello Stato, di non rispettarla.
Nella pratica quel paragrafo dice cose sensate, ma va data una risposta formale corretta.

**Comment by gunzip** [comment]
@jdeyla non mi è chiaro quali requisiti si suggerisce di non rispettare (come hai sottolineato la validazione CSS non è prescritta dalle WCAG)

**Comment by jdeyla** [comment]
Non è che lo dite esplicitamente, ma quasi.
Il paragrafo di spiegazione  non dovrebbe dire "D'altro canto, un CSS (o HTML) totalmente validi non assicurano di per sé che il sito sia accessibile."

Perchè l'HTML DEVE essere valido

Dite piuttosto qualcosa del tipo
"E non è nemmeno richiesto che un sito accessibile abbia codice CSS valido"

**Comment by gunzip** [comment]
> "D'altro canto, un CSS (o HTML) totalmente validi non assicurano di per sé che il sito sia accessibile."

La frase *non implica* che sia amesso un HTML non valido. Tuttavia mi rendo conto che potrebbe generare l'equivoco. ho inserito una parafrasi e levato il riferimento all'HTML (per evitare fraintendimenti che in effetti potrebbero scaturire):

"La validazione del CSS non è inoltre sufficiente a garantire l'accessibilità."

**Comment by LivioMo** [comment]
riprendo Gunzip: personalmente non vedo nessun problema nell'utilizzo di un CSS che non valida. vedo invece un problema di tempi e costi nel grantire il contrario (a che pro ?)

Il problema è costituito dal fatto che stiamo parlando di siti della PA, per i quali viene richiesto che  i linguaggi di marcatura (compreso CSS) devono essere utilizzati in modo conforme alle specifiche previste nelle relative grammatiche formali di riferimento. 

Il fatto che un CSS o HTML totalmente validi non assicurino di per sé che il sito sia accessibile è sicuramente vero, ma ininfluente nella discussione corrente.
