### ISSUE TITLE
Fix colore bottoni / link active SPID

### ISSUE THREAD

**Issue by tbenr** [italia-it/designer.italia.it#136]
Ciao,
sto avendo dei problemi ad inserire il tasto [entra con SPID](https://github.com/italia-it/spid-sp-access-button) all'interno della mia homepage basata su **agid-bootstrap**

stili con i css **spid-sp-access-button.min.css**:
![image](https://cloud.githubusercontent.com/assets/15999009/15249703/40c8078c-1921-11e6-9e9f-1615f35edbd5.png)

risulato ufficiale:
![image](https://cloud.githubusercontent.com/assets/15999009/15249881/42587a2c-1922-11e6-90c7-ce959330a7d9.png)

stili quando carico **agid.css** e poi **spid-sp-access-button.min.css**
![image](https://cloud.githubusercontent.com/assets/15999009/15249774/b56bd744-1921-11e6-8454-237fe560d96c.png)

conseguenze (testo non bianco e immagini non ridimensionate)
![image](https://cloud.githubusercontent.com/assets/15999009/15249838/fc0b9586-1921-11e6-905f-d22109d428ee.png)

Sbaglio qualcosa?
Suggerimenti?

**Comment by umbros** [comment]
Grazie della segnalazione riproduco l'anomalia e ti segnalo la soluzione

**Comment by gunzip** [comment]
Aggiungo che i CSS sono in fase di rielaborazione (anche per evitare questo tipo di problematiche).

Nel medio termine la roadmap prevede di integrare i seguenti elementi che attualmente risultano indipendenti:

1. CSS dei componenti scaricabili (diventa un progetto autonomo)
2. CSS per il sito design.italia.it (che utilizzerà 1.)
3. CSS per componenti SPID (che utilizzeranno 1.)

L'esigenza a brevissimo termine era di fornire una implementazione di riferimento per evitare il proliferare di interfacce di login differenti nonché di dare una identità a SPID rendendo immediatamente identificabili i punti di accesso.

**Comment by tbenr** [comment]
Ok, grazie per i chiarimenti.

**Comment by tbenr** [comment]
Ciao,
volevo condividere il workaround che ho implementato per risolvere i problemi più evidenti:

1. ho aggiunto:
``
                            <style>
                                a:visited
                                {
                                    color: #FFF;
                                }
                            </style>
`` prima di `<!-- AGID - SPID IDP BUTTON MEDIUM "ENTRA CON SPID" * begin * -->`

2. ho aggiunto `style="box-sizing: content-box !important;"` in ogni tag `<img>` relativi alle immagini degli identity provider spid.

**Comment by umbros** [comment]
Nei prossimi giorni verrà realizzata la nuova soluzione per la scelta degli IDP.

**Comment by gunzip** [comment]
https://italia-it.github.io/ita-web-toolkit/components/detail/spid.html
