### ISSUE TITLE
Contrasto colore

### ISSUE THREAD

**Issue by nerobizzarro** [italia-it/designer.italia.it#137]
L'azzurro #66A5E3 utilizzato per esempio nell'area dedicata alla partecipazione delgi utenti su Github non risulta sufficientemente contrastato rispetto al bianco degli elementi A.
Lo stesso errore viene evidenziato anche con una semplice verifica oggettiva insieme a un errore altrimenti non visibile con un approccio soggettivo per la realizzazione dell'angolo in alto a destra github in cui sia il background che il foreground ereditano il medesimo colore #06c

**Comment by gunzip** [comment]
è vero ne siamo consapevoli (è praticamente da sempre nella lista dei todo), sarà corretto con la giusta priorità. puoi fare in caso una pull request per velocizzare ?

**Comment by nerobizzarro** [comment]
Dovrei scegliere un colore sostitutivo in quel caso! ;)

**Comment by gunzip** [comment]
006b6f

**Comment by gunzip** [comment]
se è ok lascio chiusa la issue: http://designer.italia.it/

**Comment by nerobizzarro** [comment]
Okey.

**Comment by nerobizzarro** [comment]
In realtà ho notato che il colore proposto non va bene con il grigio scuro del testo semplice. Una soluzione potrebbe essere il colore: #408cd9.

**Comment by gunzip** [comment]
#408cd9 sembra non andar bene col bianco, metto il testo nero

**Comment by nerobizzarro** [comment]
Andrebbe bene con quel grigio scuro in caso di testo grande. Ma comunque si, meglio nero.
