### ISSUE TITLE
Titolazioni, blocchi logici e skip

### ISSUE THREAD

**Issue by nerobizzarro** [italia-it/designer.italia.it#138]
Le titolazioni presentano un errore di gerarchizzazione per l'assenza dell'elemento h2 tra il titolo del sito (h1) e il sommario delle linee guida (h3).
I blocchi logici non sono tutti definiti con titolazioni che ne chiariscano immediatamente la natura, inoltre non sono previsti skip che permettano di tornare a inizio pagina dove è localizzato il menu di accesso alle aree principali di pagina.

**Comment by gunzip** [comment]
intanto grazie per le segnalazioni. tuttavia sarebbe auspicabile aprire una issue per ogni richiesta diversa, soprattutto se afferenti tematiche non omogenee. solo così possiamo assegnargli una priorità differente.

per intenderci: le segnalazioni riguardo **il sito** sono importanti (es. skiplink mancante etc.), ma molto meno di quelle riguardanti **i contenuti** (es. "I blocchi logici non sono tutti definiti con titolazioni che ne chiariscano immediatamente la natura"). spesso hanno tempi differenti e coinvolgono persone differenti.

ancor meglio sarebbe effettuare una richiesta di modifica diretta (pull request): è più rapido sia per noi che per chi vuole contribuire :)

**Comment by gunzip** [comment]
1. ho sostituito h3 -> h2 come titolo del sommario
2. puoi elaborare / proporre nuove intestazioni eventualmente ?
3. non mi è chiaro, puoi elaborare / proporre un cambiamento della struttura ?

**Comment by nerobizzarro** [comment]
1. si, ho visto e infatti adesso non sono presenti errori di gerarchia.
2 e 3. volentieri.

Per sommi capi ti illustro qualche info qui: 

- metterei delle titolazioni su 1. menù di salti di pagina e 2. menù nel footer
- sposterei la dicitura Governo Italiano adiacente al titolo del sito (H1)
- sposterei  il menu di navigazione interna sotto questi due elementi per una questione di identità del sito
- la dicitura Governo Italiano dovrebbe avere il relativo link di riferimento
- è buona prassi rendere cliccabile anche il logo del sito
- ... 

Sarebbe utile fare un assestment completo.

**Comment by gunzip** [comment]
ho linkato i loghi e la scritta governo che ho spostato vicino all'h1.
per quanto riguarda inserire l'inserimento di intestazioni per i blocchi logici 
aspetto un ulteriore feedback :)

**Comment by nerobizzarro** [comment]
Okey! ;)
