### ISSUE TITLE
Ispirarsi a Material Design per integrazioni su look & feel

### ISSUE THREAD

**Issue by MLCgiustizia** [italia-it/designer.italia.it#143]
Un suggerimento trasversale, pertinente per le etichette template, bottoni, etc.: trovo molto istruttivo quanto pubblicato da Google sul [Material Design](https://www.google.com/design/spec/material-design/introduction.html). Forse il visual migliorerebbe prendendo in considerazione alcuni suggerimenti (come ombre, modalità di movimento, etc.) lì illustrati ed esemplificati.

**Comment by gunzip** [comment]
Assolutamente; si dovrebbe valutare quali temi / elementi possono esser estrapolati ed esemplificatit considerando anche il differente target. A questo proposito segnalo la #90 come correlata (capitolo su utilizzo delle animazioni).

**Comment by gunzip** [comment]
ref. https://github.com/italia-it/designer.italia.it/issues/90 #90
