### ISSUE TITLE
Implementazione, grafica e contenuti dovrebbero essere separati

### ISSUE THREAD

**Issue by santec** [italia-it/designer.italia.it#149]
Mantenere l'implementazione del sito, la grafica e i contenuti in un unico repository non è funzionale. E' logico pensare che persone diverse si occupino di aree diverse. Inoltre un commit che mira a intervenire su un'aera potrebbe inavvertitamente introdurre un bug nelle altre due.

**Comment by gunzip** [comment]
Implementazione del sito e grafica mi sembrano strettamente correlati (o non ho compreso cosa si intende esattamente con "grafica" :). Per quanto riguarda i testi (ovvero il contenuto della dir 'pages') lascerei anch'essi dove sono per motivi pragmatici (sarebbe dispersivo altrimenti). È lo stesso approccio utilizzato da UK / USA. Inoltre l'indice del sito va mantenuto assieme ai contenuti.

Per quanto riguarda i bug nell'implementazione, considerato che è comunque minimale e non dirimente, si possono tenere sotto controllo. Ad oggi vi sono state poche *pull request* a riguardo ed è ipotizzabile che la situazione non cambi (l'implementazione del sito ha una priorità molto bassa rispetto al contenuto dei testi).

**Comment by santec** [comment]
E' una scelta, ma in questo modo il progetto è meno organizzato e meno "scalabile".
Per grafica intendo semplicemente un template che dovrebbe trovarsi - secondo me - in un repository differente. Questo template dovrebbe essere indipendente dagli script e dai contenuti.

**Comment by gunzip** [comment]
attualmente esiste una repository dedicata per i template (https://github.com/italia-it/ita-bootstrap). tuttavia poiché stiamo lavorando per dare una forma più strutturata al materiale scaricabile (nel breve/medio termine, riutilizzando quanto già fatto per i siti pilota), al momento è auspicabile collaborare più sui testi più che sul resto.
