### ISSUE TITLE
Convergere su un unico set di icone

### ISSUE THREAD

**Issue by fiaschi** [italia-it/designer.italia.it#15]
Mi pare corretta l'imposizione di un'iconografia coerente. Nelle linee guida si consiglia di scegliere un set grafico da font awesome o utilizzare il set di bootstrap, perché non fare di più e definire uno standard comune?

**Comment by GianniSinni** [comment]
È in fase di realizzazione un apposito set di icone

**Comment by didoo** [comment]
Riguardo alle icone, se possibile chiederei una discussione aperta, su più fronti.

Dal punto di vista tecnico:
- il caricamento delle icone è fatto via `@include` nei CSS, cosa che include automaticamente i font anche se potenzialmente potrebbero non essere richiesti ma soprattutto blocca il rendering delle pagine nel browser, al momento del caricamento della pagina, in quanto appunto font (se occorre spiego meglio il perché, ma fidatevi).
- è in corso un dibattito sull'uso di SVG al posto di Icon Fonts, principalmente per ragioni di accessibilità. Qui la bellissima presentazione che Seren Davies a fatto al riguardo (lei soffre di dislessia, e l'uso di Icon Fonts è problematico per persone che soffrono di questo disturbo):
https://www.youtube.com/watch?v=9xXBYcWgCHA
https://speakerdeck.com/ninjanails/death-to-icon-fonts
ovviamente poi, se si vuole rimanere fedeli all'approccio Bootstrap-oriented, allora occorre rimanere su Glyphicons, non ci si scappa.

Dal punto di vista iconografico: 
- sarebbe preferibile usare un unico set di icone per preservare una certa coerenza visuale: da quel che vedo negli esempi, sono incluse sia icone di Font Awesome che di Glyphicons (e non dimentichiamo che questo fra le altre cose appesantisce le pagine ulteriormente)

**Comment by didoo** [comment]
Nota a margine: pare che la (futura) versione di Bootstrap deprecherà Glyphicons a favore di Font Awesome: https://github.com/twbs/bootstrap/pull/17021

**Comment by darkmartin** [comment]
Un set di icone base è sicuramente utile, sarebbe comodo che la sua inclusione fosse opzionale e che ci fosse un metodo semplice per estendere o sostituire questo set. Quindi quantomeno valuterei la proposta di @didoo sulle icone SVG o le metterei sulla *roadmap*.

**Comment by gunzip** [comment]
@GianniSinni, @didoo che ne dite se in questo periodo di inter-regno forziamo l'utilizzo di font-awesome e leviamo tutti i riferimenti a glyphicon sia nei testi che nei template ?

**Comment by gunzip** [comment]
Create #41 e #42

**Comment by gunzip** [comment]
set minimale di icone incluso in https://github.com/italia-it/ita-web-toolkit/tree/master/src/icons/ita
