### ISSUE TITLE
"Vivere a" non dovrebbe contenere informazioni per i turisti

### ISSUE THREAD

**Issue by santec** [italia-it/designer.italia.it#150]
Nella pagina "Architettura dell'informazione" leggo:

"Vivere a [Nome del comune]: contiene tutte le informazioni pratico-orientative riguardanti il territorio, come eventi e turismo."

Distinguiamo però tra i tipi di utenti. L'utente turista non cliccherà su "vivere a", perché il titolo stesso gli suggerisce di evitare. Il residente invece cliccherà, ma la sezione turismo non lo riguarda.
Inserire eventi e informazioni turistiche nella stessa macrocategoria ha senso, ma il titolo proposto tende a impedirne la fruizione.

**Comment by gunzip** [comment]
Giusta osservazione.

La proposizione "*a*" è stata inserita ex-post considerando che alcuni (pochi in effetti) nomi di comuni potevano non adattarsi alla dicitura "Vivere <nome comune>" visibile sui siti pilota http://www.comune.biella.it/web/ http://alpha.regione.sardegna.it/ http://www.comune.matera.it/ senza preposizione (che cambia effettivamente il significato). Correggo il testo con 'vivere [nome comune]'.
