### ISSUE TITLE
Errore installazione

### ISSUE THREAD

**Issue by 286design** [italia-it/designer.italia.it#151]
Seguendo la procedura di installazione, dopo aver lanciato il comando 

> gulp serve

node genera il seguente errore:

`[14:54:17] Starting 'clean'...
[14:54:17] Finished 'clean' after 11 ms
[14:54:17] Starting 'scripts'...
[14:54:18] Starting 'fonts'...
[14:54:18] Starting 'styles'...
[14:54:18] Starting 'templates:pages'...
[14:54:18] Starting 'webroot'...
[14:54:18] Starting 'images'...

scripts/main.js
Use the function form of "use strict".
'document' is not defined.
'document' is not defined.
'document' is not defined.
'document' is not defined.
'document' is not defined.
'document' is not defined.
'document' is not defined.
'document' is not defined.
'location' is not defined.
'window' is not defined.
'window' is not defined.
'window' is not defined.
'window' is not defined.
'window' is not defined.
'window' is not defined.

  ⚠  16 warnings

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: JSHint failed for: scripts/main.js

Qualcuno ha riscontrato questo problema? Ho clonato il repository pochi minuti fa.

**Comment by gunzip** [comment]
ho provato a riprodurre l'errore ma senza (in)successo. puoi darmi qualche info riguardo il sistema operativo (win/mac/linux), la versione di gulp installata globalmente ? (gulp -v) e se hai jshint installato globalmente ? (jshint -v)

**Comment by 286design** [comment]
Lavoro su MAC, 

jshint v2.9.2
gulp 3.9.1
node 5.1.0

Uso già node, gulp e bower su altri progetti, e funziona tutto perfettamente. 

Riprovo a fare l'installazione, magari va a buon fine.

**Comment by 286design** [comment]
Perfetto, adesso funziona. Ho provato pure a clonare nuovamente il repository, e a rifare tutta la procedura, e funziona perfettamente.

Grazie
