### ISSUE TITLE
Adeguamento linee guida alla normativa vigente e alle best practices più accreditate

### ISSUE THREAD

**Issue by LivioMo** [italia-it/designer.italia.it#152]
Buongiorno. Apprezzo molto lo sforzo, ma leggendo le linee guida ho notato diverse incongruenze ed inesattezze, oltre che una quantità di disposizioni piuttosto arbitrarie. In alcuni casi addirittura il seguire le linee guida condurrebbe a produrre un sito non a norma.
Per esempio, la pagina Accessibilità dichiara:

SI DEVE
Il sito web deve raggiungere il livello di conformità AA così come definito nelle Web Content Accessibility Guidelines - WCAG 2.0. Le 12 linee guida e i criteri di conformità delle WCAG 2.0 discendono dai quattro principi che fanno da pilastri all’accessibilità del Web. 

No, non è per niente vero, per i siti della PA il riferimento è il DM 20 marzo 2013 e a questo la PA deve fare riferimento. Pagina da rifare...

Oppure, pagina Tipografia:

dichiarare un web font come font istituzionale è perlomeno bizzarro, anche se consentito. Però così facendo si penalizzano tutti gli utenti con connessioni lente, che per vedere qualcosa dovranno aspettare lo scaricamento del font ovviamente.
Invece dei credits degli autori, perché non pubblicate qualcosa che spieghi come mai è stata scelta quella font, a quali test è stata sottoposta per verificarne il grado di leggibilità, chi e come sono stati fatti i test, e così via.
Nella stessa pagina si leggono affermazioni curiose e incomprensibili: 

SI DEVE
Un paragrafo di testo non deve mai essere composto in una dimensione inferiore a 12px. La dimensione standard del paragrafo di testo è prevista in 18px. Un paragrafo di testo deve essere composto sempre nel peso Regular, mai in Light o Bold. L’interlinea avrà generalmente una dimensione pari a circa il 150% della dimensione del corpo del carattere (per esempio un testo in corpo 18px avrà un’interlinea di 27px). 

Dichiarare le font in px, ok, qui siamo alla preistoria del web design. Dimensione standard in 18px? E perché? Chi l'ha detto? Mai usare il bold o il light? Perché? Chi l'ha detto? Sono assunzioni arbitrarie che vanno documentate.

SI DEVE
Ogni riga di testo non deve mai superare la lunghezza massima di 75 caratteri. 

Ma veramente??? Questo può avere un valore per un testo stampato su carta con una font fissa, stiamo parlando di web... sconfortante nel 2016.

SI DOVREBBE
L’uso dei tag semantici consente di venire incontro ai requisiti di accessibilità, permettendo la corretta interpretazione del testo da parte dei device di ausilio alla lettura. 

No, SI DEVE, come richiesto dal DM 20 marzo 2013.

Sono presenti incongruenze anche con la normativa relativa al CAD, Codice dell'Amministrazione Digitale.

Insomma, boh sono abbastanza perplesso. Scusate la franchezza

Livio Mondini

**Comment by gunzip** [comment]
Ciao Livio, intanto grazie per essere entrato nel merito.

> No, non è per niente vero, per i siti della PA il riferimento è il DM 20 marzo 2013 e a questo la PA deve fare riferimento. Pagina da rifare...

Nel primo paragrafo si eplicita chiaramente "Le pubbliche amministrazioni *devono* rispettare 12 requisiti tecnici riportati nell’Allegato A". L'allegato, nella sua versione aggiornata dal DM 20 marzo 2013, è linkato nei 12 requisiti.

Se quindi ho inteso bene il suggerimento si ridurrebbe allo spostare graficamente il 'si deve' al primo paragrafo (riferimento normativo) piuttosto che al requisito tecnico delle WCAG. In generale, nella stesura dei testi, si è scelto di privilegiare un approccio pragmatico e meno burocratico, tuttavia mettiamo l'ipotesi sul piatto.

> Però così facendo si penalizzano tutti gli utenti con connessioni lente, che per vedere qualcosa dovranno aspettare lo scaricamento del font ovviamente."

no, è un dettaglio implementativo: è possibile utilizzare un fallback con un font di default che compare quindi senza ritardo.

viceversa, nel caso peggiore, tale penalizzazione si verifica solo al **primo caricamento di una qualsiasi pagina**, dopodiché il font è salvato nella cache del browser. inoltre se i file vengono serviti tramite una CDN il ritardo complessivo nella navigazione del sito è assolutamente negligibile. ancor minore è l'impatto se tale font (condiviso sulla CDN) viene utilizzato trasversalmente ai diversi siti (motivo in più per convergere su un unico typeface "istituzionale").

> Invece dei credits degli autori

anche se è opinabile che i *credits* tolgano spazio al resto dei contenuti, volendo incorporare il tuo suggerimento e considerando che tra i principi vige il pieno coinvolgimento di tutti, possiamo considerare di omettere i credits qualora urtino la sensibilità di coloro che si sentono altresì esclusi. d'altronde è anche nel nostro interesse evitare atteggiamenti livorosi da parte di detrattori ostinati e/o motivati da rancori personali; pertanto per non sprecare un buon consiglio sottoporrò l'ipotesi al gruppo di lavoro.

> perché non pubblicate qualcosa che spieghi come mai è stata scelta quella font, a quali test è stata sottoposta per verificarne il grado di leggibilità, chi e come sono stati fatti i test, e così via.

per quanto riguarda il "motivare i perché di alcune scelte" (se non di *tutte*, a questo punto), è un'osservazione comprensibile. tuttavia vorremmo evitare che le LG si trasformino in un trattato e/o che assumano un piglio accademico. il *target precipuo* delle LG non sono gli esperti degli argomenti trattati (usabilità, accessibilità, visual design) che già conoscono quanto scritto nei contenuti (e oltre): tra gli obiettivi è sensibilizzare proprio coloro che, nonostante una normativa di supporto (laddove presente) e la buona volontà di altri tentativi simili effettuati nel recente passato, non hanno mai messo in pratica i principi. ogni parola non necessaria si rivela controproducente in quest'ottica.

> Dichiarare le font in px, ok, qui siamo alla preistoria del web design.

decisamente opinabile (vedi lavori UK e USA). potresti proporre un modo per indicare un font-size minimo che non sia in valori assoluti ?

> Dimensione standard in 18px? E perché? Chi l'ha detto? Mai usare il bold o il light? Perché? Chi l'ha detto? Sono assunzioni arbitrarie che vanno documentate.


> "chi l'ha detto" 

le linee guida (in consultazione pubblica, sottoposte a test tramite i siti pilota). anche qui, riguardo l'esplicitare le motivazioni di ogni scelta, valgono le considerazioni sopra riportate.

> "e perché ?"

prendere delle decisioni "a monte" (testate e condivise) è fondamentale per tagliare tempi e costi nella progettazione dei siti ed evitare che vengano prese "a valle" da coloro (es. politici e amministrativi) che non padroneggiano la materia.

> Ma veramente??? Questo può avere un valore per un testo stampato su carta con una font fissa, stiamo parlando di web... sconfortante nel 2016.

Consiglio di consultare l'immensa letteratura a riguardo:

https://www.google.it/?ion=1&espv=2&client=ubuntu#safe=off&q=+maximum+paragraph+line+length

nonché agli egregi lavori di gov.uk e/o web design standards USA, elaborati da persone che vivono in questo secolo:

"A good rule of thumb is a max of 75 characters per line as it becomes harder to read beyond that point." - https://designnotes.blog.gov.uk/2015/09/16/tips-for-creating-good-typography/


> L’uso dei tag semantici consente di venire incontro ai requisiti di accessibilità, permettendo la corretta interpretazione del testo da parte dei device di ausilio alla lettura.
> No, SI DEVE, come richiesto dal DM 20 marzo 2013.

Questo è un suggerimento interessante e concreto, come auspichiamo che siano tutti in generale: epurati da qualsiasi giudizio di merito (non per ragioni di morale ma di economia: "less is more").

Lo giro a chi si è occupato del capitolo.

> Sono presenti incongruenze anche con la normativa relativa al CAD, Codice dell'Amministrazione Digitale.

Potresti elaborare quali ? Possibilmente in una issue a parte, per non trasformare questa in un forum e rendere più difficoltoso il lavoro.

> Insomma, boh sono abbastanza perplesso. Scusate la franchezza

Ne prendiamo atto e cerchiamo di usare le perplessità altrui per migliorare.

**Comment by matteobelfiore** [comment]
@LivioMo dichiarare i font in `px` non è una questione di preistoria o no. Non esistono ragioni universali per cui `px` sia sbagliato e `em` sia corretto.

Sono semplicemente due unità di misure differenti che svolgono due compiti diversi: `px` è un'unità di misura assoluta, `em` no, ed è, come credo tutti sappiate, relativa al font size corrente. La scelta di uno o dell'altro dovrebbe essere dettata dal design, dalla tipologia e dalle funzionalità del sito. L'utilizzo di `px` non è necessariamente *sbagliato* a priori.

Questa convinzione —che `px` sia il "male" assoluto— deriva dal fatto che per anni si sia fatta campagna per l'utilizzo di `em`, perché `em` === "accessibilità". Questa premessa —oltre ad essere approssimativa perché fondata su postulato erroneo, ovvero che l'uso di un'unità di misura piuttosto che un'altra equivalga ad un requisito di accessibilità, invece che il fornire la possibilità di cambiare la dimensione della font— non tiene conto del fatto che una delle vere ragione per cui `em` venisse spesso usato fosse l'impossibilità di ottenere un render delle font invariato su diversi browser.

Quindi, mentre i browser evolvevano e cominciavano a fornire render delle font uniformi (anche utilizzando `px`) moltissimi sviluppatori e designer ancora dovevano mettersi al pari con l'intero discorso `px`, `em`, `rem`, ecc. Ora ci troviamo (o almeno, io sento di trovarmi) in una situazione paradossale in cui coloro che per primi cominciarono ad usare `em` e `rem` e che tenevano e tengono conto sempre e comunque dell'accessibilità, ora che nel 2016 sanno di poter utilizzare `px` come unità di misura con relativa tranquillità ma vengono additati come sviluppatori preistorici...

Sono anche in disaccordo con quanto dici riguardo i "75 caratteri", perché non si tratta di una questione di "carta stampata" o no, bensì di leggibilità di un testo. Ma vedo che @gunzip ha già fornito un link appropriato.

**Comment by LivioMo** [comment]
Boh, le risposte lasciano ancora più perplessi :). Sono entrato leggermente nel merito, proprio perché penso che i destinatari delle linee guida siano dei tecnici che si occupano di realizzare siti, e non lettori comuni. A un tecnico si dovrebbe fornire uno strumento pratico, e non teorico. Non ho fatto un debug, cosa che non ho alcuna intenzione di fare, ho soltanto fornito alcuni spunti di riflessione. Giusto come esempio, non ha senso indicare una dimensione della riga in caratteri senza fare alcun riferimento alla dimensione dei caratteri che compongono la riga. Secondo voi una riga di 75 caratteri corpo 12 è lo stesso che con corpo 24? O su un monitor 4k e uno smarphone? Non credo... Questo non è un blog personale dove riportare le proprie convinzioni, magari anche ben documentate ma personali. È un sito del Governo Italiano, e quindi dove possibile quando si fanno asserzioni queste andrebbero documentate (secondo me, ovviamente). 
Lascio una lettura tipografica, che credo possa essere utile: https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/

**Comment by gunzip** [comment]
segnalo che nell'articolo che riporti è indicata "una dimensione della riga in caratteri senza fare alcun riferimento alla dimensione dei caratteri che compongono la riga":

> 65 characters (2.5 times the Roman alphabet) is often referred to as the perfect measure. Derived from this number is the ideal range that all designers should strive for: 45 to 75 characters (including spaces and punctuation) per line for print. Many web designers (including me) apply that rule directly to the web. I’ve found, however, that we can reliably broaden the range to 45 to 85 characters (including spaces and punctuation) per line for web pages.

**Comment by LivioMo** [comment]
Mica è la Bibbia... ma spiega bene che non esiste una misura che SI DEVE. Si dovrebbe... così come esistono moltissime tecniche che permettono di rendere il testo fruibile alla più grande platea di persone possibile, che dovrebbe essere un punto di onore. Per esempio, https://biroblu.wordpress.com/2013/03/21/sviluppare-siti-per-utenti-con-disabilita-cognitive-e-difficolta-nellapprendimento/

Era il 2005...
