### ISSUE TITLE
Pagina Accessibilità

### ISSUE THREAD

**Issue by LivioMo** [italia-it/designer.italia.it#154]
La pagina presenta alcune imprecisioni e un errore: 
1. la frase di apertura andrebbe modificata in "Le pubbliche amministrazioni devono rispettare 12 requisiti tecnici riportati nell’Allegato A di accessibilità dei siti web previsti dal Decreto Ministeriale 8 luglio 2005 aggiornato dal DM 20 marzo 2013 - GU Serie Generale n. 217 del 16-9-2013

2. Dicendo che SI DEVE  raggiungere il livello di conformità AA così come definito nelle Web Content Accessibility Guidelines - WCAG 2.0 si induce un errore. Il DM normativo è sì ispirato e fondato sulle WCAG 2, ma la normativa italiana richiede anche due punti AAA e se ricordo bene anche un A, non è la completa fotocopia. Paradossalmente se qualcuno seguisse quel si deve ne deriverebbe un sito fuori norma.

**Comment by gunzip** [comment]
accolta (grazie). ho modificato la pagina: http://designer.italia.it/linee-guida/accessibilita/ 
come riferimento alle wcag ho lasciato quello presente nell'allegato a ("Il rispetto dei seguenti requisiti corrisponde al livello di conformità AA delle WCAG 2.0")
