### ISSUE TITLE
Il problema della linearizzazione delle pagine

### ISSUE THREAD

**Issue by LivioMo** [italia-it/designer.italia.it#157]
Anche questa non so bene come classificarla, però propongo il problema. L'uso di markup strutturale per il posizionamento dei contenuti via CSS è nota ed efficace, non ci piove. Però è necessario sottoporre le pagine a un test definito "linearizzazione". Il modo più semplice di farlo secondo me è seguire la tecnica descritta qui:

https://www.searchenginejournal.com/linearize-page/19120/

Dopo aver installato la Web Developer Toolbar, provate a osservare governo.it o comune.venezia.it

Sarà ben visibile che c'è qualcosa che non va...

rif: https://www.w3.org/TR/WCAG20-TECHS/C6.html

**Comment by gunzip** [comment]
puoi elaborare "sarà ben visibile che c'è qualcosa che non va" ? (altrimenti non riusciamo a entrare nel merito)

**Comment by LivioMo** [comment]
Sì, catturerò una schermata e la metto da qualche parte.

**Comment by jdeyla** [comment]
Io ho provato e forse capito la questione. **Secondo me è un falso problema**. Si linearizza una pagina per percepire come questa è strutturata, ovvero come un utente con screenreader, la legge. 
A volte infatti elementi lontani nel codice, a vista sono posti vicini che sono correlati. Un non vedente non può così percepire la correlazione o la conseguenza logica. 

**Non la si linearizza per guardarla.**
Quindi la foto della schermata non ha senso, e se il problema è la sovrapposizione di elementi, il problema non sussiste.

**Comment by gunzip** [comment]
grazie @jdeyla, sono della opinione

**Comment by LivioMo** [comment]
Non è vero Jacopo. Non so perché si parla sempre di screen reader e mai di ipovisione. Poter ridisporre la pagina in modi differenti  senza perdere informazioni è una richiesta, e nel caso del layout in questione il risultato è praticamente inutilizzabile per perdite di informazioni (ancora il meu) e sovrapposizione di elementi.

https://www.w3.org/TR/2008/REC-WCAG20-20081211/#content-structure-separation

**Comment by jdeyla** [comment]
Forse hai ragione, ma
Proviamo a essere concreti.
Se un ipovexdente, capita su un sito fatto come indicato dalla linee guida (es. governo?) può ingrandire infinitamente il font e non c'è perdita di informazioni. E' responsive, si adatta.

Se ha problemi coi contrasti, può disattivare il foglio di stile (e/o sostituire il proprio), e i contenuti, nel codice sono linearmente parlando, fruibili senza confusione, perdita d'informazione ecc. ecc.

Il caso in cui ci sono sovrapposizioni e quello che avviene usando la webdev toolbar e il comando linearizza. E' il caso dei nostri ipovedenti, o dei tecnici che verificano? 

A me parrebbe il caso di cambiare sistema di verifica, ma potrei aver dimenticato ancora una volta qualche caso particolare

**Comment by LivioMo** [comment]
No, se sostituisce il foglio di stile con il proprio, linearizzando la pagina ovvero eliminando i posizionamenti via CSS, finisce in una situazione come quella nell'immagine seguente.

https://cibigibi.files.wordpress.com/2016/07/www_governo_it-linearizzato.jpg

A me il problema è stato segnalato da un ipovedente, è concreto e non ha niente a che fare con sistemi di verifica. Capita a chiunque navighi in quel modo, non è nemmeno un caso particolare. È il CSS di Bootstrap che è fatto così così, prova a validarlo... innumerevoli errori di parsing, non sintattici. Per forza che il layout si disfa.

**Comment by jdeyla** [comment]
Io non lo so, ma a me quel che dici non accade,
non si sovrappone proprio niente.

Se uso questo servizio per avere dei fogli di stile da ipovedenti in sostituzione di quello del sito
http://people.ds.cam.ac.uk/ssb22/css/
e scelgo ad es.  60px giallo su nero, me lo scarico e lo applico al sito del governo

Io ottengo qualcosa di completamente fruibile
![www governo it_governo_italiano_presidenza_del_consiglio_dei_ministri_-_2016-07-22_15 51 35](https://cloud.githubusercontent.com/assets/832590/17059189/4d352d80-5024-11e6-8c07-867f018641e8.png)

quello che hai mostrato è ciò che avviene linearizzando e basta, ma se qualcuno fa così, sbaglia tecnica... anche se è un ipovedente.

**Comment by LivioMo** [comment]
Ah ok, è lui che sbaglia tecnica, d'accordo :)
