### ISSUE TITLE
Link sottolineati nel testo: è un obbligo!

### ISSUE THREAD

**Issue by jdeyla** [italia-it/designer.italia.it#158]
Vi segnalo che in più di un'applicazione delle linee guida e nelle sue varianti (siti regione, comuni ecc.), ho trovato i link nel testo non sottolineati.
L'avevo già segnalato perchè è un'eredità di Bootstrap, ma non si può:

WCAG 2
Distinguibile 1.4
Uso del colore 1.4.1

L'esempio di fallimento della tecnica è proprio il nostro caso
https://www.w3.org/TR/WCAG20-TECHS/F73.html

Passi sui link del menù o quelli con accanto un'icona, ma nel testo vanno sottolineati.
In certi casi, nemmeno il colore li distingue (es nelle card delle news).
Usare solo il grassetto è un limite, ti toglie l'unico stile leggibile che si ha a disposizione

Qui non lo sono:
http://www.governo.it/i-ministeri-0
http://www.funzionepubblica.gov.it/uffici/ufficio-la-gestione-amministrativa
http://www.mit.gov.it/come-fare-per/infrastrutture/infrastrutture-strategiche/opendata-e-opencantieri
http://www.comune.venezia.it/archivio/361
ecc. ecc.

**Comment by gunzip** [comment]
l'osservazione è corretta solleciteremo i fornitori.
