### ISSUE TITLE
Errore di rendering Firefox + Linux

### ISSUE THREAD

**Issue by elpaso** [italia-it/designer.italia.it#159]
Il problema si verifica in tutte le pagine, eseguendo lo scroll con la rotella del mouse, PgUp/PgDn funziona correttamente.

![image](https://cloud.githubusercontent.com/assets/142164/16910263/0a545b34-4cd8-11e6-97bc-1ae77ebe23c5.png)

**Comment by gunzip** [comment]
grazie, vero. sembra più un errore di rendering del browser (probabilmente introdotto nelle ultime versioni), vedo come risolvere.

**Comment by gunzip** [comment]
dovrebbe esser risolta, pubblicato fix su designer.italia.it
