### ISSUE TITLE
skip link 

### ISSUE THREAD

**Issue by LivioMo** [italia-it/designer.italia.it#161]
Sul sito di esempio governo.it, nelle pagine sono presenti gli skip link Vai al contenuto o Raggiungi il piè di pagina, ma portano a pagine 404 (http://www.governo.it/tipologie-contenuto/#main e http://www.governo.it/tipologie-contenuto/#footer

Non so se questo dipenda dal kit o dalla particolare implementazione, ma visto che lo stesso accade sul sito comune.venezia forse dipende dal kit?

**Comment by gunzip** [comment]
non sono riuscito a replicare il comportamento. da quale pagina accade ?

**Comment by LivioMo** [comment]
L'elemento è questo:

    <p id="skip-link">
        <a href="#main" class="element_invisible element_focusable">Vai al Contenuto</a>
        <a href="#footer" class="element_invisible element_focusable">Raggiungi il piè di pagina</a>
    </p>

Accadeva in modalità Lettura di Firefox un po' in tutte le pagine interne, non ho guardato il codice e mi son fidato di Firefox. Cancello tutto :) 

ps: forse al posto di un <p> potrebbe essere preferibile un <ul>.
