### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia-it/designer.italia.it#163]
Buongiorno a tutti.
Trovo poco intuitivo ed usabile l'apertura/chiusura dei dropdown
http://italia-it.github.io/ita-bootstrap/dropdown.html

Suggerirei di estendere il link a tutta la riga e soprattutto di commutare il cursore in pointer

.cst-dropdown .heading a {
    font-size: 21px;
    color: #00c5ca;
    **display: block;
    cursor: pointer;**
}

**Comment by gunzip** [comment]
concordo. puoi fare una pull request ?

**Comment by AlessandroVecchi** [comment]
Non so come si fa...

**Comment by gunzip** [comment]
ok le integro io

**Comment by AlessandroVecchi** [comment]
Ho visto che c'è già una richiesta analoga sul progetto ita-bootstrap
https://github.com/italia-it/ita-bootstrap/pull/1

**Comment by gunzip** [comment]
integrata 

http://italia-it.github.io/ita-bootstrap/dropdown.html

**Comment by AlessandroVecchi** [comment]
Manca il width: 100% sul <a>

**Comment by gunzip** [comment]
vero, ricommittata
