### ISSUE TITLE
design.italia.it o designer.italia.it ?

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia-it/designer.italia.it#164]
Ho costatato che http://design.italia.it e http://designer.italia.it non sono allineati.
Qual è quello corretto di riferimento?
Ha senso mantenere 2 siti uguali paralleli? non sarebbe meglio fare un redirect?
Grazie

**Comment by gunzip** [comment]
il sito con l'ultima versione ufficiale delle LG è  http://design.italia.it

designer.italia.it è considerato un sito di pre-release (vengono incorporate le singole modifiche man mano che emergono le problematiche)

in effetti c'è una richiesta di disambiguare i siti che giace li da un po' di tempo: 

#40 

proviamo a darle più priorità
