### ISSUE TITLE
Errore installazione in locale

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia-it/designer.italia.it#165]
Ciao,
Dopo aver lanciato il comando gulp serve mi appare questo errore:

> Error in plugin 'sass'
> Message:
>     styles\main.scss
> Error: File to import not found or unreadable: ../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap
>        Parent style sheet: E:/GitHub/designer.italia.it/styles/main.scss
>         on line 8 of styles/main.scss

Il sito in locale si vede ma senza i css.

> Cannot GET /styles/main.css

Uso Windows 10

**Comment by gunzip** [comment]
il file dovrebbe esser stato scaricato dal comando 'bower install' 
puoi verificare che sia nella directory indicata ? 
(o che almeno esista la directory bower_components)

**Comment by AlessandroVecchi** [comment]
Il messaggio completo è il seguente, avevo dimenticato un pezzo
> Error in plugin 'sass'
> Message:
>     styles\main.scss
> Error: File to import not found or unreadable: ../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap
>        Parent style sheet: E:/GitHub/designer.italia.it/styles/main.scss
>         on line 8 of styles/main.scss
> >> @import "../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap";
>    ^
Se ho capito bene alla linea 8 del file main non interpreta correttamente l'istruzione di @import o non trova quel file.
