### ISSUE TITLE
Disponibilità template HTML/CSS per riutilizzo

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia-it/designer.italia.it#166]
Domanda: se io ad oggi voglio iniziare a sviluppare il sito per un comune da cosa posso partire?
Non ho trovato al momento un template standard html+css da cui partire.
Significa che posso muovermi liberamente, creando un mio html ed un mio css, che avrà quindi le classi ed i nomi che decido, partendo dalle semplici indicazioni delle linee guida?
La mia paura è che se, più avanti, viene standardizzato un codice da seguire tassativamente, il mio lavoro non vada più bene.
Inoltre, quanta libertà ho io di muovermi? Tra il comune di Biella e quello di Matera vedo che, a parte l'impostazione di base, poi sono state fatte scelte diverse di impaginazione ed elementi grafici.

**Comment by adaniello** [comment]
Anche io, data l'impostazione generale del lavoro da voi svolto, ritengo a questo punto utile predisporre dei layout "base"... qualcosa, per intenderci, sulla falsa riga di del "Getting started" sul sito di Bootstrap (penso a http://getbootstrap.com/getting-started/#template e http://getbootstrap.com/getting-started/#examples), classificando magari gli esempi per tipologia di Ente (PA centrale, comune, ...)

**Comment by AlessandroVecchi** [comment]
Salve, sollecito una risposta. La nostra piattaforma web è utilizzata da circa 400 comuni italiani, quindi è importante per noi partire con il piede giusto.

**Comment by agidgov** [comment]
AgID sta sviluppando un framework standard HTML/CSS che verrà rilasciato a settembre 2016 sul sito delle linee guida e a cui seguirà una fase di debug. Contemporaneamente sta predisponendo una roadmap di rilasci tecnici, per giungere entro la fine dell’anno ad una versione più stabile delle LG. Per quanto riguarda tutto ciò che è prodotto prima di tali release, le LG non hanno un effetto retroattivo.

**Comment by AlessandroVecchi** [comment]
Grazie. Mi piacerebbe capire anche quanta libertà ci sia, per gli sviluppatori, all'interno di questo framework. Se da un lato avere siti uniformati semplifica l'approccio da parte del cittadino, per contro rischia di far perdere il know-how di aziende che da anni sviluppano siti per la PA ed hanno maturato soluzioni e conoscenze specifiche.
Avere linee guida è importante, specie per quanto riguarda l'usabilità e l'accessibilità. Per l'organizzazione dei contenuti invece non è detto che la soluzione proposta sia la migliore.
Noi lavorando sia con comuni di poche anime sia con comuni ed enti più grandi constatiamo quotidianamente quante differenze ci sono tra le varie realtà.

**Comment by gunzip** [comment]
partiamo dall'analisi dell'*as-is*. la qualità media dei siti della PA attuali è, a dir poco, scarsa (salvo qualche raro caso di eccellenza); questo nonostante il know-how delle aziende che da anni sviluppano siti per la PA. i perché sono noti (budget limitati, deadline "politiche", scarsa formazione, mancanza di professionalità adeguate, scarso interesse riguardo le tematiche accessibilità e usabilità, considerazione delle esigenze utente pressoché nulla, manutenzione evolutiva inesistente, etc.)

l'esperienza delle LG è l'occasione per metter a fattor comune i casi di eccellenza e l'apporto dei fornitori, con la loro esperienza acquisita sul campo, è determinante. un framework in quest'ottica non deve esser visto come qualcosa di calato dall'alto; tutt'altro. è il meccanismo abilitante per poter collaborare concretamente e fornire alle PA un riferimento.

le "differenze" che citi sono spesso dovute a motivi di ordine esclusivamente politico in un'ottica autoreferenziale; si tratta di scelte calate dall'alto (quelle sì) da personale amministrativo che non sempre possiede il know-how necessario per poter decidere su argomenti tecnici. le LG vogliono esser uno strumento tramite il quale chi sviluppa siti e servizi può "negoziare" le proprie scelte declinandole nell'ottica user-centered.

**Comment by webgrafia** [comment]
Concordo con @gunzip , le LG offrono uno strumento importante a chi lavora per le PA per poter "costringere" gli amministratori a seguire una strada condivisa e uniforme.
Credo che saranno un fattore determinante per accelerare i processi decisionali, e evitare scelte di design legate al  gusto estetico dell'amministratore di turno.
A mio avviso il know how pregresso acquisito dai fornitori non potrà che esserne valorizzato, e si potrà concentrare sulle specificità dei singoli progetti

**Comment by AlessandroVecchi** [comment]
Da questo punto di vista sono d'accordissimo.

**Comment by GianniSinni** [comment]
@gunzip descrive perfettamente lo spirito delle LG.

**Comment by giannigio1981** [comment]
Sarebbe utile predisporre anche un tema base per Drupal per esempio, dato che è il più diffuso tra i CMS della PA.

**Comment by AlessandroVecchi** [comment]
Non vorrei fare il polemico ma settembre è passato...

**Comment by dgardina** [comment]
@AlessandroVecchi avevi dato un'occhiata a questo: https://italia-it.github.io/ita-web-toolkit/index.html ?

Devo ammettere, purtroppo, la mia ignoranza nell'utilizzo di certi strumenti, però sto cercando di applicarmi e capire come abbiano fatto certi enti a mettere già in pratica le indicazioni delle linee guida, dato che più o meno dappertutto c'è scritto che sono "alpha" (da un pezzo) e di attendere il rilascio di una versione stabile.. In particolare mi riferisco al Comune di Matera, dato che anche noi vorremmo utilizzare queste linee guida su diversi siti realizzati con CMS Joomla! ma non riesco quasi nemmeno a capire come partire..

**Comment by gunzip** [comment]
@dgardina la prossima settimana possiamo verrà data qualche spiegazione in merito al tookit.

> come abbiano fatto certi enti a mettere già in pratica le indicazioni delle linee guida, dato che più o meno dappertutto c'è scritto che sono "alpha"

le amministrazioni che hanno già messo in pratica le indicazioni, in uno spirito collaborativo, si sono fatte carico del "rischio" dei cambiamenti che potrebbero esserci nelle LG durante il percorso verso la versione più 'stabile'. tali cambiamenti, del resto, scaturiranno anche dai feedback raccolti grazie al loro contributo (proprio per questo sono riferiti come 'siti pilota'). va da sé che partendo da una situazione di 'avanguardia' l'eventuale effort richiesto per adeguarsi in futuro sarà del tutto sostenibile (es. cambiare un label o un elemento grafico)

> sono "alpha" (da un pezzo)

in linea con le esperienze internazionali (vedi [UK](https://www.gov.uk/service-manual/user-centred-design/resources/elements/index.html) e [USA](https://standards.usa.gov/about-our-work/component-maturity-scale/) perennemente in 'draft'), è per la natura dinamica di questo tipo di progetti.
stiamo effettuando dei test sul modello proposto a luglio nonché recependo contributi dai vari attori coinvolti (ministeri, comuni e loro fornitori).

> attendere il rilascio di una versione stabile

contiamo di arrivare a una 'beta' entro fine anno ovvero incorporare:

  - indicazioni più specifiche (e stabili) per l'architettura dell'informazione
  - indicazioni definitive su header e menu

le indicazioni di carattere generale (es.quelle sul content design, usabilità, accessibilità) dovrebbero 
(nel caso dell'accessibilità, devono) essere applicate da subito.

> mi riferisco al Comune di Matera, dato che anche noi vorremmo utilizzare queste linee guida su diversi siti realizzati con CMS Joomla! ma non riesco quasi nemmeno a capire come partire.

http://www.agid.gov.it/cad/art-69-riuso-soluzioni-standard-aperti

**Comment by gunzip** [comment]
nel mentre, abbiamo predisposto delle FAQ: https://github.com/italia-it/ita-web-toolkit/wiki

**Comment by gunzip** [comment]
chiudo la issue. per tutto ciò che riguarda più da vicino i template (issue comprese) verrà utilizzato il repository relativo: https://github.com/italia-it/ita-web-toolkit
