### ISSUE TITLE
CSS e validazione

### ISSUE THREAD

**Issue by LivioMo** [italia-it/designer.italia.it#167]
Per definizione, i fogli di stile di Bootstrap non sono validabili ed usano CSS non standard. Per loro va bene così per vari motivi. Però per un sito della PA questo potrebbe essere un problema, e personalmente non concordo con le conclusioni del gruppo di sviluppo di Bootstrap su questo argomento, troppi errori di parsing e non di semplice sintassi errata. 
Come può essere risolto questo problema? Ho visto che il problema è già stato affrontato e chiuso, ma ritengo sia un errore:  i linguaggi di marcatura (compreso CSS) devono essere utilizzati in modo conforme alle specifiche previste nelle relative grammatiche formali di riferimento.

rif: 
http://getbootstrap.com/getting-started/#support-validators

"In generale un linguaggio di markup è un insieme di regole che descrivono i meccanismi di rappresentazione (strutturali, semantici o presentazionali) di un testo che, utilizzando convenzioni standardizzate, sono utilizzabili su più supporti. La tecnica di formattazione per mezzo di marcatori (o espressioni codificate) richiede quindi una serie di convenzioni, ovvero appunto di un linguaggio a marcatori di documenti"

https://it.wikipedia.org/wiki/Linguaggio_di_markup

**Comment by gunzip** [comment]
chiudo questa issue. è possibile commentare anche issue chiuse che all'occorrenza verranno riaperte, nel caso specifico: #134 dove invito eventualmente a proseguire la discussione possibilmente elaborando l'asserto "potrebbe essere un problema"

personalmente non vedo nessun problema nell'utilizzo di un CSS che non valida. vedo invece un problema di tempi e costi nel grantire il contrario (a che pro ?)

**Comment by LivioMo** [comment]
ok, aggiunto a #134
