### ISSUE TITLE
installazione in locale funzionante per test

### ISSUE THREAD

**Issue by Davolraf** [italia-it/designer.italia.it#168]
Sarebbe, possibile avere istruzioni su come e cosa scaricare per avere un'installazione completa e funzionante del template?

grazie

**Comment by gunzip** [comment]
@Davolraf  le istruzioni sono visibili qui 

https://github.com/italia-it/ita-bootstrap

tuttavia stiamo ristrutturando totalmente i template per renderli più utili
(novità a settembre 2016)
