### ISSUE TITLE
burger menu: da correggere per accessibilità

### ISSUE THREAD

**Issue by LivioMo** [italia-it/designer.italia.it#169]
Siccome la tematica JS fa venire il mal di pancia, segnalo che il burger menu dei siti campione governo.it e comune.venezia.it (ho guardato solo questi due) non è a norma, poiché c'è un'ancora che contiene un attributo href valido, ma non viene fornito il necessario contenuto del link, che non può essere vuoto.

a href**="#"** class="toggle-menu menu-left push-body jPushMenuBtn"
div
div
...
a

ps: nel corpo delle pagine vengono spesso usate ancore di questo tipo. non sono ammesse dalla normativa corrente.

**Comment by arbizzani** [comment]
Chi l'ha detto?

**Comment by LivioMo** [comment]
LOL :) questa la trovi facilmente, dai almeno leggila 'sta normativa. È scritta in un linguaggio bizantino, ma si può.

http://www.agid.gov.it/dm-8-luglio-2005-allegato-A

**Comment by arbizzani** [comment]
Mi son fermato a 7 crisi epilettiche.

Ma davvero lì dentro c'è scritto che è vietato usare il tag <a> con la
proprietà href vuota?

Interessante il mondo fuori da qui.

**Comment by LivioMo** [comment]
No, non puoi usare < a > se non c'è il relativo testo del link nel tag. Nel caso in questione, c'è un attributo href (il cancelletto) ma non c'è il testo. È un link vuoto. Da un punto di vista tecnologia assistiva, lo screen reader ti annuncia un link, ma senza alcuna indicazione su dove va il link. Così tu senti "collegamento" e stop, e ti si accende il punto di domanda in testa. Dove andrò?

**Comment by arbizzani** [comment]
La curiositá è femmina, ma io per scoprire dova porta lo cliccherei subito.

A parte l'ironia, l'unico modo per aiutare un assistente è quello di usare
il tag <a>.

Meglio che uno span o div con del js, non credi?

Comunque è vero che il # in href ha effetti spesso indesiderati su browser
differenti.

**Comment by webnicola** [comment]
Che ne dite se invece di un link visto che è un bottone per aprire e chiudere il menu di navigazione usiamo il tag button, tipo:

`<button aria-label="Navigation menu" type="button" class="toggle-menu menu-left push-body jPushMenuBtn"`

Così dovrebbe essere più accessible... ?!?

p.s.:  si potrebbe usare anche un checkbox, questo potrebbe aprire e chiudere il menu di navigazione senza js ;)

**Comment by LivioMo** [comment]
Personalmente non so perché sia stata usata quella soluzione, non so come funziona quindi non ho idea se si possa sostituire l'elemento a con button. Sicuramente aria andrebbe aggiunto, e forse basterebbe invece di lasciare il tag a vuoto aggiungerci il testo Menu... come fra l'altro indicano le linee guida. Comunque, è una buona pratica per le liste di navigazione usare ul e li e non div, già che si interviene sul menu forse sarebbe il caso di approfittarne e farlo diventare come si deve.

**Comment by gunzip** [comment]
l'implementazione offcanvas+menu ad albero su cui vorremo convergere è quella visibile su http://www.spid.gov.it/ (dovrebbe funzionare anche senza js attivo). il problema segnalato delle anchor usate come bottoni è corretto anche perché gli screen reader non ricevono, nel caso specifico, nessun feedback sull'espasione del sotto menu on-click.
