### ISSUE TITLE
I menù di secondo livello (dropdown) non funzionano con il burger menù

### ISSUE THREAD

**Issue by met67** [italia-it/designer.italia.it#170]
Ecco come riprodurre il comportamento:

1. Aprite il sito http://design.italia.it/
2. Ridimensionate la finestra del browser sotto i 768 pixel per far apparire il burger
3. Cliccate sul burger -> si apre il menù
4. Cliccare sulla freccia a destra di "Accessibilità", per "Espandere il menu Accessibilità"
5. BINGO: il menù si chiude, la pagina non cambia e l'icona del burger resta una X

**Comment by gunzip** [comment]
grazie per la segnalazione, ora dovrebbe andare
