### ISSUE TITLE
icone accesso ai social e indicazioni contenuti minimi

### ISSUE THREAD

**Issue by mbolzan** [italia-it/designer.italia.it#171]
Salve, 
volevo fare una considerazione partendo da questa domanda : perché inserire nelle linee guida la presenza delle icone ai social in una parte così importante della pagina?

sono icone che spesso spariscono con l'header compattato dopo lo scroll, non sono visibili nei layout responsive inferiori, sono link esterni la cui apertura in altra scheda è affidata (giustamente) al visitatore, spesso e volentieri i canali social delle PA sono mere liste di news duplicati del sito.

non sarebbe il caso di incoraggiare a lasciarle solo nel footer e, che ne so, utilizzare quello spazio per migliori e specifiche call-to-action?

**Comment by gunzip** [comment]
per alcune PA i social sono un punto di contatto. tuttavia le considerazioni in merito alla visibilità delle icone sono tutte valide, le giro a chi se ne occupa qui e proviamo a raccogliere qualche ulteriore feedback dai cittadini.

**Comment by giancarlobuzzanca** [comment]
Buongiorno
credo che le indicazioni contenute nella sezione Header, con la specifica del "SI PUÒ" siano corrette sia per funzionalità sia per il ruolo che, per l'appunto, la PA intende assegnare all'ambito social. Che talune presenze siano inutili e/o mal gestite è altra questione

**Comment by giovanisp** [comment]
sarebbe il caso di considerare e/o cercare di essere il più coerente possibile con quanto già pubblicato nelle Linee Guida per i Siti Web della PA, quando indica alcuni posti precisi dove inserire alcune informazioni "minime" dei siti istituzionali (a meno che si intenda proprio sostituire e rendere obsolete queste indicazioni). Ad esempio:

"Le informazioni relative all'Ufficio relazioni con il pubblico (URP), reso obbligatorio dalla Legge n. 150/2000, anche se presenti all'interno dell'organigramma devono essere direttamente raggiungibili dalla testata o dalla home page indirizzate dall'etichetta "URP" o "Ufficio relazioni con il pubblico"."

"Inoltre, il nominativo del responsabile del procedimento di pubblicazione, completo di indirizzo e-mail, deve essere - ove possibile - raggiungibile da un'area informativa a piè di pagina (footer), presente in tutte le pagine (www.nomesito.gov.it/responsabile) o, alternativamente, in un'apposita sezione del sito web, accessibile dalla homepage e da tutte le pagine."

"Il servizio di consultazione dell'elenco dei procedimenti e la modulistica disponibile on line dovranno essere raggiungibili dalla home page del sito istituzionale, in posizione ben evidente, e correlata alle sezioni informative sui procedimenti ed a quella dei servizi on line."

"I siti tematici pubblici debbono riportare nel piè di pagina una sezione informativa indirizzata dall'etichetta "Informazioni sul sito""

Ecc... Ecc...

**Comment by gunzip** [comment]
per le indicazioni sui contenuti minimi (non affontati nelle LG di design) fanno testo le LG2011 che tuttavia andrebbero aggiornate in toto, considerando il nuovo quadro normativo (CAD, FOIA, ...) e altre novità (SPID, pagoPA, DCAT, CPSV, ...). non è escluso estendere il contesto delle LG di design a tale scopo.

per quanto riguarda i contatti (e quindi l'URP) trovano la loro collocazione naturale nel footer, un'area con collocazione prevedibile, immediatamente raggiungibile da chi naviga da tastiera e senza i limiti di spazio verticale che impone l'header. ciò non impedisce di proporli anche in altre posizioni come ad esempio visibile sul sito pilota  http://www.comune.biella.it/ in coerenza con quanto riportato nelle LG2011

**Comment by giancarlobuzzanca** [comment]
Condivido appieno Giovani Spagnolo. Ho la sensazione che  quanto correttamente elaborato (cito anche, in piccolo,  il caso del mio ministero con le "Linee guida per i siti web culturali pubblici")  non sia stato tenuto da conto. Non si tratta di primeggiare ma solo di stendere un tappeto omogeneo e coerente con le prassi e norme che si sono  succedute.
Perdonate, comunque, queste considerazioni sostanzialmente off-topic ...

**Comment by gunzip** [comment]
considerando che la presentazione delle icone social è indicata come facoltativa (nella testata), è comunque opportuno indicare dove devono comparire qualora presenti. starà alla singola amministrazione deciderne l'importanza. per le indicazioni sui contenuti minimi stiamo riscrivendo la parte della normativa per coprire le sezioni delle LG2011 non ancora aggiornate.
