### ISSUE TITLE
Macchina a stati (wizard)

### ISSUE THREAD

**Issue by marcoalbarelli** [italia-it/designer.italia.it#172]
Salve a tutti
Grossomodo la domanda ricalca il #19 

Con un cliente stiamo lavorando a una soluzione per offrire servizi al cittadino. 
Stiamo organizzando la compilazione dei form sotto forma di macchine a stati.
Abbiamo cercato nelle LG ma non abbiamo trovato niente di specifico per skinnarli, quindi per il momento andiamo avanti con una soluzione bootstrap che abbiamo già usato in altri contesti.

Se come mi pare non c'è niente di specifico sarei lieto di fare una PR dato che il caso d'uso credo possa essere di interesse generale

**Comment by gunzip** [comment]
puoi allegare un'immagine che esemplifichi il caso d'uso ? stiamo ristrutturando i template (CSS/HTML) vedi #166, quindi una PR su ita-bootstrap risulterebbe poco utile a oggi

**Comment by marcoalbarelli** [comment]
il caso d'uso è quello solito di un wizard:

![image](https://cloud.githubusercontent.com/assets/789508/17616881/2231c1da-6077-11e6-8265-3313742a63ff.png)

tolto che ovviamente nel nostro caso gli elementi saranno declinati in un'ottica di servizi per il cittadino, seguendo un flusso di compilazione diverso per ogni servizio offerto.
Stiamo pensando a un look and feel come quello in allegato

Dal #166 non ho ben capito lo stato corrente. ita-bootstrap è in fase di deprecazione?
Noi stiamo per deliverare a brevissimo, quindi ormai proseguiamo coi componenti bootstrap attuali, ma farebbe comodo sapere se dobbiamo già allocare un refactoring dell'interfaccia

**Comment by gunzip** [comment]
sì, è in fase di deprecazione (il che non significa che non può essere utilizzato, ma che vorremmo mettere a disposizione qualcosa che sia più utile e strutturato). considerando che seguirà un periodo di debug (auspicabilmente partecipato) ed evoluzione, nel mentre è sufficiente seguire quanto contenuto nei *testi* delle LG utilizzando una qualsiasi implementazione.

**Comment by gunzip** [comment]
convoglierei l'effort su 

https://github.com/italia-it/ita-web-toolkit

un esempio di "form multistep" è previsto nella roadmap:

https://italia-it.github.io/ita-web-toolkit/docs/roadmap.html
