### ISSUE TITLE
tag h4 mancante su design.italia.it

### ISSUE THREAD

**Issue by rdhat801** [italia-it/designer.italia.it#173]
Ciao :)
Stavo leggendo la sezione [http://design.italia.it/linee-guida/il-progetto/](Il progetto) e mi sono accorto che l'ultimo paragrafo ha il sottotitolo senza tag h4, diversamene dagli altri.

Vedi pic
![indicazioni_generali](https://cloud.githubusercontent.com/assets/21067294/17714036/37cbd898-63fe-11e6-8bd1-04eaefe475f1.png)

I miei complimenti, è un progetto davvero interessante, e... posso dirlo? Finalmente, ci voleva proprio un progetto così!

**Comment by gunzip** [comment]
grazie, ho effettuato il merge
