### ISSUE TITLE
Chiarimento "rapporto di contrasto minimo tra testo e sfondo di 4,5:1"

### ISSUE THREAD

**Issue by dellamina** [italia-it/designer.italia.it#175]
Alla pagina https://github.com/italia-it/designer.italia.it/blob/master/pages/colori.md viene scritto "rapporto di contrasto minimo tra testo e sfondo di 4,5:1", volevo chiedere un chiarimento in quanto la versione personalizzata di bootstrap resa disponibile già non rispetta questo principio perchè esempio le varie classi "danger" hanno testo #ffffff e background #d9534f il che genera un rapporto di contrasto 4:1, "warning" 1.9:1 e "info" 2.1:1.
Dovendo poi anche andare a personalizzare la parte cromatica per i vari enti mi risulta difficile se non impossibile utilzzare un ampia gamma di colori se anche per elementi come i bottoni e gli alert(di bootstrap) bisogna rispettare questo vincolo.
In sostanza questo principio deve essere rispettato per tutti gli elementi dell'interfaccia o principalmente per il corpo garantendo maggiore libertà su elementi come quelli citati prima?

**Comment by AlessandroVecchi** [comment]
Io ti sconsiglio di evitare le classi colori predefinite di bootstrap per i progetti inerenti la PA perché non rispettano i contrasti colore (anche nella versione 4). Puoi creare delle classi tue oppure sovrascrivi i colori predefiniti nel tuo css.
Se usi un preprocessore CSS puoi customizzare gli stili http://getbootstrap.com/customize/

**Comment by dellamina** [comment]
Capisco che sia un operazione molto semplice (che già faccio per le personalizzazioni che ci vengono richieste sui colori primari) ma vista l'attenzione per i colori presente nelle linee guide riguardanti ai form dove le classi colori relativamente agli alert sono state modificate(presumo siano state modificate) per rispettare il contrasto colore, mi sarei aspettato queste modifiche in tutto bootstrap.
Per cambiarle io ci metto davvero poco però avrei preferito evitare modifiche così da essere sicuro di rispettare i principi che stanno alla base di questo progetto.

**Comment by AlessandroVecchi** [comment]
A Settembre dovrebbero essere rilasciati i nuovi template #166

**Comment by gunzip** [comment]
esatto, il rapporto di contrasto va rispettato sempre e comunque (valida anche l'osservazione sui template).
