### ISSUE TITLE
Utilizzo Carousel

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia-it/designer.italia.it#177]
Ho un dubbio su un'affermazione contenuta nelle linee guida:

> **Organizzare la sezione notizie**
> 
> Nella disposizione e organizzazione delle notizie in home page, è sconsigliabile l'utilizzo dello slider (o carousel) per la pubblicazione dei contenuti.
> 
> Spesso infatti lo slider viene ignorato e gli utenti non riescono ad avere accesso immediato alle notizie più importanti. Lo slider inoltre potrebbe non essere fruibile per chi naviga un sito mediante tastiera o screen reader.

Questa dichiarazione è fatta sulla base di dati statistici precisi? A me suona un po' strana, non ho mai riscontrato un limite all'utilizzo di carousel, anzi sono molto richiesti come funzionalità.

Mi sembra comunque di capire che è sconsigliato ma non proibito, può essere usato se lo script rispetta determinati requisiti di accessibilità, è così?
Una soluzione che abbiamo già usato su nostri progetti è quella di avere un carousel con un'immagine rappresentativa ed il titolo della news o appuntamento, e a seguire le stesse news sono ripetute in forma di elenco con breve riassunto. In questo modo anche se viene ignorato lo slider l'informazione è ulteriormente veicolata. Può essere una soluzione compatibile con le linee guida?

**Comment by gunzip** [comment]
esistono dei dati statistici a riguardo, oltre che un'ampia letteratura, riporto qualche riferimento:

- https://www.nngroup.com/articles/auto-forwarding/
- https://thedigest.org/articles/carousels-of-comprimise
- https://erikrunyon.com/2013/07/carousel-interaction-stats/
- http://www.widerfunnel.com/rotating-offers-the-scourge-of-home-page-design/

che siano molto richiesti dai clienti (le PA) non ho dubbi, che siano invece efficaci per i cittadini è un altro discorso (ovvero che venga rispettato il principio 'user centered').

il caso specifico riportato, ovvero permettere in ogni caso la fruzione dei contenuti anche fuori dal carousel, abbinato ad alcuni accorgimenti per rendere accessibile il js è compliant alle LG; tuttavia rende il carousel "superfluo" e, laddove presente un'animazione *automatica*, di difficile fruizione.

**Comment by adaniello** [comment]
@gunzip 

Una mera considerazione "personale": non concordo sull'idea "tuttavia rende il carousel "superfluo" e, laddove presente un'animazione automatica, di difficile fruizione" in quanto il carousel è una interfaccia pensata per migliorare la fruizione di contenuti di interesse cui l'utente "medio" è ormai ampiamente abituato soprattutto in virtù del fatto che la medesima soluzione viene ampiamente utilizzata dai dispositivi mobile (a titolo di esempio, una galleria di immagini). Aggiungerei che quando un carousel viene utilizzato per la "promozione" di un contenuto (caso tipico di quello in Bootstrap), allora a mio avviso è scontato l'effetto "banner" (cioè che ad esempio il contenuto nella prima slide è prevalente sui successivi...), ma in effetti questo è proprio lo scopo per cui avrei utilizzato questo componente, cioè "promuovere/mettere in evidenza" un contenuto e rimandare ad esso.

In generale, anche gli interessanti riferimenti da te suggeriti o sono articoli "vecchi" (2011 e 2013, vecchi per il passo che ci impone la tecnologia) o sono riferiti ad applicazioni specifiche di tale interfaccia in casi particolari di layout.

**Comment by gunzip** [comment]
le gallerie di immagini sono un discorso a parte (vengono utilizzate anche su governo.it / fp senza animazioni automatiche). quel che si sconsiglia è l'utilizzo di animazioni *automatiche* per la presentazione di *contenuti testuali che sono considerati prioritari*.

i motivi sono quelli riportati nei diversi articoli (per citarne alcuni: la scarsa interazione utente rilevata, [la difficoltà di leggere per intero i testi che spariscono dopo un certo lasso di tempo](http://shouldiuseacarousel.com/), la complessità nell'implementare una versione efficace su uno screen reader). i contenuti possono in sostanza esser promossi anche tramite presentazioni statiche che non soffrono di tali problematiche (problematiche che persistono al di la dell'avanzare delle tecnologie nel corso degli anni).

l'esperienza sembrerebbe suggerire che l'utilizzo dei carousel, più che per 'migliorare la fruizione di contenuti di interesse' (che magari finiscono nascosti nelle slide successive alla prima) è più spesso funzionale a tranquillizzare il cliente che vuol contenere in home page *tutti* i contenuti che lo autopromuovono, spesso senza alcuna logica di prioritarizzazione.

**Comment by AlessandroVecchi** [comment]
il difficile è convincere i clienti :)

**Comment by adaniello** [comment]
Beh, il mio pensiero "personale" è legato, lo ripeto, all'affermazione "di difficile fruizione" (a cui aggiungerei l'altra "scarsa interazione utente rilevata") che si basa su articoli e statistiche vecchie (le più recenti risalgono al 2013, così come le altre fonti assai diffuse sul tema, come ad esempio http://shouldiuseacarousel.com: ritengo che le cose siano cambiate.

Ovviamente, se poi si parla di accessibilità ed usabilità, allora c'è da dire che come fonte sarebbe sufficiente https://www.w3.org/WAI/tutorials/carousels/ (i cui contenuti sono del 2014) i cui punti, però, possono tutti essere facilmente superati dal buon senso e da qualche modifica fatta dallo sviluppatore (considerando che poi già due dei quattro punti di sintesi sarebbero gestibili mediante le opzioni native del carousel in Bootstrap).

Da questo punto di vista, questa discussione mi ricorda un'altra issue in cui parlavate di "burger menu", ma per quella le posizioni mi sembravano rovesciate. 😆

**Comment by gunzip** [comment]
credo che sia una buona occasione per effettuare dei test con gli utenti. tramite gli strumenti di analytic più popolari è semplice rilevare ad esempio il numero dei click sui controlli del carousel o il mouseover su una slide. inoltre si potrebbero effettuare dei [test di usabilità](http://www.funzionepubblica.gov.it/glu) con task che coinvolgono i contenuti presenti nel carousel per valutarne l'efficacia (i risultati potrebbero esser sufficienti a convincere il cliente).
