### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia-it/designer.italia.it#178]
Ho notato nelle LG l'assenza di indicazioni sulle breadcrumbs (o briciole).
Nei vari siti demo infatti non c'è una gestione univoca e su governo.it non ci sono neppure.
C'è qualche motivazione? io direi che sono elemento imprescindibile per l'usabilità del sito.

Bootstrap4 propone 2 soluzione: tramite classica lista oppure sfruttando il tag `<nav>`.
A vostro parere quale è semanticamente più corretta?

**Comment by Strae** [comment]
Mah, sono entrambi corretti, concettualmente io sarei più per la classica lista in quanto le breadcrumbs non le vedo come un "menu" ma è una mia opinione personale.

Concordo sul fatto che sono molto importanti per l'usabilità del sito.

**Comment by francescozaia** [comment]
:+1: per liste semplici, anche [gov.uk](https://www.gov.uk/social-security-child-support-tribunal) usa `li`.

**Comment by engbmsdev** [comment]
L'esempio del [w3c](https://www.w3.org/WAI/tutorials/menus/multiple-ways/) utilizza il `<nav>` con i vari `<a>` all'interno.
Anche il w3c  forse vede le briciole come un'informazione da leggere tutta insieme piuttosto che un elenco di link (menu)

**Comment by gunzip** [comment]
concordo sul fatto che sia un elemento imprescindibile. 

al momento non ci sono indicazioni a riguardo, si potrebbe considerare di inserirle nei testi (infoarchitettura ?) o direttamente nei template quando saranno disponibili.

opionione personale: ok l'utilizzo di `<nav>` con o senza lista

```
<nav aria-label="..." role="navigation">
  <ul>
    <li><a href="...">Home</a></li>
    <li><a href="...">...</a></li>
  </ul>
</nav>
```
