### ISSUE TITLE
Elenchi e ricerche di servizi

### ISSUE THREAD

**Issue by lb16330** [italia-it/designer.italia.it#180]
Tutte le PA presentano in modo variegato un elenco di servizi:
Occorre individuare una buona pratica di riferimento per mostrare/ filtrare elenchi di  servizi.
con particolare attenzione all'omoneizzazione delle categorie e delle dimensioni delle categorie stesse.
Esempi: 
- 1.  http://www.spid.gov.it/cerca 
- 2.  http://servizi.regione.fvg.it/portale/
- 3.  https://www.inps.it/portale/default.aspx?sID=%3b0%3b11513%3b&lastMenu=11513&iMenu=2&p4=2
- 4. http://servizi.toscana.it
- 5. https://www.comune.roma.it/pcr/it/elenco_servizi_online.page

hanno approcci molto diversi.

Come primo contributo si suggerisce di taggare (per poi poter ricercare) ogni servizio per 
- dimensione territoriale [Nazionale, interregionale ,  Regionale,  intercomunale,  Comunale] taggando in modo codificato unico (si faccia riferimaneto a ipa o istat)
- area funzionale (vedi esempio fvg o prese4ntazione catalogo servizi)
  -tipologia utente:(Extra eu, Eu,it)  X cittadino, professionista , impresa.
  -evento della vita di riferimento 
- altro

Qundi indivisare una unica ux di riferimento da rendere comune.

**Comment by gunzip** [comment]
per quanto riguarda la classificazione dei servizi le indicazioni sui metadati saranno quelle riportate nel
[CPSV-AP_IT](http://www.dati.gov.it/consultazione/CPSV-AP_IT) dopdiché si può pensare di suggerire delle UI di ricerca (eventualmente basate su soluzioni esistenti particolarmente virtuose)

**Comment by mirkobattisti** [comment]
Per l'interfaccia, credo che uno degli esempi più brillanti sia il portale dei servizi del governo britannico: https://www.gov.uk/
I servizi sono raggiungibili navigando (_browse_) o dal motore di ricerca (_search_). 
In modalità _browse_, i servizi sono organizzati per fabbisogni, hanno posto il vincolo di avere due livelli prima di raggiungere la scheda relativa al servizio, e la navigazione viene effettuata con il paradigma delle colonne di miller: https://www.gov.uk/browse/tax/inheritance-tax
Hanno definito anche un manuale per la definizione dei servizi (https://www.gov.uk/service-manual).
hanno anche un blog dove é tracciato il processo che li ha portati a sviluppare quella soluzione, e dove raccontano le evoluzioni (https://gds.blog.gov.uk/).

**Comment by umbros** [comment]
Come detto da gunzip la linea sarà tracciata in italia dal CPSV-AP_IT e dal futuro portale dei servizi.
Il portale di ricerca servizi SPID sarà basato su quella base dati.

**Comment by mirkobattisti** [comment]
@umbros forse mi sono espresso male. Il manuale per la definizione dei servizi che indico é orientato a come i funzionari possano identificare i servizi per riportarli nella piattaforma, quindi non ha a che vedere con la definizione formale e tecnica del servizio stesso, che non viene messa in discussione. La mia intenzione era di dare un contributo sulla modalità di presentazione, che è cosa ben diversa dalla base dati.

**Comment by lb16330** [comment]
Salve, 
scusate ma CPSV-AP_IT permette di _"Attraverso il profilo si possono descrivere tutti i servizi forniti dalle pubbliche amministrazioni ai cittadini, professionisti e imprese, siano essi disponibili online o fisicamente, attivi o in fase di sviluppo."_

quindi dice bene @mirkobattisti  parlando di funzionari (immagino della pubblica amministrazione).
La prospettiva deve essere girata: si parla dei cittadini, degli utenti che ricercano (e non descrivono) il servizio e non degli addetti ai lavori.
Le categorie date dai funzionari per descrivere il servizio, sono "statiche" (o almeno non cambiano nel tempo) non sono proprie del linguaggio comune.

E poi gli utenti non sono tutti uguali.
Io immagino un percorso guidato (colonne di miller o meno) le quale l'utente che vuole aprire un bar scrive "aprire un bar" e poi (se vuole) indica anche il comune.
al pari la possibilità di trovare "iscrizione scuola" (evento comune a molti utenti genitori) e trovare proposti (suggeriti) i servizi che sono più utili, un suggerimento opertaibo e  oltre che la lista dei servizi che derivano da una ricerca su un db di classifiche.

Esempio pratico:

**Comment by umbros** [comment]
Prima della presentation, della ux, della facilità di ricerca, c'è la base dati e la base dati è CPSV-AP_IT. Poi si può parlare delle modalità di ricerca, di guida dell'utente, di segmentazioni della ricerca. Una base dati può essere letta ed elaborata in base all'utilizzo che se ne deve fare. Luca quello che dici è giusto ma è un passo successivo la raccolta delle informazioni e della normalizzazione... Oggi l'approccio seguito, ad esempio su www.spid.gov.it/cerca, è quello di, a partire dall'amministrazione, di mostrare i servizi presenti proprio perchè si è in una fase di startup, di adesione al sistema di autenticazione, ovvio che quando tutte le PA avranno i propri servizi online interfacciati a SPID non sarà più necessario mostrare quali servizi della x PA sono disponibili con il sistema di autenticazione, ma si entrerà in un ottica di Portale Servizi. We're working on it!

**Comment by mirkobattisti** [comment]
@umbros lungi da me il voler entrare in polemica, ma l'inizio di questa discussione dice "individuare una buona pratica di riferimento per mostrare/ filtrare elenchi di servizi."
Se la cosa va posticipata dopo aver consolidato la base dati lo posso (in parte) capire. Ma credo sia interessante considerare le strade percorribili per offrire agli utenti un modo semplice di trovare ed accedere ai servizi. Questo deve tener conto della struttura della base dati, ma non può esserne una diretta conseguenza, altrimenti rischiamo di proporre interfacce potentissime e completissime, ma totalmente inutilizzabili dai cittadini.
L'esempio www.spid.gov.it/cerca è certamente interessante, ma segue la logica di esposizione del database. Sotto tipologia vedo "autorità di bacino", "autorità portuali", "altri enti locali", ... : non mi pare ideale per un utente trovarsi davanti a quel tipo di scelta: il cittadino non deve essere costretto a conoscere come funziona la pubblica amministrazione per accedere ai servizi che offre.

**Comment by lb16330** [comment]
riprendendo proprio le linee di questo progetto e cercando si applicarle ad un menù di ricerca trovo quello che segue.
nessuna polemica da parte mia, ma una invito all'attenzione verso l'utente/concittadino.
Rifuardo i tempi non concordo: vero che si può proccedere in modo seriale, ma anche vero che occorre fare bene  per design e non per stati di avanzamento.

> 
> 
> L'ordine delle voci segue una logica di importanza: prima quelle tematiche orientate al pubblico principale, poi quelle più istituzionali.
> Aree tematiche
> 
> L’accesso per tema non è mutuamente esclusivo rispetto a un accesso per tipologia organizzativa o istituzionale. Esse costituiscono in effetti due modalità complementari di accesso a contenuti e servizi. Ciò significa che se alcuni contenuti sono specifici e si trovano solo in un’area, molti contenuti saranno comuni: ciò che cambia è la modalità, la logica attraverso cui vengono recuperati. Così, ad esempio, selezionando il tema "casa" l’utente potrà visualizzare anche i riferimenti e i contatti degli uffici collegati, le notizie o eventi su questo tema ecc.
> 
> Poiché ogni area tematica copre uno spettro ampio di contenuti e servizi, è utile strutturare ogni area in sottocategorie. Una stessa sottocategoria può comparire in più di un’area tematica.
> 
> Per la scelta delle etichette delle categorie e sottocategorie è utile:
> 
>     fare in modo che le parole-chiave compaiano per prime
>     evitare un linguaggio burocratico
>     verificare quali termini gli utenti cercano nel sito e integrarle nel titolo
>     effettuare test con utenti reali
> 
> Possibile struttura interna del menu tematico
> 
> (in ordine alfabetico)
> 
>     Ambiente Avere un animale, Fare la raccolta differenziata, Fare sport, Forme di mobilità alternativa, Vivere la natura
>     Casa Acquistare casa, Affittare/prendere in affitto casa, Cambiare casa, Costruire ristrutturare casa
>     Certificati e documenti Anagrafico e di stato civile, Edilizio e urbanistico
>     Cultura e tempo libero Biblioteche e archivio storico, Eventi culturali, Fare sport
>     Denunce Denunce civili e penali, Pagare o ricorrere contro sanzioni
>     Elezioni Informazioni sulle consultazioni elettorali
>     Famiglia Adozione, Aiuto e sostegno familiare, Associazioni che si occupano di famiglia, Matrimonio, Avere un figlio, Adozione, Prima infanzia
>     Imprese Aprire un'attività, Cessare un'attività
>     Innovazione e smart city SPID, Pagamenti elettronici, Anagrafe unica popolazione residente
>     Lavoro Cercare lavoro, Svolgere commercio fisso o ambulante
>     Salute Assistenza medica, Assistenza sociale
>     Studio Scuole elementari e d'infanzia
>     Tasse Imposta sugli immobili, Tariffe, imposte e canoni comunali
>     Trasporti Forme di mobilità alternativa, Utilizzo dell'automobile, Utilizzo di motocicli
>     Uffici comunali Informazioni di contatto, orari di apertura al pubblico, competenze e altro ancora relativi agli uffici comunali
>     Volontariato Cittadinanza attiva, Fare il volontario, Organizzare un evento, Servizio civile
> 
> Classificazione per profilo
> 
> La classificazione dei contenuti per profilo utente permette all’utente un accesso mirato ai contenuti e servizi sulla base di specifici tipologie di utenti. Le ricerche sul campo e l’esperienza sconsigliano di usare la classificazione per profilo come unico criterio di navigazione per l'accesso ai contenuti, in quanto non tutti gli utenti potrebbero facilmente riconoscersi in un profilo.
> 
> [modalità polemica OFF]

**Comment by mirkobattisti** [comment]
Qualche tempo fa abbiamo creato un prototipo per l'accesso ai servizi del Servizio scuola della Provincia autonoma di Trento. Replica il funzionamento di gov.uk, e riprende il concetto espresso da @lb16330 (menu tematico). Lo potete vedere qui:
http://vivoscuola.opencontent.it/

La sezione "servizi e informazioni" rappresenta il menù tematico, con quelli che abbiamo chiamato "argomenti" (le cui descrizioni sono esse stesse un esempio), il click su uno di essi porta ad una navigazione attraverso le colonne di Miller, dove ci sono gli argomenti di secondo livello, e poi l'elenco dei servizi.

Un esempio di percorso completo è:
Alternanza scuola lavoro  -  Studenti-in-azienda  -  Attivazione-di-un-tirocinio-curricolare

che porta alla scheda servizio:
http://vivoscuola.opencontent.it/Servizi-e-Informazioni/Alternanza-scuola-lavoro/Studenti-in-azienda/Attivazione-di-un-tirocinio-curricolare

Si tratta di un prototipo, è quindi incompleto, ma vuole essere un esempio di come potrebbero essere presentati i servizi ai cittadini. Ogni commento è ben accetto.

**Comment by lb16330** [comment]
@mirkobattisti per correttezza il concetto che riporto è estratto da http://design.italia.it/
quindi è un concetto che dovrebbe (IMHO) essere sempre tenuto presente in fase di progettazione.
Il fatto che:

>  Oggi l'approccio seguito, ad esempio su www.spid.gov.it/cerca, è quello di, a partire 
>dall'amministrazione, di mostrare i servizi presenti proprio perchè si è in una fase di startup

A mio avviso può essere provvisoriamente (1-2 mesi al massimo ) accettata una incongruenza tra le linee guida stesse e la realizzione di  www.spid.gov.it/cerca , passati i primi giorni appare come una forte contraddizione ed espone a critiche il sito perchè non aderente alla linee guida, le linee guida perchè ignorate da chi le ha scritte  proprio nel primo servizio nuovo.
Questo il mio pensiero a livello "gestione del progetto".

A livello operativo insisto sulla necessità di intraprendere  l'implementazione di un processo a ciclo continuo utile a determinare ed aggiornare nel tempo le categorie-argomenti-dimensioni di ricerca.
Questo detto attendo una risposta da chi segue il progetto.
Se la risposta sarà si ci sarà il mio contributo ovviamente....
Se non arriverà una risposta chiara o la risposta sarà no allora ringrazio e (come si dice) : "non si sta in paradiso a dispetto dei santi"

Bye bye

**Comment by gunzip** [comment]
@lb16330 il capitolo delle LG del quale hai riportato un estratto non si riferisce (unicamente) alla classificazione dei servizi, ma a una modalità di presentazione delle informazioni che afferiscono *anche* a tipi di contenuto non necessariamente strutturati (es. pagine informative, news, eventi, schede su "come fare per", ...). 

l'obiettivo attuale del sito spid non è essere un portale di accesso ai servizi (che ci sarà, ma è un altro progetto), bensì presentare l'offerta e mostrare un progresso nell'adozione che sensibilizzi (eventualmente) il cittadino. in quest'ottica, a mio parere, ci sta che il focus sia sulla "quantità" considerando anche che la base di dati attuale non è quella del catalogo servizi catalogati con CPSV (che sarà più completa), ma quella del registro servizi SPID (dati che confluiranno asap nel catalogo). dov'è l'incongruenza con le LG ?

@mirkobattisti la soluzione govuk-like va bene. andrebbe analizzata l'accessibilità (es. cosa succede con uno screen reader quando seleziono la voce sulla prima colonna ?). riuscite a condividere la soluzione tecnica adottata isolando HTML e JS e fornendo un codice di esempio ?

di tutta la discussione credo che l'argomento sul quale sarebbe utile ricevere ulteriori feedback è se le categorie indicate nel CPSV oltre che per la **classificazione** vadano in qualche modo "fortemente consigliate" anche per la **presentazione** dei servizi sul sito della PA.

**Comment by lb16330** [comment]
Ok, ho capito...
"non si sta in paradido a dispetto dei santi"

**Comment by gunzip** [comment]
@lb16330 mi spiego meglio: limitatamente alle osservazioni (condivisibili) riguardo il la pagina di 'ricerca' del sito spid, ciò che è _profondamente_ sbagliato non è il contenuto (una lista di amministrazioni abilitate) bensì la voce di menu ("cerca servizi"), fuorviante e che pertanto verrà cambiata (assieme al titolo). va da sè che è poco utile includerla come esempio in questa discussione.

**Comment by lb16330** [comment]
Sono abituato a essere diretto e chiaro: state  cambiando il discorso.
Vi state focalizzando su un solo sito e sul lavoro fatto personalmente.
Temo siate viziati da questo fatto che genera ancora più difficoltà di comunicazione.

Riporto il primo post sperando che qualcun altro partecipi alla discussione ed al progetto.

Un saluto


> Tutte le PA presentano in modo variegato un elenco di servizi:
> Occorre individuare una buona pratica di riferimento per mostrare/ filtrare elenchi di servizi.
> con particolare attenzione all'omoneizzazione delle categorie e delle dimensioni delle categorie stesse.
> Esempi:
> 
>     1. http://www.spid.gov.it/cerca
>     2. http://servizi.regione.fvg.it/portale/
>     3. https://www.inps.it/portale/default.aspx?sID=%3b0%3b11513%3b&lastMenu=11513&iMenu=2&p4=2
>     4. http://servizi.toscana.it
>     5. https://www.comune.roma.it/pcr/it/elenco_servizi_online.page
> 
> hanno approcci molto diversi.
> 
> Come primo contributo si suggerisce di taggare (per poi poter ricercare) ogni servizio per
> 
>     dimensione territoriale [Nazionale, interregionale , Regionale, intercomunale, Comunale] taggando in modo codificato unico (si faccia riferimaneto a ipa o istat)
>     area funzionale (vedi esempio fvg o prese4ntazione catalogo servizi) -tipologia utente:(Extra eu, Eu,it) X cittadino, professionista , impresa. -evento della vita di riferimento
>     altro
> 
> Qundi indivisare una unica ux di riferimento da rendere comune.
>

**Comment by mirkobattisti** [comment]
@gunzip vediamo di attrezzarci per isolare il tutto e fornire un esempio. In che forma? Un esempio online potrebbe andare?

**Comment by gunzip** [comment]
@mirkobattisti da quello che ho visto è utilizzato questo js (dovrebbe bastare): 
https://github.com/alphagov/collections/blob/master/app/assets/javascripts/browse-columns.js

**Comment by mirkobattisti** [comment]
@gunzip ho visto la nuova ricerca dei servizi su http://www.spid.gov.it/Servizi che implementa le colonne di miller. Molto bene (anche se il pallino che gira durante l'attesa e spinge giù tutte le colonne non è meraviglioso)! Significa che è stato integrato in design italia o è stato aggiunto ad-hoc?

**Comment by gunzip** [comment]
@mirkobattisti si, il suggerimento è stato accolto e implementato ad-hoc. dalle stats sembra esser molto più utilizzata la navigazione per categorie che il form di ricerca. ci cono alcune migliorie in coda (es. il back causa un reload della pagina) da integrare asap (alle quali aggiungo il problema che segnali).

**Comment by mirkobattisti** [comment]
@gunzip sono molto felice che abbiate accolto il nostro suggerimento. Vorrei capire se avete una roadmap per integrarlo in design Italia, in modo da avere idea sui tempi. Stiamo lavorando con la Provincia autonoma di Trento e con il Consorzio dei Comuni Trentini per l'implementazione dell'accesso ai servizi (online e non) sulla piattaforma Comunweb (http://www.comunweb.it/), che stiamo allineando a design Italia. E' piuttosto impattante (la piattaforma, rilasciata in open source, è adottata da circa 200 enti) quindi vorremmo capire se è preferibile anticipare lo sviluppo o attendere il rilascio "ufficiale" della funzionalità. Grazie!

**Comment by gunzip** [comment]
dirottata su #190. per l'implementazione procrastiniamo https://italia-it.github.io/ita-web-toolkit/docs/roadmap.html

**Comment by gunzip** [comment]
per condividere qualche risultato: il problema della visualizzazione a colonne é. funziona bene solo se tutte le voci dell'albero selezionate entrano nella viewport, ad esempio scegliendo l'ultima voce sulla home di  gov.uk 'Working, jobs and pensions' si atterra sull'elenco delle sotto-categorie, ma a 1024x768 non si vede la voce nel menu di sx:

![image](https://cloud.githubusercontent.com/assets/148224/20621748/01400a1e-b300-11e6-81ec-b83f9fdb8c82.png)

di conseguenza gli utenti non capiscono perchè si ritrovano "tutto il menu che era già in home" (cit.) 

abbiamo effettuato dei test di usabilità su questo modello sulla vecchia pagina dei servizi spid e abbiamo riscontrato che effettiamente crea disorientamento. abbiamo di conseguenza modificato l'impostazione grafica per evidenziare la gerarchia e guidare l'occhio sulla colonna delle sotto-categorie, es:

http://www.spid.gov.it/categorie/ambiente/servizi-di-pagamento-controllo-pagamenti-tasse-e-tributi

impostazione su cui effettueremo nuovi test.

**Comment by gunzip** [comment]
ref. https://github.com/italia-it/ita-web-toolkit/issues/42
