### ISSUE TITLE
La tabella sulle griglie responsive è tronca (!)

### ISSUE THREAD

**Issue by met67** [italia-it/designer.italia.it#183]
La visualizzazione (in condizioni normali, anche ammettendo che esistano) della tabella nella [pagina sulle griglie](http://design.italia.it/linee-guida/layout/griglie/) è tronca: la terza colonna è smezzata, la quarta manca proprio...
Senza scomodare una non conformità ai requisiti della L.4/2004, mi pare che sia un comportamento inappropriato per qualsiasi sito, a maggior ragione uno che voglia essere responsive.
In questi casi, come minimo, mi aspetterei che la visualizzazione si adattasse alla pagina.
Allego una schermata fatta con Chrome ultima versione in un Mac 1920x1080, grandezza carattere 100%...
Non compaiono nemmeno le (bruttissime) scroll bar che su altre piattaforme danno almeno l'idea che esistano altre colonne oltre a quelle visualizzate.
![griglie](https://cloud.githubusercontent.com/assets/4471785/18542947/c3aa8ae4-7b2d-11e6-963d-253351180a32.png)

**Comment by met67** [comment]
Si, beh, certo il problema non sono le scroll bar :-)
Diciamo che nei casi in cui non ci sono, non sai nemmeno se e quante colonne non vedi :-D
Se si deve rispettare il vincolo di larghezza, allora le tabelle dovrebbero mandare a capo le colonne, adattandosi in maniera intelligente alla larghezza, un roba tipo questa http://codepen.io/pixelchar/pen/rfuqK

**Comment by LivioMo** [comment]
Il problema vero è che chi propone delle linee guida di design non vede queste cose basilari, diciamocelo.

**Comment by gunzip** [comment]
grazie per la segnalazione.

le scrollbar non compaiono, nel caso specifico riportato, per una scelta "estetica" (più o meno recente, più o meno discutibile) di alcuni *vendor* di nasconderle di default; sono visibili in altre combinazioni di OS / browser. 

per quanto riguarda le 'scrollbar su una tabella', laddove non si adottano soluzioni (javascript) come quella segnalata da @met67, sono un male necessario: mostrare la tabella per intero sempre e comunque la rende illegibile sugli schermi più piccoli. la scrollbar è una soluzione diffusa, tant'è che è quella proposta da bootstrap nella sezione [responsive tables](http://getbootstrap.com/css/#tables-responsive), la stessa adottata sul sto delle LG. il fatto che sia popolare non significa che sia ottimale.

nel caso specifico potremmo anche mostrare le tabelle nella loro interezza, ma non risolverebbe il problema: a risoluzioni minori di quella visbile nello screenshot comparirebbero comunque le scrollbar.

una soluzione è pertanto utilizzare un JS come quello citato da @met67 oppure (e personalmente propenderei per quest'ultima) evitare *quanto possibile* l'utilizzo di ```table``` che mal si adattano agli schermi su mobile in qualsiasi scenario.

segno pertanto la issue come 'todo'. ricordo che quello delle LG è un progetto open source dove tutti coloro che sono realmente interessati a cooperare e possiedono le competenze per farlo possono intervenire direttamente sul codice, rendendo il progresso più rapido e presentando, oltre ai problemi, delle soluzioni applicabili nella realtà.

**Comment by met67** [comment]
...ehm... l'esempio che ho fatto NON utilizza alcun JS, se lo apri e vedi il box che CodePen dedica al JS, è vuoto.

Sull'evitare le tabelle, ci sono casi (e la pagina delle linee guida ne è un esempio concreto, senza dover tirare in ballo la sezione Trasparenza che è obbligatoria per legge) in cui le tabelle sono estremamente utili per esprimere correttamente un concetto, devono solo adattarsi correttamente al layout del sito.

Nel caso specifico, chiunque usi Chrome non ha davvero modo di capire che c'è del contenuto nascosto, il che è palesemente in contrasto con la normativa vigente (ad es, ma non solo, cfr. il punto di controllo 4.4).
Poiché si tratta di linee guida per siti che DEVONO rispettare la legge, mi pare che il problema sia un po' più grave di un TODO: se una ditta realizza un sito seguendo queste linee guida ed il sito non passa il collaudo si rischia un contenzioso senza fine.

**Comment by met67** [comment]
A proposito di conformità alla normativa, poi, non sono riuscito in alcun modo ad arrivare a vedere le colonne nascoste navigando da tastiera (Requisito 5, Punto di controllo 5.1), ma forse c'è un modo che non ho trovato.

**Comment by gunzip** [comment]
vero, è senza JS :) tuttavia sostituendo "utilizzare una soluzione come quella citata" alla frase "utilizzare un JS come quello citato" la sostanza non cambia. in ogni caso concordo sul fatto che va rivista quella tabella anche per la problematica della navigazione da tastiera che riporti.

> ci sono casi (e la pagina delle linee guida ne è un esempio concreto, senza dover tirare in ballo la sezione Trasparenza che è obbligatoria per legge) in cui le tabelle sono estremamente utili per esprimere correttamente un concetto

ok, ma, applicando la soluzione che citi, le tabelle rimangono tali fino a un certo breakpoint e diventano pertanto meno utili quando "scatta" la ridisposizione dei contenuti; motivo per il quale spesso è altrettanto utile pensare *dall'inizio* a modalità alternative di visualizzazione che siano valide in *tutti* gli scenari e non solo su desktop (il che il più delle volte si traduce nell'utilizzare un'alternativa alla ```table```).

> Nel caso specifico, chiunque usi Chrome

credo che accada in particolare su Mac (con Chrome su Linux vedo una scrollbar)

non mi è chiaro a cosa ti riferisci esattamente qui:

> se una ditta realizza un sito seguendo queste linee guida ed il sito non passa il collaudo si rischia un contenzioso senza fine

anche considerando che la discussione è incentrata su un problema specifico del sito (e non riguarda il contenuto dei testi)

**Comment by met67** [comment]
Lo scenario "contenzioso al collaudo" è questo: 
Una PA fa una gara per realizzare un sito, e chiede il rispetto sia delle LG che della L.4/2004 (per quanto ovvio, non prevedere nel contratto il rispetto della L.4/2004 rende NULLO il contratto stesso).
La ditta segue le LG e realizza un sito in cui le tabelle si comportano come la pagina di esempio sulle griglie.
La PA, al collaudo, rileva che le pagine con le tabelle non sono conformi ai requisiti della L.4/2004 e non collauda la fornitura.
La ditta sostiene di aver seguito le LG e quindi di non aver colpa e chiede il pagamento della fornitura.
Ed ecco il contenzioso...

Per la questione "breakpoint", le pagine delle LG sono particolarmente sfigate, visto che il menù è sempre visualizzato e quindi una bella fetta della pagina è costantemente occupata dal menù. In altri siti, tipicamente, sarebbe usato il menù burger e quindi si potrebbero vedere più colonne prima di far scattare il reflow.
A patto di trovare una soluzione al problema della navigazione da tastiera (se non si risolve, le LG portano a siti non conformi alla legge...), si potrebbero prevedere due stili di tabelle, con reflow e senza.

**Comment by gunzip** [comment]
seguire le LG non significa attingere da una soluzione specifica (che nessuno ha bollinato quale esente da problematiche :), bensì attenersi a quanto descritto nei testi. non nascondo che, a tendere, una "soluzione specifica da cui attingere" è un obiettivo che vorremmo perseguire con questo progetto (vedi #166); ciò non avverrà partendo dal codice del sito che, in ogni caso, è giusto sia corretto per una questione di coerenza (più che di utilità): chi ha seguito il progesso sa che le osservazioni in merito vengono accolte più o meno solertemente (sarebbe ancor più rapido se chi propone le modifiche lo facesse direttamente sul codice) così come avverrà con la problematica esposta in oggetto.

**Comment by gunzip** [comment]
il capitolo è stato rivisto levando le "istruzioni" legate a bootstrap.

**Comment by met67** [comment]
Certo che se la soluzione ad un problema di contenuti "semanticamente" strutturati in tabelle un po' più larghe di due colonne è togliere i contenuti stessi, siamo messi bene.

**Comment by gunzip** [comment]
spesso omettere qualche parola di troppo si rivela la scelta più saggia (less is more), a volte
non viene spontaneamente e bisogna lavorarci un po'.

sono state rimosse le istruzioni che riguardavano bootstrap: le LG dovrebbero astrarre dalle tecnologie utilizzate, al limite va inserito qualche rimando.
