### ISSUE TITLE
E' proprio necessario l'outline arancione sugli <a> :focus dei menu laterali (burger compreso)?

### ISSUE THREAD

**Issue by QUB3X** [italia-it/designer.italia.it#185]
Noto che su siti come governo.it e http://alpha.regione.sardegna.it/  (tanto per fare un esempio) quando si clicca sul burger o nei link del drawer del menu laterale compare una (a mio dire) fastidiosa outline arancione, che sinceramente stona un po' con il background solitamente blu dell'header ed e' anche bruttina da vedere.
![cattura](https://cloud.githubusercontent.com/assets/6921879/18615088/75b7af16-7d9d-11e6-9ab9-2c927db8cb19.PNG)
E' anche brutto da vedere il padding quando e' in un secondo livello del menu.
![cattura2](https://cloud.githubusercontent.com/assets/6921879/18615089/77532620-7d9d-11e6-9783-41a34f731a9a.PNG)

Non ne trovo menzione da nessuna parte su design.italia.it.

Non che sia niente di particolarmente importante, mi e' solo venuto il dubbio se fosse voluta o meno.
Se qualcuno puo' darmi delucidazioni in merito gli sarei grato!

**Comment by gunzip** [comment]
come regola generale, tutti gli elementi che ricevono il focus devono esser facilmente individuabili (" qualsiasi interfaccia utente utilizzabile tramite tastiera deve possedere una funzionalità operativa in cui è visibile l'indicatore del focus"): https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20160317/F78. non è necessario che l'outline sia di un colore specifico; quello utilizzato sui siti citati, simile alla soluzione visibile su gov.uk, è scelto in modo da esser particolarmente evidente.
