### ISSUE TITLE
header e navbar

### ISSUE THREAD

**Issue by groundrace** [italia-it/designer.italia.it#19]
prima che ne vengano fatte mille diverse l'una dall'altra nel template auspico la presenza di una header e navbar riutilizzabile e sopratutto adattabile a qualsiasi Pubblica Amministazione che preveda di poter ospitare il proprio logo ed un menu analogamente a quanto stanno facendo gli amici di 18F negli US https://github.com/18F/web-design-standards/pull/832

**Comment by paolobarberis** [comment]
Assolutamente sì, anche un footer con i link alle policy e ai servizi collegati, aperto anche a servizi di interazione, statistica, help, etc

**Comment by gunzip** [comment]
proporrei un refactoring pressoché completo del css+html del footer / header del sito da usare come testbed per poi includerlo nei template scaricabili

**Comment by davideoliva** [comment]
@groundrace giusta osservazione. Nell'ottica di questo progetto è previsto un unico modello di menu per tutte le PA da quelle locali a quelle centrali?

**Comment by gunzip** [comment]
attualmente non vi sono prescrizioni per il menu se non quelle trasversali al resto dei contenuti (tipografia, colori). per quanto riguarda l'header ci si aspetta che le amministrazioni centrali adottino il colore blu ufficiale.

**Comment by groundrace** [comment]
a prescindere dai contenuti, che ciascuna amministrazione decide, e' necessario che header con relativa navbar e footer oltre alle prescrizioni sui colori, siano disponibili come componenti del template e direi con qualche indicazione aggiuntiva in modo che vengano utilizzati accorgimenti comuni tipo la disposizione dei loghi, dei nomi delle amministrazioni, dei riferimenti per i contatti, le note legali, i link alle sezioni standard come amministrazione trasparente, etc. Aggiungerei che se e' prevista una animazione o delle transizioni di alcune di queste parti, anche queste dovrebbero essere parte delle linee guida.
Un aspetto importante e' proprio quello dell'omogeneita' nel trovare determinati elementi ricorrenti in tutto il Web della PA. Per l'utente e' appagante il fatto di trovare determinate informazioni sempre nello stesso luogo e con le stesse modalita'

**Comment by gunzip** [comment]
@groundrace concordo su tutto, ho segnato la issue come "todo"
(l'omogeneità del resto è uno degli obiettivi precipui delle linee guida)

non prenderei ad esempio l'html/css di header e footer del sito che sono al momento di scarsa qualità nonché difficilmente riutilizzabili (per quello suggerivo un completo refactoring); qualsiasi contributo in questa direzione è ben accetto. fatto ciò direi di aprire un capitolo dedicato nei testi.

per quanto riguarda le transizioni non è prevista al momento nessuna prescrizione / indicazione.

**Comment by davideoliva** [comment]
@groundrace concordo al 100%

**Comment by milesimarco** [comment]
Mi permetto di caricare qualcosa a cui sto lavorando da qualche settimana. Al momento la questione header/navbar la ho affrontata in questo modo:
![cattura](https://cloud.githubusercontent.com/assets/3340185/12004221/f341d426-ab47-11e5-8d6d-d657b392ab55.JPG)

**Comment by gunzip** [comment]
@milesimarco #112

**Comment by mariocariello** [comment]
Buongiorno a tutti, sono appena ritornato al Ministero delle politiche agricole dal seminario di stamani a Via Maresciallo Caviglia.
Volevo segnalarvi il menu del MEF http://www.mef.gov.it che ha utilizzato un componente che si chiama YAMM ed è compatibile con boostrap, di seguito i link
     YAMM per boostrap http://geedmo.github.io/yamm/
     YAMM3 per boostrap3 http://geedmo.github.io/yamm3/ 
una versione bootstrap 4 compatibile ancora non c'è.
che ne pensate?

**Comment by gunzip** [comment]
È in cantiere un paragrafo da integare nei testi.

Intanto qualche indicazione "informale" riguardo i menu

Si dovrebbe garantire che il menu sia utilizzabile su mobile ed evitare:

1. menu a comparsa 'on hover'
2. menu inutilizzabili dopo un resize della pagina o del font
3. più di un menu principale nella navigazione permanente (va bene invece avere un menu principale" più uno contestuale della sezione corrente)

Vanno inoltre necessariamente garantiti i requisiti di accessibilità (mancanze più comuni riguardano navigazione tramite tastiera impossibile, link focus poco visibile, assenza di skiplink(s)).

Per quanto riguarda le voci di menu orizzontali sarebbe bene limitarle a un numero esiguo. Questo, come altri requisiti, vanno di pari passo con una revisione dell'architettura dell'informazione (un capitolo più ampio da trattare a parte).

Inoltre se il motivo per quale si opta per un menu orizzontale è che le voci **devono** comparire immediatamente in evidenza, è probabile che debbano [rimanere tali anche su mobile](http://kyusuf.com/post/a-couple-of-alternatives-to-the-hamburger-menu)

In alternativa è possibile inserire le voci in evidenza direttamente dentro la pagina (in aggiunta che nel menu eventualmente). Esempio su http://www.funzionepubblica.gov.it/

![image](https://cloud.githubusercontent.com/assets/148224/14913760/871ab436-0e05-11e6-9d55-9b5adb139136.png)

Da una rapida analisi l'implementazione menzionata non sembrerebbe presentare nessuna problematica. Ho qualche dubbio sul fatto che siano immediatamente comprensibili i numeri che indicano la cardinalità delle voci annidate nella versione mobile (da testare con qualche utente). Inoltre è necessario dare più risalto ai link che ricevono il focus (cfr. menu su governo.it con border: #ff8c00 solid 3px). Infine, l'implementazione su mef.gov.it risulta esteticamente più gradevole di quella negli esempi poiché il panello a comparsa occupa il 100% della viewport in larghezza.

Coinvolgerei @GianniSinni

**Comment by gunzip** [comment]
Aggiunto capitolo http://design.italia.it/linee-guida/header/

**Comment by gunzip** [comment]
chiudo la issue, segnalo #162 come correlata

https://github.com/italia-it/designer.italia.it/issues/162

**Comment by mariocariello** [comment]
Buongiorno a tutti, mi sono letto e riletto tutte le issue, consumato i polpastrelli nel digitare siti per eventuali soluzioni. Stiamo ristrutturando il sito www.reterurale.it, e personalmente ho trovato solo un sito che risolve le nostre problematiche.
Problema n°1: il nostro sito ha tante sotto sessioni (secondi livelli) con relativi terzi livelli. E' un portale da decine di migliaia di pagine.
Problema n°2: Il menu di primo livello stretto all'osso ha 7 voci e con circa 40 sotto livelli
Problema n°3: Il menu burger a nostro avviso non serve a nulla su risoluzioni desktop se non ad aumentare la navigazione di un click
Problema n°4: l'apertura dei menù on mouse open con abilitato sia il click sul padre che sui figli per noi è fondamentale
Senza tediarvi troppo ho visto che i colleghi nostri di ISMEA hanno realizzato con bootstrap/FlexCMP un buon compomesso a nostro parere.
Vi segnalo il link: http://www.ismea.it
