### ISSUE TITLE
Condivisione sui social networks

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia-it/designer.italia.it#193]
Ciao,
Vorrei capire se per la condivisione delle pagine sui social ci sono problemi ad usare strumenti esterni come il classico AddThis.
Oppure è preferibile creare dei pulsanti apposta con le funzioni dei singoli social?
Es. https://www.facebook.com/sharer/sharer.php

Grazie

**Comment by gunzip** [comment]
bisogna verificare l'accessibilità del widget utilizzato. puoi dare un riferimento per il caso specifico ?

**Comment by AlessandroVecchi** [comment]
Il tipo di widget che ho usato è questo
https://www.addthis.com/get/inline-share-buttons

**Comment by gunzip** [comment]
utlizzare elementi dinamici è possibile, è compito dei fornitori valutarne l'accessibilità. in generale, per chi vuole risparmiare questo passaggio (nonché ulteriori implementazioni e scelte sul design), può utilizzare i componenti visibili nel toolkit.
