### ISSUE TITLE
playbook design dei servizi ottobre 2016, reindirizzamenti in pagina.

### ISSUE THREAD

**Issue by francescomilano** [italia-it/designer.italia.it#195]
Ciao a tutti.
Volevo segnalare che nell'ultimo aggiornamento, con la pubblicazione del playbook sul design dei servizi, nel caso in cui si clicca uno dei link di reindirizzamento alle row più in alto, la row in questione in cui ci si reindirizza risulta non allineata e deforme.
http://www.agid.gov.it/playbook-servizi/#row0102

**Comment by gunzip** [comment]
corretto grazie
