### ISSUE TITLE
Licenza

### ISSUE THREAD

**Issue by groundrace** [italia-it/designer.italia.it#20]
Nelle note legali disponibili su http://design.italia.it/linee-guida/note-legali/ e' specificata la licenza CC-BY 3.0 immagino per i contenuti e i vari media, ma mancano i termini di licenza per il riutilizzo dei template e del codice (file LICENSE). Inoltre non sono presenti le licenze delle componenti terze parti che sono inserite nel template. Vedi quanto fatto da 18F https://github.com/18F/web-design-standards#licenses-and-attribution

**Comment by fiaschi** [comment]
Ho fatto una pull request con un file LICENSE.md minimale contenente esclusivamente le dichiarazioni di licenza per i componenti di terze parti (Twiiter Bootstrap e Jquery).
Manca la licenza per i font GLYPHICONS perché, per quanto vengano distribuiti insieme a Bootstrap, non è molto chiaro se ne ereditino la licenza.

**Comment by gunzip** [comment]
Parrebbe di si

> GLYPHICONS Halflings are also a part of Bootstrap from Twitter, and they are released under the   > same license as Bootstrap. While you are not required to include attribution on your Bootstrap-based > projects, I would certainly appreciate a visible link back to GLYPHICONS.com in any place you find >
> appropriate (footer, docs, etc).

**Comment by elpaso** [comment]
Al di là dei media e dei contenuti dei componenti di terze parti, qual'è la licenza per il template? 
Sarei interessato a create un template per Joomla! utilizzando questo come punto di partenza.
Di norma rilascio il codice in GPL ma in questo caso quale dovrebbe essere la licenza?
Immagino l'opera derivata  riguardi principalmente i CSS.

**Comment by fiaschi** [comment]
In effetti @agidgov  e @gunzip non hanno ancora chiarito questo aspetto interessante. Attualmente si parla solo di CC-BY 3.0 che non è una licenza ad hoc per il software, ma legalmente vale quella per ora.

Detto questo, spassionatamente, siamo ancora in fase embrionale con questo progetto, fossi in te aspetterei un po' prima di impegnarmi per lo sviluppo di un template joomla.

**Comment by gunzip** [comment]
ho proposto CC0 sto aspettando conferme

https://wiki.creativecommons.org/wiki/CC0_FAQ

**Comment by gunzip** [comment]
ho aggiunto 

https://github.com/italia-it/designer.italia.it/blob/master/LICENSE.md
https://github.com/italia-it/ita-bootstrap/blob/master/LICENSE.md

se ok lascio chiusa la issue
