### ISSUE TITLE
loghi custom legati al servizio

### ISSUE THREAD

**Issue by saiballo** [italia-it/designer.italia.it#201]
nell'ambito in cui mi trovo si sta rapidamente diffondendo l'usanza di realizzare siti di terzo livello (collegati all'amministazione principale) che al posto del logo della rep italiana utilizzano un logo custom legato al servizio.

ecco un esempio: https://cartadeldocente.istruzione.it

qualcuno può darmi delucidazioni in merito dato che le linee guida sono abbastanza fumose su questo tema? secondo me è sbagliato perchè alla fine si viene a creare un header custom per ogni servizio oppure è ammessa questa pratica?

**Comment by gunzip** [comment]
Diversi portali già esistenti utilizzano loghi 'tematici', es:

- cartadeldocente.istruzione.it
- 18app.italia.it
- infoprecompilata.agenziaentrate.gov.it 
- opencantieri.mit.gov.it
- soldipubblici.gov.it
- ... 

sembra difficile prescindere da un logo personalizzato nel caso dei siti tematici.

**Comment by saiballo** [comment]
e quindi? è possibile allora usare loghi personalizzati senza problemi?

**Comment by gunzip** [comment]
si, rendendo comunque visibile la provenienza del progetto (che la ragione d'essere della prima fascia dell'header contenente il nome dell'amministrazione afferente)

**Comment by saiballo** [comment]
grazie
