### ISSUE TITLE
Discount Usability

### ISSUE THREAD

**Issue by emilio55** [italia-it/designer.italia.it#21]
L'iniziativa del GLU (Gruppo di Lavoro per l'Usabilità) presso il Dipartimento della funzione pubblica - http://www.funzionepubblica.gov.it/glu - , ha portato dall'avvio dei lavori nel 2012 a produrre il protocollo eGLU 1.0, 2.0, e, dall'agosto di questo anno, la versione 2.1 eGLU-M (per mobile). 

Come molti sapranno, si tratta di un metodo, predisposto da esperti, per test di usabilità semplificati, rivolto a redattori web delle pubbliche amministrazioni, non esperti di usabilità. 

In questo spazio possono essere condivise, con la community degli esperti di usabilità e UX, in modo allargato oltre il GLU,  le istanze che guidano questa proposta: significato, finalità, modalità d'uso e possibili sviluppi tecnici e non. 

Ovviamente a partire da una presenza adeguata di questo metodo nelle Linee guida di design che tenga conto dei contributi prodotti dalla community.

**Comment by gunzip** [comment]
Attinenti: #22 #26

**Comment by emilio55** [comment]
Doveroso segnalare da parte mia che per la definizione di "Discount Usability" faccio riferimento al relativo termine di glossario presente nel protocollo eGLU 2.1 http://www.funzionepubblica.gov.it/media/1256388/protocollo_eglu_2_1_02092015.pdf  
che a sua volta riprende quello di WikiPA http://wikipa.formez.it/index.php/Glossario_dell'Usabilit%C3%A0
