### ISSUE TITLE
Usabilità, definizione

### ISSUE THREAD

**Issue by mboscarol** [italia-it/designer.italia.it#22]
Segnalo un problema con la definizione scelta di usabilità, presa dalla ISO 25010 (invece che dalla più nota e compatta ISO 9241)
a) o si cita l'intero modello 25010, o risulta abbastanza strana, parziale e poco comprensibile, perché non viene specificato come si valutano quelle sottocaratteristiche
b) poiché proprietà della qualità di prodotto, non è congruente con l'uso di metodo di test per la verifica (si basa su proprietà di prodotto e non di utilizzo)
c) ignora le definizioni già presenti in ambito pubblico (ad esempio wikiPA: http://wikipa.formez.it/index.php/Usabilit%C3%A0), che sono già note e diffuse

Ritengo utile scegliere la definizione che più mostra coerenza con gli obiettivi delle PA (e l'efficacia mi sembra il più importante, diciamo, dell'esteticità... :) ) e con le esperienze già note e diffuse, anche semplicemente per evitare di introdurre confusione e incoerenze.

Posso argomentare con maggior dettaglio, se serve.

**Comment by agidgov** [comment]
Ok, perché non proponi la modifica tramite una pull request?

**Comment by mboscarol** [comment]
Ok, ci provo, anche se ci sarebbero vari modi possibili per modificare. Provo in ordine di "desiderabilità" secondo me...

**Comment by gunzip** [comment]
suggerimenti incorporati :)
