### ISSUE TITLE
Alias del progetto

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#24]
Che ne pensate di un nome più corto che "Linee guida di design per i siti web della PA" ?

@agidgov

**Comment by fiaschi** [comment]
Concordo.

**Comment by iperdiscount** [comment]
Propongo: LiGuIT

**Comment by gunzip** [comment]
DesignPA ?

**Comment by davideoliva** [comment]
Anche a me piace DesignPA

**Comment by italia-it** [comment]
Ok DesignPA (può esser utilizzato anche come tag per social etc.)
