### ISSUE TITLE
Notifiche di errore sui validatori a causa dell'utilizzo del TAG <i></i>

### ISSUE THREAD

**Issue by Dorigoleopoldo** [italia-it/designer.italia.it#25]
Suggerisco di prendere in considerazione l'ipotesi di utilizzare un altro elemento ad esempio <span> e non il tag <i></i> un tempo utilizzato per definire lo stile "italic" perchè alcuni validatori segnalano notifiche di errore.

**Comment by italia-it** [comment]
puoi elaborare, es. quali validatori ? esattamente dove andrebbe cambiato ? grazie ! :)

**Comment by fiaschi** [comment]
![image](https://cloud.githubusercontent.com/assets/703787/11345448/3b87d720-9217-11e5-8ec9-6699608a28e9.png)

**Comment by didoo** [comment]
Nel progetto i tag _i_ sono usati per l'inserimento di icone. A quel che vedo Bootstrap utilizza un tag _span_ assegnandogli fra l'altro l'attributo _aria-hidden="true"_:
`<span class="glyphicon glyphicon-euro" aria-hidden="true"></span>`
Tuttavia, le pagine sembrano comunque validare correttamente:
https://validator.w3.org/nu/?doc=http%3A%2F%2Fdesign.italia.it%2Flinee-guida%2Ficonografia%2F

Cosa intendevi, @Dorigoleopoldo? Puoi fare qualche esempio?

**Comment by Dorigoleopoldo** [comment]
@italia-it ,
@didoo : 
Validatori che si occupano di controlli automatici per i requisiti di accessibilità come:

- AChecker
- TotalValidator 

@fiaschi : 
Non restituisce nessun risultato perchè effettivamente non ci sono tag <i> privi di classi. prova con 
<i class="
altrimenti nel codice sorgente della sezione "iconografia"

**Comment by fiaschi** [comment]
Si, si, visto. Sorry

**Comment by gunzip** [comment]
concordo, me ne occupo asap

**Comment by gunzip** [comment]
ho cambiato l'html degli esempi in iconografia per renderlo più accessibile
