### ISSUE TITLE
Titolo descrizione e path nel package.json/supporto bower

### ISSUE THREAD

**Issue by Slumber86** [italia-it/designer.italia.it#28]
Bisognerebbe inserire questi dati, assieme alla gestione delle release su github, almeno si può usare il repository come dipendenza bower o altri Package manager

**Comment by didoo** [comment]
Fai una PR (o suggerisci qui quali vuoi inserire e posso farlo io, no problem).

**Comment by gunzip** [comment]
è inserito in ita-bootstrap https://github.com/italia-it/ita-bootstrap/blob/master/package.json
(che tuttavia è in fase di deprecazione)
