### ISSUE TITLE
Aggiornare sezione colori

### ISSUE THREAD

**Issue by saiballo** [italia-it/designer.italia.it#31]
Non mi è chiara la sezione sui colori. Una PA centrale è di fatto obbligata ad usare il blu istituzionale (con palette associata) oppure è un consiglio?

Se è un requisito, in che misura si deve usare il blu istituzionale? Basta un header? Oppure è necessaria una identità forte orientata ai colori istituzionali?

Non si rischia, in questa maniera, di fare tutti siti PA uguali tra loro? Tanto vale preparare dei template già fatti che i ministeri possano adottare.

Diverso il caso di Gov.UK che, è vero, ha voluto rendere omogenea la sua immagine ma l'ha fatto riunendo sotto un unico sito tutte le PA centrali.

In italia invece stiamo mantenendo separati tutti i ministeri ma, a quanto pare, li stiamo obbligando ad essere tutti cromaticamente simili (non uguali, che forse è ancora peggio)

grazie per eventuali contributi

**Comment by davideoliva** [comment]
Giusta l'osservazione di @saiballo. E le PA locali come si devono adattare a questo schema cromatico?

**Comment by saiballo** [comment]
@davideoliva 
le PA locali, a quanto scritto (questo mi pare più chiaro), sono obbligate a fare l'inverso: ovvero non possono usare i colori istituzionali

**Comment by davideoliva** [comment]
@saiballo grazie, Avevo letto di fretta e non mi era chiaro. Quindi posso partire da un mio colore base e sviluppare una palette cromatica attorno ad esso.

**Comment by fiaschi** [comment]
@saiballo lo scopo di questo progetto è, evidentemente, arrivare ad un template unico :)

**Comment by saiballo** [comment]
se sei in ambito PA locale sì. Devi rispettare i requisiti di accessibilità ma puoi usare la palette che preferisci (ad esclusione del colore #0066CC).

questo è quello che si evince dal documento

**Comment by saiballo** [comment]
ciao stefano,

non so se la tua è un'affermazione o una constatazione :-)

cmq sono d'accordo sul template unico ma allora perchè continuare ad avere domini (e soprattutto costi) separati?

**Comment by fiaschi** [comment]
@saiballo:
"Una volta recepiti i contribuiti dagli utenti, i CSS (o Sass) allegati alle linee guida potranno essere utilizzati nella progettazione dei nuovi siti web della pubblica ammnistrazione. Al momento è prevista l'implementazione come tema del framework CSS Bootstrap." 
dal README.md

**Comment by saiballo** [comment]
non capisco questa risposta ma fa niente :-)

**Comment by yuchi** [comment]
Ritengo che il problema possa essere riformulato in:

> Le linee guida descritte in questa documentazione, poiché impattano anche sulle scelte di brand, come devono essere recepite nelle diverse formule di Pubblica Amministrazione del Paese?

E di conseguenza:

> Aziende e realtà che posseggono un loro brand, devono allontanarsene per accogliere quello descritto in questo documento?

**Comment by gunzip** [comment]
segnalo la #47 come correlata

**Comment by gunzip** [comment]
Riporto la stessa risposta che nella #78 

Il colore istituzionale #0066cc **non** va utilizzato per l'header delle PA locali e si sconsiglia fortemente l'utilizzo anche per qualsiasi altro elemento.

Le PA locali possono utilizzare un qualsiasi colore base seguendo le indicazioni su come costruire una palette adeguata.

Va aggiornata la sezione 'colori' con queste indicazioni.
