### ISSUE TITLE
Accessibilità del sito

### ISSUE THREAD

**Issue by madelfa** [italia-it/designer.italia.it#32]
Ho riscontrato diversi problemi di accessibilità nel sito.

Uno di questi è dato dal fatto che le pagine sono state realizzate con un font base in PX e non come scritto sulle linee guida in sp (Scale-independent Pixel). 

L’utilizzo dell’unità pixel in alcuni browser più obsoleti non permette agli utenti di modificare la dimensione del font, e questo ovviamente comporta un grave problema di accessibilità del sito agli utenti ipovedenti che necessitano di ingrandire il carattere, come riportato nell'Allegato A - D.M. 8 luglio 2005 - Punto di controllo 4.4 - Ridimensionamento del testo: il testo, ad eccezione dei sottotitoli e del testo rappresentato come immagine, deve poter essere ridimensionato fino al 200 percento senza l'ausilio di tecnologie assistive e senza perdita di contenuto e funzionalità.

Ad esempio su IE 9 il testo non viene ridimensionato.

Altro problema riguarda i titoli della pagina "Tipografia":
- Allineamento (H4)
- Giustezza (H4)
- Markup semantico (H4)

Dovrebbero essere degli H3 altrimenti si riferiscono al solo capitolo Titillium Web (H3) e invece dovrebber essere dei capitoli che sono sotto il titolo principale della pagina Tipografia (H2)

Sempre nella pagina "Tipografia" nel paragrafo dedicato a "Dimensioni e interlinea del testo" c'è un refuso "Un paragrafo di testo non deve essere mai essere".

Nota metodologica: perchè utilizzare un linguaggio tecnico che non viene incontro agli sviluppatori? 
Ad esempio, nella pagina "Tipografia" nel paragrafo dedicato a "Dimensioni e interlinea del testo", vengono fornite una serie di indicazioni tecniche sulle dimensioni del testo che non fanno riferimento alle linee guida sui CSS ma alle linee guida sulle APP di Android.

**Comment by gunzip** [comment]
ciao, intanto grazie per le info, puoi fare una pull request con le modifiche ? magari anche più di una suddividendole per "argomento"  (in genere è preferibile aprire issue diverse per argomenti diversi per non rischiare di tralasciare qualcosa). 

al momento siamo tutti volontari. è in programma di allocare risorse, ma attualmente per le richieste del tipo "dovrebbe essere" non accompagnate da una pull request c'è da mettere in conto un probabile delay.

**Comment by gunzip** [comment]
@madelfa ho corretto la sequenza dei titolo nella pagina tipografia e il refuso, inoltre ho creato una nuova issue #51 riguardo il font base.

non mi è chiaro:

> perchè utilizzare un linguaggio tecnico che non viene incontro agli sviluppatori? 
> Ad esempio, nella pagina "Tipografia" nel paragrafo dedicato a "Dimensioni e interlinea del testo", > 
> vengono fornite una serie di indicazioni tecniche sulle dimensioni del testo che non fanno riferimento 
> alle linee guida sui CSS ma alle linee guida sulle APP di Android

puoi proporre una modifica ?

**Comment by gunzip** [comment]
chiusa e aperta #51
