### ISSUE TITLE
Individuazione maintainer del progetto

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#33]
Questa issue è dedicata agli aggiornamenti riguardo l'individuazione dei maintainer (o "community leader" secondo la dicitura in home page :) del progetto.

**Comment by fiaschi** [comment]
Credo che debba trattarsi di qualcuno dell'agid che possa occuparsene a tempo pieno.

**Comment by gunzip** [comment]
ci piacerebbe coinvolgere anche altri soggetti per formare un gruppo di lavoro (costoro non necessariamente a tempo pieno =)

**Comment by fiaschi** [comment]
Non avevo letto il plurale, pensavo ad un community leader singolo.

**Comment by gunzip** [comment]
Se il trend è quello attuale (siamo in una fase in cui bisogna ancora valutare l'interesse nel progetto e la frequenza dei contributi da incorporare) non è sufficiente un singolo moderatore: le competenze richieste sono eterogenee (programmazione / visual design / usabilità / accessibilità), e per prendere decisioni bisogna coordinarsi con esperti di ogni area.

**Comment by M3kH** [comment]
Ciao,
avere visto il primo repository istituzionale su github mi ha suscitato certe emozioni.
Sarei interessato a poter collaborare/contribuire al progetto.

Naturalmente credo di poter dare un notevole contributo mettendo esperienza, abilità e senso critico a disposizione. Ma sfortunatamente non a tempo pieno.
Avete altri canali di coordinamento, per presentazioni meno 'formali'?

**Comment by gunzip** [comment]
@M3kH grazie per la segnalazione. In settimana sono pianificate una serie di attività a riguardo e decisioni da prendere; tutti gli aggiornamenti verranno comunicati appena possibile

**Comment by gunzip** [comment]
http://designer.italia.it/linee-guida/credits/

**Comment by M3kH** [comment]
Sono contento che il team sia già formato,
ma ho già menzionato in un'altro topic che molti degli argomenti/issue/ticket hanno una soluzione `d'opinione` o di `gusto`. Personalmente mi é contribuire a questo repository non sapendo come certe decisione vengono effettuate e su base di quali criteri.

Sembra che tra i `collaboratori` ci siano terzi canali di cui altri `normali` utenti siano esclusi.
Si potrebbe fare chiarezza su questo?

**Comment by gunzip** [comment]
@M3kH è un inizio, dovrebbero aggiungersi risorse operative dai primi mesi del 2016. sono inoltre in produzione alcuni documenti che definiranno meglio le modalità di collaborazione. 

per le soluzioni di gusto e opinione, proprio poiché non dirimenti, privilegiamo un approccio pragmatico (escluderei di fare una votazione ogni volta) che possa portarci a conseguire risultati concreti a breve termine. 

detto ciò, tutti i contributi sono ben accetti, anzi direi più che auspicati. per chi ha intenzione di fornire quelli più sostanziali, sarebbe bene che magari li proponesse prima di iniziare un lavoro che si rivela poi vano.

non mi è chiaro cosa intendi con

> Sembra che tra i collaboratori ci siano terzi canali di cui altri normali utenti siano esclusi

**Comment by M3kH** [comment]
in breve, github non sembra essere l'unico posto dove *coordinamento* e *decisioni* vengono effettuati. Ci sono altri posti che i contributori dovrebbe essere a conoscenza per i motivi sopra citati? Google group, Skype, IRC, Meeting con presenza fisica, etc.. ?

**Comment by fiaschi** [comment]
@M3kH sto collaborando a questo progetto dal 1° giorno e non ho visto decisioni prese da qualche altra parte. Anzi, per ora, non ho visto proprio alcuna decisione presa. 
Abbiamo scelte sostanziali da prendere ( vedi #29 ) e siamo ancora a "Caro Amico" per dirla alla romana. :)

**Comment by M3kH** [comment]
Ok grazie @fiaschi mi hai tolto un'eventuale dubbio.
Provo ad offrire il mio contributo in PR; alla prossima :+1:

**Comment by gunzip** [comment]
coordinamento e decisioni vengono effettuati qui in AgID attualmente. come canale di comunicazione GitHub è al momento la corsia preferenziale, esiste un indirizzo email che speriamo venga utilizzato meno poiché probabilmente sarebbero questioni più utili laddove trattate pubblicamente.

**Comment by gunzip** [comment]
chiudo la issue se nessuno ha nulla in contrario. 

in merito a 

> ho già menzionato in un'altro topic che molti degli argomenti/issue/ticket hanno una soluzione d'opinione o di gusto

vero. ma l'importante è che le soluzioni semplicemente... ci siano: uno degli obiettivi delle LG è tagliare i tempi delle decisioni prendendole "a monte" nonché testate con gli utenti. ciò non significa imporle dall'alto, ma convergere verso soluzioni condivise.
