### ISSUE TITLE
Considerare svg come formato per il set di icone

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#41]
Dal commento di @didoo in #15 

Qualche link di riferimento:

- http://blog.cloudfour.com/seriously-dont-use-icon-fonts/
- https://speakerdeck.com/ninjanails/death-to-icon-fonts
- https://github.com/encharm/Font-Awesome-SVG-PNG
- https://icomoon.io/app/#/select/image

**Comment by saiballo** [comment]
per quelle amministrazioni che ancora impongono IE8 come requisito vanno preparate delle immagini fallback o si può iniziare a lavorare senza pensare più a questo browser?

Lo domando perchè vedendo governo.it il con IE8 si nota che il sito è "leggibile" ma di certo non ottimizzato. Non mi pare sia stata riservata molta cura a questo browser (che da tempo dovrebbe essere morto ma che in realtà è vivo e vegeto nella PA italiana)

**Comment by gunzip** [comment]
Al momento IE8 va supportato con qualche fallback, vedi anche #29 
(va bene che sia leggibile ma non ottimizzato)

**Comment by didoo** [comment]
Riporto qui il commento di @mikfaina in #85:
```
Io consiglierei l'utilizzo di svg al posto di icone https://css-tricks.com/icon-fonts-vs-svg/ e anche questo articolo molto interessante http://blog.cloudfour.com/seriously-dont-use-icon-fonts/ (in inglese entrambi)
```

**Comment by GianniSinni** [comment]
Solo per precisazione (il testo sarà forse da rendere più esplicito): il riferimento al Font Awesome alla pagina Iconografia delle LG indica la necessità di rifarsi a un set omogeneo di icone (stesso stile), non all'uso del font stesso. Quindi sì assolutamente all'utilizzo di svg invece che icon fonts.

**Comment by carlogatto** [comment]
il suggerimento è interessante, e in effetti ci sono parecchie scuole di pensiero sia "pro-icons" che "pro-svg"
 
esiste uno studio parallelo che spiega come rendere le icon-fonts accessibili al 100%

ve lo sottopongo, in modo da avere un quadro completo

https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html

qui c'è il repo su github:
https://github.com/filamentgroup/a-font-garde

**Comment by gunzip** [comment]
riassumendo una tra:

1. icon font con fallback-to-text per risolvere problemi accessibilità / supporto font-face mancante (= Opera Mini)
2. svg font con fallback a testo per IE8 (che non supporta svg). rimane qui il problema di come agire al meglio sullo stile (es. colore delle icone) vedi: http://tympanus.net/codrops/2015/07/16/styling-svg-use-content-css/

**Comment by didoo** [comment]
https://twitter.com/SaraSoueidan/status/674298533667807232

**Comment by didoo** [comment]
Bootstrap font icons => "In V4, all font icons will be removed"
https://twitter.com/s10wen/status/677092661761847296

**Comment by carlogatto** [comment]
non significa che le font-icons siano state "bandite" da Bootstrap, ma solo che Bootstrap non includerà più il set Glyphicons nel framework

![glyph](https://cloud.githubusercontent.com/assets/4160020/11844257/08199f46-a40e-11e5-9c18-7e51e233979f.jpg)

**Comment by gunzip** [comment]
è possibile utilizzare il set di icone svg / png incluso in

https://github.com/italia-it/ita-web-toolkit/tree/master/src/icons/ita

a corredo [CSS](https://github.com/italia-it/ita-web-toolkit/blob/master/src/icons/ita/font/style.css) dell'icon font e istruzioni per l'utilizzo tramite [sprite svg](https://github.com/italia-it/ita-web-toolkit/blob/master/src/icons/ita/img/Read%20Me.txt).
