### ISSUE TITLE
Evitare di includere i font direttamente dal CSS

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#42]
Vedi @didoo  #15

> il caricamento delle icone è fatto via @include nei CSS, cosa che include automaticamente i font
> anche se potenzialmente potrebbero non essere richiesti ma soprattutto blocca il rendering delle 
> pagine nel browser, al momento del caricamento della pagina

modificare sito e template scaricabili di conseguenza

**Comment by M3kH** [comment]
A merito, vorrei suggerire,
che le icone, come i loghi, dovrebbero essere distribuite in formato *svg*.
Per poi eventualmente essere compilati anche come fonts, quest'ultimo passaggio non é essenziale.

Tuttavia, compilare i fonts, o creare un unico sprite con tutti gli svg aiuta a diminuire le richieste http.
Che rende il download piu veloce nei dispositivi con banda limitata.

Offrire un 'servizio' di compilazione sull'implementazione sarebbe la via ideale per ottimizare le risorse solamente utilizzate.
