### ISSUE TITLE
Repository dedicati per i singoli progetti nell'area download

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#44]
Al momento i file del tema bootstrap scaricabile sono sotto web/assets/agid-guidelines. 
Proporrei di istituire un repository diverso (sempre sotto l'account github italia-it) per ogni progetto (presente e futuro) separato da quello del sito delle linee guida.

**Comment by fiaschi** [comment]
Concordo per una questione di organizzazione, ma come funzionerebbero i deploy? Per intenderci: una modifica al progetto bootstrap andrebbe a variare designer.italia.it?

**Comment by gunzip** [comment]
al momento designer.italia.it non usa i css del tema bootstrap allegato. cambierebbe il puntamento del link "scarica i componenti" che si potrebbe far puntare direttamente allo zip della release del progetto github

**Comment by gunzip** [comment]
chiudo la issue. stiamo ristruttrando la componentistica (HTML/CSS) per renderla fruibile.
