### ISSUE TITLE
Qual è l'ambito di applicazione di queste linee guida e in che misura sono da considerare prescrittive per le PA, centrali e non?

### ISSUE THREAD

**Issue by stella81** [italia-it/designer.italia.it#47]
Il quesito potrebbe apparire eccessivamente burocratico, ma credo possa tornare utile per quanti in enti e società controllati dalle Pubbliche amministrazioni centrali e locali stanno lavorando alla progettazione dei propri siti web. 

Le nuove linee guida si applicheranno solamente alle Pubbliche amministrazioni in senso stretto (art.1, comma 2 del d.lgs. 165/2001) oppure è auspicabile un'applicazione estesa come avvenuto per provvedimenti di natura diversa ma sempre connessi a ICT e siti web (ad esempio legge Stanca e Cad)?

**Comment by saiballo** [comment]
Mi permetto anche di aggiungere una domanda correlata al tema dell'applicabilità delle linee guida: quell'amministrazione centrale che si trova già in una fase avanzata per il rilascio del nuovo portale, come deve comportarsi se non rispecchia alcuni requisiti (penso soprattutto ai colori istituzionali)? buttare mesi di lavoro e rifare tutto? oppure ci sarà un periodo per l'entrata in vigore delle linee guida?

**Comment by bussolon** [comment]
Su suggerimento di @gunzip ri-posto qui una domanda *politica* :)

Che **potere** hanno queste linee guida?
Nel senso: quello che uscirà da questo lavoro verrà poi vagliato da qualcuno che avrà il potere di portare avanti una legge che definirà queste linee guida come vincolanti e che prevederà delle sanzioni a chi non le rispetta e ci sarà qualcuno che controlla e se qualcuno non le rispetta verrà sanzionato?

Aggiungo una seconda domanda: è stata definita una **strategia** nella definizione di questo progetto?
Voglio dire: un conto è dire "togliamo la navigazione dal main", un conto è dire "tutte le pa dovranno fare il sito in bootstrap". Sono due livelli di astrazione molto diversi (entrambi importanti, intendiamoci).

A me piacerebbe che si discutesse in maniera esplicita i diversi livelli di astrazione che vanno dai princìpi di design ai princìpi di usabilità ai pattern alle linee guida alle guide di stile.

Infine mi piacerebbe che si discutessero le finalità del progetto, anche alla luce della prima domanda.

Scusate se sto ponendo domande complicate :)

**Comment by mamokulla** [comment]
Mi piacerebbe conoscere, quanto prima, una riposta da parte dell'Agid in merito alle domande sopra poste soprattutto per poter rispondere ai nostri clienti della PA, che premono per capire se, come e in che tempi (già dal prossimo anno?) si dovranno addeguare a queste linee guida.

**Comment by marcobani** [comment]
Cerco di rispondere ad alcune delle giuste domande che sono state poste sulle finalità e l'attuazione del progetto, 
In questa prima fase sono direttamente coinvolti i siti web delle Amministrazioni centrali. La prossima versione delle linee guida, prevista entro Giugno 2016, prevederà anche indicazioni per le amministrazioni locali. 
Fino a quando non verrà rilasciata la prossima versione non ci sarà nessuna necessità immediata di adesione da parte delle pubbliche amministrazioni locali.
Le amministrazioni locali che desiderano aderire già adesso alle Linee guida, possono rientrare nel gruppo di sperimentatori che AgID sta predisponendo per testare e preparare le nuove indicazioni. La volontà di partecipare a questo gruppo dovrà essere segnalata a lineeguidasitipa@agid.gov.it. AgID sceglierà un primo elenco di amministrazioni locali in base alla loro tipologia, peculiarità, efficienza e impegno nel progetto.

Le eventuali norme che sosterranno l’adesione e l’applicazione delle linee guida prevederanno un tempo di attuazione compatibile con l’ordinaria amministrazione degli enti, in modo che l'adeguamento non sia causa di imprevisti finanziari o tecnici.

Invece, le amministrazioni centrali che volessero maggiori informazioni possono contattare direttamente AgID per un supporto tecnico-operativo al solito indirizzo lineeguidasitipa@agid.gov.it

**Comment by stella81** [comment]
Grazie mille delle precisazioni. Avrei bisogno di qualche ulteriore dettaglio. Da queste linee guida restano, quindi, escluse le società a totale capitale pubblico controllate dai Ministeri?

**Comment by marcobani** [comment]
In questa versione rientrano anche le società a totale capitale pubblico controllate dai Ministeri: un esempio simile, ma non uguale, riguarda il MAE (Ministero Affari Esteri) che utilizzerà questa versione  delle linee guida per i siti satellite degli istituti italiani di cultura e delle ambasciate. Se poi ci sono dubbi sui casi singolari siamo sempre disponibili al chiarimento.
