### ISSUE TITLE
Tooltip icone

### ISSUE THREAD

**Issue by marcochiesi** [italia-it/designer.italia.it#48]
Nella pagina Iconografia è riportato che:

> Quando si utilizzano delle icone è necessario assicurare una chiara comprensione del loro significato. Pertanto ogni icona dovrà essere associata a un tooltip che ne chiarisca l’azione.

Sarebbe utile mettere un esempio esplicito basato sui [Tooltip di Bootstrap](http://getbootstrap.com/javascript/#tooltips).

A mio parere comunque il tooltip è necessario solo nei casi di icone a sé stanti, mentre mi sembra superfluo per icone che sono a corredo di un'etichetta di testo.

**Comment by gunzip** [comment]
aggiunto un attributo title negli esempi in iconografia
