### ISSUE TITLE
Verifica ridimensionamento font e unità per dimensione base (px / em)

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#51]
Vedi #32

**Comment by jdeyla** [comment]
Avete considerato l'uso dell'unità REM per i font? Chi non la suppota, la ignora e usa quelle standard,  è meno influenzabile dall'annidamento dei contenitori, e oggi è piuttosto ben supportata http://caniuse.com/#search=rem

**Comment by gunzip** [comment]
il sito utilizza già rem con falback px

**Comment by didoo** [comment]
La mia esperienza mi dice che usare `px` aiuta molto nella riduzione della complessità (usare unità poco conosciute - al developer medio - implica introdurre ulteriori freni all'adozione degli stili condivisi).
Fra l'altro, unità "liquide" andrebbero usate se tutta l'interfaccia è liquida, cosa che considerato il tipo di progetto non è pensabile. E fra l'altro su GOV.UK pare usino `px` per i font: https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_typography.scss

**Comment by gunzip** [comment]
parliamone. @madefa segnalava che utilizzando i px il ridimensionamento dei font su IE9 non funziona.
inoltre utilizzare px come font-size di base e rem per tutto il resto facilita avere una tipografia "responsive" (perché basta cambiare il font-size base per le varie media query al posto che ridefinire tutta la tipografia)

**Comment by fiaschi** [comment]
Facciamo un po' di chiarezza: 
utilizzando i px come dimensione del font base il ridimensionamento del font non funziona su tutte le versioni di IE (non solo su IE9), tanto che le best pratices impongono l'utilizzo di un font-size relativo (%) per il font base cosa che viene applicata su google.com, nytimes.com e w3.org per fare qualche esempio.
Essendo però molto utilizzato lo zoom della pagina su IE, a discapito dell'ingrandimento del font (è anche un po' macchinoso trovarlo su IE10+) è ormai ammesso anche il sizing del font base in px, (vedi gov.uk) personalmente però non ne comprendo il giovamento.
@madelfa propone di utilizzare un unità scale indipendent come gli sp che però hanno la problematica di funzionare solo su android e su chrome nei desktop e non dagli altri browser, quindi andrebbero comunque utilizzati con un fallback in percentuale.
@didoo propone di non utilizzare le unità relative (sono d'accordo sugli em che sono la causa principale di visite nei centri di igiene mentale per gli sviluppatori frontend, meno sui rem), come fa gov.uk, ma la scelta, oltre ad avere la problematica che segnalava @madelfa, ci pone nella condizione di prevederne delle variazioni elemento per elemento con le media queries.
Soluzioni tipo gli em o le percentuali per gli elementi le troverei totalmente complesse da gestire, soprattutto con un preprocessore CSS.

Alla luce di questi fatti personalmente la mia classifica di preferenza è la seguente:

1) % per il font base, rem per gli elementi
2) px per il font base, rem per gli elementi

**Comment by gunzip** [comment]
dico la mia personale opinione. usare *rem* conviene se si intende scalare i font per le varie media query unicamente ridefinendo il base-font-size (quindi si scala tutto di una certa percentuale a seconda della risoluzione). come diceva @didoo questo ha senso solo se anche gli altri elementi della pagina scalano (es. se la grid è definita anch'essa in rem, come avviene in Bootstrap 4 e se non sbaglio Foundation 6). 

l'alterativa, usando i px, è ridefinire il font-size per tutti gli elementi / classi (quello che ad esempio fa gov.uk utilizzando i vari ```@include media(tablet)``` su ogni ```h*```). in questo caso anche i breakpoint sono definiti in px.

**Comment by giovanisp** [comment]
salve, non sarebbe meglio seguire le indicazioni delle tecniche WCAG (Techniques and Failures for Web Content Accessibility Guidelines 2.0 - C14: Using em units for font sizes) ?
http://www.w3.org/TR/WCAG20-TECHS/C14.html

**Comment by gunzip** [comment]
l'utilizzo dell'unità 'em' per il font-size è problematico. il consiglio delle wcag riguarda i browser che non supportano lo zoom dell'intero contenuto; al giorno d'oggi (2016) sono davvero pochi. è invece lecito l'utilizzo di 'em', ad esempio, per margini che devono scalare *assieme* al font-size del singolo elemento.

il problema dei px (l'unico ?) è che non onorano il font-size di default *eventualmente* impostato dall'utente nei settings del browser. ipotizzo che non sia una funzionalità che trova largo utilizzo, considerando la possibilità dello zoom...

**Comment by gunzip** [comment]
la soluzione proposta è utilizzare font in percentuale (html) + rem (body) + fallback in px per i browser che non supportano rem

https://github.com/italia-it/ita-web-toolkit/blob/master/index.css
