### ISSUE TITLE
Sotto iPad il testo del banner sulla privacy non è leggibile

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#53]
Allego qui screenshot che illustra il problema.

![image](https://cloud.githubusercontent.com/assets/2411296/11460681/37decfd2-96f1-11e5-9574-3ba8e5469247.png)

**Comment by gunzip** [comment]
Ho corretto lo z-index dell'elemento per lo scroll a inizio pagina. Se confermate che è risolto possiamo ciudere la issue

**Comment by renatius** [comment]
Sotto iPad OK ora.
