### ISSUE TITLE
Perplessità sull'uso nelle pagine dei tag h1-h4

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#58]
Ho una serie di perplessità sull'uso dei tag h1-h4 all'interno delle pagine.

a) Visto che si sta utilizzando html5, mi aspetterei che il titolo di grado superiore all'interno dell'elemento <main> sia un elemento h1 e non un elemento h2. 

b) analogamente mi aspetterei che il titolo di livello più alto all'interno delle varie pagine sia il tag h1 dell'elemento <main> e non il testo "Linee guida di design per i siti web delle PA" (che è uguale in ogni pagina) e che non si trova peraltro nemmeno all'interno di un tag <header> ma è posto dentro un elemento <nav>

**Comment by gunzip** [comment]
Ok per riconsiderare l'utilizzo di H1 come titolo delle pagine.

Non mi è chiaro:

>  non si trova peraltro nemmeno all'interno di un tag ma è posto dentro un elemento

a cosa ti riferisci esattamente ?

**Comment by renatius** [comment]
Scusate, GitHub ha rimosso alcune parti per cui il messaggio è in effetti incomprensibile :)

Il testo corretto è:

a) Visto che si sta utilizzando html5, mi aspetterei che il titolo di grado superiore all'interno dell'elemento **main** sia un elemento h1 e non un elemento h2.

b) analogamente mi aspetterei che il titolo di livello più alto all'interno delle varie pagine sia il tag h1 dell'elemento **main** e non il testo "Linee guida di design per i siti web delle PA" (che è uguale in ogni pagina) e che non si trova peraltro nemmeno all'interno di un elemento **header** ma è posto dentro un elemento **nav**

**Comment by gunzip** [comment]
ok, la segno come "todo" (oltre a cambiare la semantica degli heading va valutata la resa visiva alle varie risoluzioni). vedi anche la #19 (l'header va completamente rivisto e reso riutilizzabile nei template scaricabili)

**Comment by renatius** [comment]
Parte del problema, aggiungo, deriva dall'attuale scarso supporto per l'algoritmo di sectioning di html5, il cui (mancato) supporto si fa particolarmente sentire quando la pagina viene "letta" tramite tecnologie assistive (es. Jaws). In pratica, a seconda del livello di supporto del lettore, l'outline del documento può anche cambiare notevolmente.

Una descrizione dell'algoritmo di outlining (e dei suoi problemi) può essere trovata qui:
http://html5doctor.com/outlines/

Qui sotto ad esempio riporto come apparirebbe l'outline della pagina iniziale se l'algoritmo venisse implementato:

![cattura](https://cloud.githubusercontent.com/assets/2411296/11472462/08099cd4-976d-11e5-9cbe-c6abad7dfed4.PNG)

che corrisponde all'url https://gsnedders.html5.org/outliner/process.py?url=http%3A%2F%2Fdesign.italia.it%2Flinee-guida%2Fprincipi-generali%2F

Una possibile soluzione, per siti che devono garantire l'accessibilità, potrebbe forse essere non fare uso (per il momento) degli elementi di sectioning di html5 (main, section, article, etc...) e continuare ad usare i tag h1-h6 alla vecchia maniera?

**Comment by gunzip** [comment]
proporrei di usare gli elementi di sectioning assieme a h1-h6 alla *vecchia maniera* (è retrocompatibile). 
ovvero:

```
<header>
  <h1>Linee guida di design per i siti web delle PA</h1>
</header>
<article>
  <h2>Titolo articolo</h2>
</article>
```

rimane da decidere se avere due h1 (uno per "Linee guida di design per i siti web delle PA" e uno per l```'article```) o tenere com'è adesso l'h2 per il contenuto (propenderei per la prima soluzione)

**Comment by renatius** [comment]
Io sarei per avere il tag h1 soltanto dentro al main e corrispondente al titolo della pagina (piuttosto che al titolo del sito). Le scritte "Governo Italiano" e "Linee guida...", infatti, potrebbero essere incorporate, come testo, all'interno dell'attributo alt delle immagini corrispondenti. 

Sperimentando un pò tra algoritmo classico di outlining e algoritmo html5, la combinazione che riporto sotto sembra produrre una outline simile in entrambi i casi (sacrificando però proprio l'uso dei sectioning elements di html5 per suddividere il contenuto principale).

Il problema è che, indipendentemente dalla teoria, l'outline del documento serve principalmente a chi fruisce delle pagine non visualmente usando tecnologie assistive (es. Jaws o VoiceOver) e, quindi, in ultima analisi l'arbitro su quale struttura adottare dovrebbe essere proprio l'esame tramite screenreader, i quali al momento mi pare di capire spesso rispettino poco l'algoritmo html5.

[  sigh ! se solo esistesse un Can I Use anche per gli screenreader! :(  ]

```html

<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Per un design dei servizi della Pubblica Amministrazione | Linee guida di design per i siti web della Pubblica Amministrazione</title>
</head>
<body>
  
<div class="skiplink sr-only">
  <ul>
    <li><a href="#main" tabindex="800">Vai al contenuto principale della pagina</a></li>
    <li><a href="#nav-sito" tabindex="800">Vai alla navigazione del sito (sommario delle linee guida)</a></li>
    <li><a href="#footer" tabindex="800">Vai al footer</a></li>
  </ul>
</div>

<header role="banner">

  <div class="logogov">
    <a href=""><img alt="Logo Governo Italiano" /></a>     
  </div>
  
  <div class="logosito">
    
    <div>
      <a href=""><img alt="Logo Italia.it" /></a>
    </div>
    
    <div>
      <a href="/" title="torna alla home page del sito">
        <img alt="Sito delle Linee guida di design per i siti web della Pubblica Amministrazione"/>
      </a>
    </div>
    
  </div>
  
</header>  

<nav role="navigation" id="nav-sito">
  
  <h3 class="sr-only">Sommario delle linee Guida (navigazione del sito):</h3>
  
  <ul class="nav navgoco">
    <li><a href="/">Home <span class="sr-only">(sei qui)</a></li>
    <li><a href="/linee-guida/principi-generali">Principi generali</a></li>
    <li><a href="/linee-guida/usabilita">Usabilità</a></li>
  </ul>
  
</nav>  

<main role="main" id="main">
  
  <h1>
    Per un design dei servizi della Pubblica Amministrazione
    <small>versione alfa</small>
  </h1>

  <h2>Premessa</h2>  
  
  <p>Il progetto <strong>Italia Login</strong> persegue la realizzazione di un ecosistema di informazioni e di servizi, secondo quanto previsto
  dal piano di Crescita Digitale, la strategia del Governo per l’innovazione del Paese. Italia Login rappresenta 
  anche un primo passo verso la definizione di un’identità coerente per la pubblica amministrazione centrale.</p>

  <h2>Obiettivi</h2>  
  
  <p>L’obiettivo è di facilitare la costituzione della comunità
  <a href="http://design.italia.it">design.italia.it</a> promuovendola presso gli aderenti alle associazioni 
  e stimolare l’attività di condivisione 
  delle migliori pratiche progettuali al fine di migliorare la consultazione dei contenuti e l’efficienza
  dei servizi online presentati dalle diverse amministrazioni pubbliche e mantenere aggiornate le linee guida.</p>

  <h3 id="-repository-github-delle-linee-guida-https-github-com-italia-it-designer-italia-it-">
    <a href="https://github.com/italia-it/designer.italia.it">Repository GitHub delle linee guida</a>
  </h3>
 
</main>  

<aside role="complementary">
  <h2>
    Vuoi contribuire ? Partecipa creando una issue
    sul <a href="https://github.com/italia-it/designer.italia.it">repository GitHub</a>
  </h2>
</aside>  

<footer id="footer" role="contentinfo">

</footer>

</body>
</html>

```

Confronto delle document outline prodotte:

![cattura](https://cloud.githubusercontent.com/assets/2411296/11502640/5357b3d6-983c-11e5-98ec-964874fc7f65.PNG)

![cattura2](https://cloud.githubusercontent.com/assets/2411296/11502641/5360b314-983c-11e5-84ff-c5d4cff28223.PNG)

**Comment by gunzip** [comment]
@renatius ho incorporato alcuni suggerimenti
(quelli che non richiedevano grandi sconvolgimenti nel css):

https://github.com/italia-it/designer.italia.it/pull/69/files

l'outline dovrebbe essere corretto adesso.

per quanto riguarda l'html dell'header sono d'accordo nel semplificarlo (è in cantiere vedi #19)

riguardo invece l'utilizzo dell'H1 per il main / article aspetterei alcune integrazioni sul paragrafo "tipografia" (vedi #70). allo stato attuale inserire  l'H1 di 72px (come consigliato nel testo delle LG), soprattutto sugli schermi più piccoli non ha una resa visiva ottimale.

**Comment by renatius** [comment]
OK, grazie :)

**Comment by gunzip** [comment]
grazie a te :) chiudo questa e lascio aperte le altre issue correlate
