### ISSUE TITLE
La navigazione laterale (navgoco) dovrebbe stare fuori dell'elemento <main>

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#60]
Secondo:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main

il contenuto dell'elemento **main** di una pagina deve escludere qualsiasi tipo di contenuto che viene ripetuto all'interno delle pagine del sito quali ad esempio barre laterali, link di navigazione, informazioni di copyright, etc...

la barra di navigazione laterale pertanto dovrebbe stare fuori dell'elemento **main**

![cattura](https://cloud.githubusercontent.com/assets/2411296/11470612/8bb59d8e-975f-11e5-92fd-274a1d7ca80e.PNG)

**Comment by gunzip** [comment]
ok, proporrei di sostituire il ```main``` con un ```div``` (al posto che tirare fuori la navbar dal ```main```) poiché tutto il resto sarebbe comunque contenuto in un ```article``` (si potrebbe considerare di sostituire ```article``` con ```main```).

**Comment by renatius** [comment]
concordo su entrambi i punti :)

**Comment by gunzip** [comment]
ho sostituito il main con un div #66. chiuderei la issue

**Comment by renatius** [comment]
ok per me
