### ISSUE TITLE
Integrazioni al testo sezioni form / bottoni

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#61]
È necessario integrare gli esempi di form con del testo che spieghi i casi d'uso e le best practice per accessibilità e usabilità.

Link di riferimento
- http://govuk-elements.herokuapp.com/buttons/
- http://govuk-elements.herokuapp.com/form-elements/
- https://www.gov.uk/service-manual/user-centred-design/resources/patterns/form-structure.html

**Comment by MaoX17** [comment]
Per quanto riguarda l'inserimento delle date e delle ore cosa pensate sia meglio?
Io ho sempre utilizzato https://github.com/eternicode/bootstrap-datepicker/ e mi sono sempre trovato molto bene... voi che ne pensate? Può in qualche modo rendere meno accessibile / usabile l'applicazione?
Non pensate che sarebbe opportuno suggerire anche l'adozione di componenti di uso più comune?
In questo modo, secondo me, oltre ad uniformare la visualizzazione grafica dei siti istituzionali, potremmo anche rendere più semplice ed economico l'aggiornamento e la manutenzione delle applicazioni web.
Inoltre eviteremo la perdita di tempo nella valutazione del componente più funzionale e/o semplice oppure potremmo semplicemente suggerire alcuni esempi pratici di utilizzo che aiuterebbero tutti a ottimizzare le proprie risorse. 
Saluti

**Comment by gunzip** [comment]
@MaoX17 

> Non pensate che sarebbe opportuno suggerire anche l'adozione di componenti di uso più comune

si, ma non con priorità altissima. 

nel caso specifico vedi anche

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/dates.html

**Comment by gunzip** [comment]
in merito ai suggerimenti riguardo « componenti di uso più comune » possiamo utilizzare il toolkit
https://italia-it.github.io/ita-web-toolkit/

vedi anche le issue in coda (tra cui il datepicker):
https://github.com/italia-it/ita-web-toolkit/issues
