### ISSUE TITLE
IE8 - elementi con classe .lg-callout sono privi di padding

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#62]
In allegato l'immagine che illustra il problema

![cattura](https://cloud.githubusercontent.com/assets/2411296/11475560/5789892a-977e-11e5-9901-b7cb9c4b9c9c.PNG)

**Comment by gunzip** [comment]
@renatius grazie per le segnalazioni. quelle relative a IE8 le metterei a bassa priorità dato anche il target del sito :)

**Comment by gunzip** [comment]
era dovuto alla minificazione CSS:
 https://github.com/gunzip/designer.italia.it/commit/2c282276b11889cc30cbdfeb975a3b6b126efdee
