### ISSUE TITLE
IE9 (-11?) - il font Titillium Web viene scaricato ma non viene usato per la renderizzazione

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#63]
In allegato screenshot che illustra il problema.

![cattura](https://cloud.githubusercontent.com/assets/2411296/11475886/11715772-9780-11e5-9a2e-2dda39b9ca3b.PNG)

Il problema si verifica anche con IE 8-11 (da BrowserStack)

![cattura2](https://cloud.githubusercontent.com/assets/2411296/11476029/ce2e35b0-9780-11e5-9748-b15f4a956e13.PNG)

**Comment by renatius** [comment]
Osservo peraltro che, sotto IE9, iniettando il link di GoogleFonts sul DOM usando i developer Tools (F12), il font viene caricato e renderizzato correttamente:

![cattura](https://cloud.githubusercontent.com/assets/2411296/11476164/8ce7034c-9781-11e5-8c6a-72e2cf89d62c.PNG)

**Comment by gunzip** [comment]
in emulazione IE8 / IE9 da Edge pare funzionare. Investigo il problema asap

**Comment by gunzip** [comment]
credo che il problema fosse dovuto all'utilizzo di https, la #72 dovrebbe aver risolto il problema, se ho conferma chiudo la issue

https://github.com/italia-it/designer.italia.it/pull/72/files

**Comment by renatius** [comment]
Si, ora sotto IE9 funziona. Suggerirei però di non usare // senza protocollo, ma di specificare https:// esplicitamente nel link:

https://twitter.com/paul_irish/status/588502455530311680?lang=it

**Comment by gunzip** [comment]
il problema è proprio un errore di certificato (su IE8) quando si utilizza https

**Comment by renatius** [comment]
OK

**Comment by renatius** [comment]
Per me si può chiudere la issue
