### ISSUE TITLE
Integrare CSS dei template scaricabili nel sito delle LG

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#65]
Attualmente il sito utilizza un CSS differente da quello dei template scaricabili.
È necessario unificare il tema bootstrap in modo che sia lo stesso per i template e per il sito stesso,
auspicabilmente tramite l'inclusione di una dipendenza bower (vedi #28 e #44)

**Comment by fiaschi** [comment]
Concordo, se trovo del tempo ci metto mano, magari lunedì.

**Comment by gunzip** [comment]
Grazie @fiaschi, ma la procrastinerei vedendo come evolve la #29

**Comment by gunzip** [comment]
ref. https://github.com/italia-it/ita-web-toolkit/issues/45

andrebbe fatto un tema per [fractal](fractal.build) utilizzando il toolkit:
https://italia-it.github.io/ita-web-toolkit/
