### ISSUE TITLE
Migliorare l'accessibilità del sito

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#68]
- rivedere sequenza tabindex e fix per link offcanvas
- controllare e integrare l'utilizzo degli attributi wai-aria 
- test tramite screenreader

link di riferimento:
- http://heydonworks.com/practical_aria_examples

**Comment by jdeyla** [comment]
Posso dare una mano se serve, anche a verificare. 
suggerirei di:
*  non esagerare con gli ausili (es. io non metterei sempre il link per raggiungere il footer negli skiplink),
* verificare il comportamento al clik, in modo che si omogeneo tra interfacce (ovvero il menù usabilità e accessibilità, al click si aprono, ma non succede lo stesso se premo SPACE o INVIO)

**Comment by gunzip** [comment]
@jdeyla sicuramente serve una mano =) 

sul primo punto ho dei dubbi; in genere i footer delle PA contengono delle informazioni importanti (es. contatti e soprattutto link ad area "amministrazione trasparente" con bandi e concorsi) che in molti casi sono esattamente quelle ricercate dall'utente.

accolgo invece  in pieno la seconda osservazione, è un comportamento che va sistemato.

**Comment by jdeyla** [comment]
Capisco il tuo punto, ma segui il ragionamento.

Più cosa ci sono su una pagina, più la pagina è pesante da fruire, specialmente con gli ausili.
Il link per il salto dei contenuti è per evitare che ti venga sempre riletta una parte della pagina (il menù), è un link di utilità che ha un uso probabilmente frequente.
Il footer invece contiene informazioni, che se va bene, vengono lette 2 volte nella vita, mentre quel link ti viene letto ad ogni pagina.
Così come suggerirei di usare sempre lo stesso sistema, anche per la home.
Un sito che è certamente da seguire come indicazioni e soluzioni è http://www.webaim.com 

Quindi seguendo la filosofia, less is more, consiglio solo un link per saltare ai contenuti, magari con un accesskey, (se vuoi usando quelle standardi che usano altri sistemi, es.
http://www.regione.emilia-romagna.it/accessibility-info/  1 home, 2 salto ai contenuti))

**Comment by jdeyla** [comment]
**Aggiungo: tabindex**

visto che è tra le cose che ti sei segnato, occhio ai tabindex: cambiare le sequenza naturale della pagina, anche solo mandando il focus in un punto raigonevole, non porta mai cose buone, perchè modifica l'immaine che vcerti utenti si fanno dei contenuti.
Se la scorrono col tab appare in un modo, se l scorrono con le frecce e lo screen reader in un altro.

L'unica vera operazione che si deve fare, è verificare sempre che chi edeve ricevere il focus lo riceva. Certe volte elementi html usati in modo improprio (es. span come bottoni) non lo ricevono.

**Comment by gunzip** [comment]
Tramite  #80 ho aggiunto il comportamento al click / focus per gli elementi del menu che permettono di espandere le relative voci (al momento accessibilità / usabilità). Inoltre ho levato il footer dagli skiplink (pensandoci, rimane comunque raggiungibile navigando "al contrario" con shift+tab) e aggiunto le accesskey.

**Comment by matteobelfiore** [comment]
Anche io mi rendo disponibile se serve aiuto.

È importante ricordarsi —senza forse scendere in ogni minimo dettaglio— che l'accessibilità non si limita agli screen reader e agli utenti visually impaired. Negli ultimi tempi si è parlato molto anche di transizioni, animazioni, movimenti improvvisi della UI che spesso sono inutili ma che portano disagi a una porzione importante dell'utenza.

**Comment by gunzip** [comment]
ho integrato alcune altre modifiche suggerite in #138

per ora chiudo la issue, se sussitono le condizioni la riapriamo. per quanto riguarda l'animazione nelll'header rimando a #90
