### ISSUE TITLE
Occorre aumentare la coerenza nei testi

### ISSUE THREAD

**Issue by didoo** [italia-it/designer.italia.it#7]
Leggendo i testi si trovano diverse versioni della stessa parola o scritta con capitalizzazioni diverse (esempio: "pubblica amministrazione" e "Pubblica Amministrazione", "Linee Guida" e "linee guida") o con generi diversi (esempio: "la repository" e "il repository").
Per evitare un numero eccessivo di pull-request atomiche (ovvero, piccole correzioni che non diano adito a conflitti nella fase di merge) sarebbe opportuno che questo lavoro di revisione fosse fatto dai maintainer di designer.italia.it, non dai contributor.

**Comment by GianniSinni** [comment]
Giusta osservazione. Provvediamo.

**Comment by gunzip** [comment]
ho impostato 'Pubblica Amministrazione' con le maiuscole solo quando se ne parla in senso lato
