### ISSUE TITLE
Tipografia responsive / contestuale

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#70]
È auspicabile integrare il paragrafo sulla tipografia con indicazioni per le intestazioni (headings) che considerino diverse risoluzioni dello schermo (mobile).

**Comment by renatius** [comment]
La mia opinione - evidentemente non condivisa da Bootstrap :) - è che sia problematico pensare che i vari elementi (e quindi anche gli elementi h1-h6) debbano avere determinate caratteristiche tipografiche e visuali (dimensione, colore, peso, interlinea, margini, etc...) **indipendentemente** dal loro contesto di utilizzo. 

Ad esempio, un h3 usato all'interno di una news avrà generalmente bisogno di uno stile css diverso da un h3 che fa da titolo di un riquadro di approfondimento. E un h3 usato come intestazione di una lista di link nel footer avrà spesso bisogno di avere un aspetto diverso dai primi due.

Potrebbe quindi essere più utile descrivere le caratteristiche tipografiche dei vari elementi raggruppandole per contesto di utilizzo e funzione - nel qual caso le attuali linee andrebbero quindi probabilmente assegnate ad un contesto d'uso di "articolo principale della pagina" - e raccogliendo  in una sezione iniziale separata i criteri generali che sono stati utilizzati per validare le scelte proposte (es. livello di contrasto tra testo e sfondo non inferiore a 4,5:1).

Quanto sopra ovviamente non nega che sia generalmente più che conveniente definire dei valori visuali di default dei vari elementi - come fatto appunto dai vari normalize.css e reset.css - in modo da renderli per quanto possibile indipendenti dalla piattaforma e dal browser. 

Questo però più che essere parte di una linea guida visuale, credo, dovrebbe essere considerato, soltanto come un meccanismo che facilita la scrittura successiva degli stili nel css (in quanto, ad esempio, non dovrò più preoccuparmi se per ridefinire l'indentazione degli elementi di una lista devo agire sul left-padding o sul left-margin) e andrebbe documentata come tale (cioè non nella sezione Tipografia ma - per fare una ipotesi - nella sezione Normalize.css).

**Comment by didoo** [comment]
Concordo con @renatius, il contesto incide molto sugli elementi tipografici di un testo.
In genere - per i tag `h1-h6` - è diventata prassi comune disaccoppiare l'elemento HTML dalla sua presentazione visuale (dimensione); quindi si troveranno delle regole CSS dichiate in questo modo 
```
h1 { font-size: xxx; }
h2 { font-size: yyy; }
...
.h1 { font-size: xxx; }
.h2 { font-size: yyy; }
...
```
in modo che ad esempio a un "h4" possa essere applicata una presentazione visuale da "h1" semplicemente facendo: `<h4 class="h1">` (sto semplificando, ma è per capirci)

**Comment by fiaschi** [comment]
Concordo con ambedue le opinioni che mi precedono, però bootstrap non ha colpe :)
Non è limitante in questo, nessuno ci vieta di estenderlo con altre helper classes ad hoc.

**Comment by gunzip** [comment]
credo che la critica si riferisse al fatto che boostrap appllica il CSS direttamente ai tag HTML (h1, h2...) senza considerare il contesto es. 

```
h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6 {
  font-family: $headings-font-family;
  font-weight: $headings-font-weight;
  line-height: $headings-line-height;
  color: $headings-color;
```

**Comment by gunzip** [comment]
è corretto limitare al minimo l'utilizzo del CSS globale.
