### ISSUE TITLE
Task gulp per convertire le immagini SVG in PNG

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#73]
Bisognerebbe convertire tutti gli SVG in PNG di qualità migliore di quelli attuali (vedi logo governo non trasparente) per supportare i browser che non renderizzano SVG (Explorer 8)

**Comment by didoo** [comment]
Qui il discorso entra nel tecnico. Esistono plugin Gulp che già si occupano di questo (e ad esempio possono creare sprites SVG, se dovessero servire) e potrebbero farlo anche in doppia risoluzione (anche se credo che chi usa ancora IE8 non avrà display retina :) ). 
Il più è mettere in piedi un sistema che automaticamente sostituisca gli SVG nelle pagine web, se renderizzate in IE8. Consiglio caldamente questo: https://github.com/jonathantneal/svg4everybody

**Comment by gunzip** [comment]
sul sito governo.it hanno usato questo codice:

```
if(!Modernizr.svg) {
    $('img[src*="svg"]').attr('src', function() {
        return $(this).attr('src').replace('.svg', '.png');
    });
}
```

non ho incluso Modernizr per una serie di motivi (richiede una build custom che complica l'integrazione tramite bower) allora ho optato per 

```
  if (!document.implementation.hasFeature('http://www.w3.org/TR/SVG11/feature#Image', '1.1')) {
    $('img[src*="svg"]').attr('src', function () {
      return $(this).attr('src').replace('.svg', '.png');
    });
  }
```

do un'occhiata alla lib che suggerisci =)

**Comment by gunzip** [comment]
memo: http://una.im/svg-icons

**Comment by umbros** [comment]
Aggiungo un tool per l'ottimizzazione dei file svg: https://github.com/svg/svgo
E' presente anche una versione gui ma non è aggiornata.
Per installarlo: npm install -g svgo
Per ottimizzare un file:
svgo nomefile.svg
svgo nomefile.svg nomefileottimizzato.svg

**Comment by umbros** [comment]
https://www.npmjs.com/package/gulp-svg2png
