### ISSUE TITLE
Browser nativo Android non visualizza il font e i pesi del font

### ISSUE THREAD

**Issue by decarola** [italia-it/designer.italia.it#77]
Al momento mi limito a segnalare, appena torno ad avere un device Android tra le mani provo a fare la pull request

![design-italia-font](https://cloud.githubusercontent.com/assets/693956/11537730/aec8eb3a-991e-11e5-9ce4-7323c043a0ec.png)

**Comment by fiaschi** [comment]
@decarola Puoi testare se il problema si ripete sia su http://design.italia.it sia su http://designer.italia.it ?
