### ISSUE TITLE
Colore istituzionale #0066cc

### ISSUE THREAD

**Issue by saiballo** [italia-it/designer.italia.it#78]
Il colore istituzionale principale #0066cc è ormai una scelta definitiva oppure no? Lo chiedo perchè all'interno del gruppo di lavoro in cui sto (una PA centrale) siamo tutti concordi che abbia un' alta saturazione (è molto accesso) e che alla lunga affatichi non poco la lettura.

E' vero che il gusto grafico è assolutamente personale ma come tonalità di BLU avrei scelto qualcosa di meno sparato...

**Comment by gunzip** [comment]
@GianniSinni @paolobarberis

**Comment by jdeyla** [comment]
@saiballo tipo #0057AD ? o ancora meno #004A93 ? in effetti essendo a video, i colori sono piuttosto relativi...

**Comment by saiballo** [comment]
sottolineando ancora una volta che sì, i colori sono assolutamente relativi su uno schermo e che inoltre molto è dato dal gusto personale, trovo la tua proposta #004a93 molto interessante.

dal mio punto di vista è anche meno "sparata" per un sito istituzionale

**Comment by renatius** [comment]
Perfidamente allora propongo anche #005393 :)

**Comment by saiballo** [comment]
tutte le vostre proposte mi piacciono semplicemente perchè sono desaturate rispetto al colore istituzionale.

una domanda secca: non mi è ancora chiaro se lo 0066cc è un colore che necessariamente deve essere presente nel sito (come governo.it e italia desgin che lo hanno messo nell'header) oppure può essere usato solamente per i link ed il resto dei colori si basa sulla palette proposta dalle linee guida

**Comment by didoo** [comment]
A proposito di colori, valutate se ha senso dare tutte quelle varianti (gradazioni di colore) basate sulla luminosità. Avere così tante scelte apre le porte alla differenziazione, invece che alla coerenza e all'uniformità

**Comment by GianniSinni** [comment]
@saiballo Il colore #0066CC è il colore istituzionale per i siti della pubblica amministrazione centrale, quindi il colore delle header ed eventualmente di altri moduli presenti sulla pagina (vd governo.it).

@didoo Le gradazioni sono state create allo scopo di rendere flessibile l'utilizzo del colore in funzione delle varie necessità che potranno incontrare designer e sviluppatori. Il principio su cui basarsi è quindi "coerente non significa uniforme".

Sulla scelta del colore si potrebbe dire molto. Non è stata facile dato che il blu è ormai il colore preferito in assoluto dalla maggioranza delle persone occidentali e quello più associato al concetto di istituzionalità (vd. Blu, storia di un colore di Michel Pastereau). Qui di seguito la tabella di alcuni dei blu più utilizzati:

![schermata 2015-12-06 alle 10 37 39](https://cloud.githubusercontent.com/assets/15969789/11612782/e92410e8-9c07-11e5-90cc-77304cfe05fd.png)

**Comment by gunzip** [comment]
Il colore istituzionale principale #0066cc è una scelta definitiva da applicare alle PA centrali.

Per le PA locali ci saranno integrazioni (al momento non vi sono indicazioni).

Rimane inoltre sospeso se è possibile per le PA locali utilizzare il blu-italia al di fuori dell'header.

**Comment by gunzip** [comment]
Il colore istituzionale #0066cc non va utilizzato per l'header delle PA **locali** e si sconsiglia fortemente l'utilizzo anche per qualsiasi altro elemento. 

Le PA locali possono utilizzare un qualsiasi colore base seguendo le indicazioni su come costruire una palette adeguata.

Lascio aperta la issue: va aggiornata la sezione 'colori' con queste indicazioni.

**Comment by crisbaret** [comment]
Salve, quando si parla di verifica del contrasto, si deve considerare anche la "Colour Difference" che sia superiore a 500?
Perché il colore istituzionale con testo bianco si ferma a 459.
Mi è sfuggito qualcosa?

**Comment by gunzip** [comment]
@crisbaret il contrasto è conforme a WCAG AA (livello raccomandato nelle LG) nonché AAA per "large text" (ovvero quello utilizzato negli header).
