### ISSUE TITLE
Risoluzione minima versione desktop

### ISSUE THREAD

**Issue by H3xx3n** [italia-it/designer.italia.it#81]
Suggerisco di abbassare la risoluzione minima per la versione desktop da 992px a 940px. 
Si usa spesso suddividere uno schermo full hd in due parti e ad oggi il sito sarebbe in modalità mobile. Con 50px in meno l'usabilità in modalità desktop non ne risentirebbe.

**Comment by fiaschi** [comment]
Andrebbe discussa la questione, perché il breakpoint a 940px non è molto usato e in effetti lo stesso bootstrap utilizza per default il breakpoint a 992px, così come praticamente tutti i framework css e le linee guida più diffuse consigliano un breakpoint a 1024px (992px + scrollbar su alcuni browser).
Bootstrap 4 alpha continua ad utilizzare il breakpoint a 992px (62em).
Si tratta comunque di una discussione interessante, perché non è detto che le nostre scelte non possano migliorare scelte anche diffuse, ma andrebbe avvalorata da dati e discussioni esterne. 
@H3xx3n riesci a riportare qualche discussione corposa di qualche altro progetto?

**Comment by H3xx3n** [comment]
940 sta per la metà di 1920 meno 20 pixel di respiro nel caso di scrollbar. Non vuole essere una costante assoluta.
Credo che la risoluzione full HD sarà un punto di riferimento per i prossimi anni e per ottimizzare l'usabilità l'uso dello schermo diviso in due è usanza molto comune nell'ambiente dove lavoro.
Inoltre anche Windows 8 e Windows 10 hanno introdotto molte scorciatoie e strumenti per consentire una visualizzazione semplificata a metà schermo per le applicazioni. Basta pensare ai tasti Win + frecce.

Suddividere in due uno schermo full hd significa avere due sezioni paragonabili a due fogli A4 quindi già familiari alla maggioranza degli utenti. Se vogliamo possiamo impostare metà schermo per il sito e l'altra metà per programmi come Word, Excel senza compromettere l'usabilità di uno dei due ma anzi incrementando la produttività perchè non si deve passare da una finestra all'altra.

Inoltre secondo i miei gusti avere dei contenuti "mobile" su una risoluzione a limite (maggiore di 900px e minore di 992px) vorrebbe dire sacrificare molti elementi che potrebbero fare comodo all'utente senza che questi occupino troppo spazio.

**Comment by gunzip** [comment]
poché "standard de facto" condivido la posizione di @fiaschi, tuttavia lascerei aperta la discussione

**Comment by gunzip** [comment]
proponiamo tre breakpoint:

```
@custom-media --sm-viewport screen and (min-width: 768px) and (max-width: 992px);
@custom-media --md-viewport screen and (min-width: 992px) and (max-width: 1440px);
@custom-media --lg-viewport screen and (min-width: 1440px);
```

https://github.com/italia-it/ita-web-toolkit/blob/master/index.css
