### ISSUE TITLE
Considerare l'utilizzo della lingua inglese

### ISSUE THREAD

**Issue by XVincentX** [italia-it/designer.italia.it#82]
It would be better to drive all development in English.

**Comment by jdeyla** [comment]
should it really? Once we've got a 100% pure .it developement fot .it project. Can't see the PROs, can't you explain your point of view?

**Comment by renatius** [comment]
Please elaborate :) Why do you feel that it would be better?

I have personally mixed feelings about such a proposal. I fear it might risk putting off a lot of Italian developers and graphic designers who are not necessarily that comfortable with English, while I doubt there are many non Italian speaking developers who would join a project that is targeted exclusively at the Italian PA. So it might raise rather than lower the barrier to entry.

But this is just my view.

**Comment by gunzip** [comment]
personalmente lo riterrei fuori discussione. le issue github potrebbero di per sé costituire una knowledge base per i tecnici delle amministrazioni.

**Comment by didoo** [comment]
concordo con @renatius (ancora, siamo proprio in sintonia). anche io ci avevo pensato, se aprire un topic su questo tema (mi faceva stranissimo scrivere in Italiano su GitHub) ma poi mi sono dato la risposta che farlo in inglese avrebbe ridotto di moltissimo l'intervento di altre persone (indipendentemente dal fatto che sappiano l'inglese o no). e visto che immagino lo scopo di usare GitHub sia quello di allargare il più possibile gli interventi e i contributi esterni, sarebbe un controsenso.
personalmente chiederei a @gunzip di chiudere la issue (rimane comunque disponibile come riferimento futuro della scelta presa)

**Comment by darkmartin** [comment]
Vedo e rilancio: nomi delle classi in italiano?

**Comment by gunzip** [comment]
allargherei a nomi classi / funzioni e commenti nel codice, potrebbe aver senso averli in inglese ?

**Comment by didoo** [comment]
@darkmartin suvvia! stiamo parlando delle discussioni su GitHub, non del codice! 
@gunzip questo invece è un punto interessante, su cui vale la pena discutere: entrambe le scelte hanno pro e contro. Ad esempio avere commenti in inglese apre le porte a contributi "non italiani" - ma a questo punto il codice implementativo va spostato in un altro repository, e quello sì che avrebbe senso con discussioni in inglese. Mentre avere i commenti in italiano apre le porte a una maggiore adozione da parte dei dipartimenti IT delle pubbliche amministrazioni

**Comment by gunzip** [comment]
@didoo potremmo presupporre che un *developer* sappia quel minimo di inglese che serve a leggere poche righe di commento =)  mi preoccupano più i nomi intrinsecamente in italiano (es. i nomi dei colori)  che devono matchare con quelli dei testi (es. avere un ```button-rosso```)

**Comment by didoo** [comment]
no @gunzip altrimenti devi prevedere `button-lillá` o `border-caffè` :) quindi nomi delle classi in inglese. tutto ciò che è codice è *necessariamente* in inglese.

**Comment by gunzip** [comment]
@didoo per farti un esempio qui https://github.com/italia-it/designer.italia.it/blob/master/styles/_colors.scss c'è una procedura Sass che crea in automatico i nomi della classi da quello dei colori. Se mettiamo tutto in inglese, come li chiamiamo i colori ?

**Comment by didoo** [comment]
Vedi che torniamo al punto, al nodo gordiano da risolvere sull'implementazione vs. i principi? se usassimo Bootstrap, il colore del bottone con azione primaria non puoi chiamarlo "bottone-te-verde", devi per forza chiamarlo `primary-action` o quello che è il nome dato da Bootstrap al colore delle azioni primarie, adesso non ricordo.
Per quanto disaccoppierai (puoi creare una variabile `$primary-action: $colore-te-verde`) ti ritroverai sempre in situazioni in cui scegli il colore, altri in cui la variabile disaccoppiata, altri in cui sarà lasciato a chi implementa la cosa. Leggi: un caos e una anarchia. Quindi ben vengano i colori in italiano nelle linee guida, non nel codice (ovvero: nomi delle variabili dei colori e eventuali classi in inglese, con commento a lato del nome in italiano, se servisse).
Capisco che possa sembrare un overkill, ma il codice è **sempre e comunque** in inglese (ti immagini un sito web giapponese, con i nomi delle classi o delle funzioni in giapponese?)

**Comment by gunzip** [comment]
ok per me github e testi in italiano, codice / commenti in inglese

**Comment by darkmartin** [comment]
> potremmo presupporre che un developer sappia quel minimo di inglese che serve a leggere poche righe di commento
- @gunzip 

I beg to differ.
