### ISSUE TITLE
Differenziare colori alert per informazioni ed alert per successo

### ISSUE THREAD

**Issue by Vizjerey** [italia-it/designer.italia.it#83]
http://design.italia.it/linee-guida/form/#alert-per-informazioni

Come potete vedere i colori degli alert per le informazioni e per i successi sono gli stessi. Sarebbe idoneo differenziarli per evitare possibili confusioni da parte degli utenti. Una soluzione potrebbe essere il classico verde, che caratterizza il successo dell'azione compiuta.

EDIT: visto ora che nella palette di colori il verde non è contemplato. Rimango comunque dell'idea che avere lo stesso colore per due tipi di informazioni diverse può creare confusione.

**Comment by jdeyla** [comment]
**Concordo**, ma ricordo che l'accessibilità vuole che non sia il colore l'unico mezzo per distinguere le informazioni. Ora, è vero che il titolo dell'alert e il messaggio aiutano comunque a capire il senso del messaggio, e che si possojno usare per certi utenti, appropriati attributi WAIARIA, ma di solito si usano anche delle **icone per certi contesti o tipi di oggetto**. 
Qui sono caldamente sconsigliate, sebbene siano indicate librerie da cui attingere: **possiamo pensare casi in cui sono ammesse e rivedere alcune posizioni**?

**Comment by gunzip** [comment]
@jdeyla si, aprirei una issue apposita

**Comment by jdeyla** [comment]
fatto #85

**Comment by gunzip** [comment]
https://italia-it.github.io/ita-web-toolkit/components/detail/alert--error.html
