### ISSUE TITLE
Uso delle icone: limitatissimo, ma forse necessario?

### ISSUE THREAD

**Issue by jdeyla** [italia-it/designer.italia.it#85]
Riprendo il suggerimento di @gunzip su #83 e apro un issue appostia sull'uso delle **icone**

Qui sono sconsigliate, ma **ci sono casi in cui potrebbe essere opportuno**.

Da noi, in Regione Emilia-Romagna le utilizziamo sempre, **abbinate ai messaggi di avviso, errore, conferma**, per superare il limite dell'accessibilità e dell'usare il solo colore.

Lo stesso bootstrap da una parte non lo consiglia http://getbootstrap.com/components/#alerts ma da un'altra lo consiglia quando si parla di accessibilità e spiega come fare http://getbootstrap.com/components/#glyphicons-how-to-use

**Un altro caso** in cui le usarei, oltre ai messaggi, è **su alcuni bottoni chiave**, quelli per spedire un modulo o per fare un upload.

(beh di fatto ammetto che io usarei i glifi di bootstrap (oggi e domani quel che verrà)  sempre, abbinati al testo di un bottone)

**Comment by gunzip** [comment]
non mi è chiaro dove esattamente sono sconsigliate. ti riferisci alla pagina"iconografia" che andrebbe rivista ?

**Comment by jdeyla** [comment]
si, a quella... ammetto che non ho il quadro completo degli scambi e dei lavori da fare, mi basavo su quel che avevo letto nel sito... allora siamo a posto? sdoganiamo le icone e diciamo a bootstrap di seguire i consigli che nasceranno dall'esito della nostra discussione?

**Comment by gunzip** [comment]
si, direi che, parafrasando quanto scritto in iconografia, un hint esclusivamente visivo non accompagnato da un testo / titolo / tooltip non è sufficiente laddove il messaggio comunicato tramite l'icona è fondamentale (e non sono una decorazione grafica). 

credo che alcuni dubbi di questo tipo possano essere sciolti anche guardando al lavoro compiuto (e da compiere) sui siti pilota (per ora governo.it, a breve seguiranno altri)

**Comment by mikfaina** [comment]
Io consiglierei l'utilizzo di svg al posto di icone https://css-tricks.com/icon-fonts-vs-svg/ e anche questo articolo molto interessante http://blog.cloudfour.com/seriously-dont-use-icon-fonts/ (in inglese entrambi

**Comment by gunzip** [comment]
@mikfaina vedi #41
