### ISSUE TITLE
Hamburger Menu e User Experience

### ISSUE THREAD

**Issue by QUB3X** [italia-it/designer.italia.it#89]
È comprensibile da tutti il cosiddetto Hamburger Menu (cioè le tre linee orizzontali)?
Nonostante ormai chiunque abbia uno smartphone lo conosca, a colpo d'occhio si potrebbe confondere un po' con il logo ".it" di questo sito.

**Comment by gunzip** [comment]
direi che è ormai un pattern consolidato

**Comment by didoo** [comment]
concordo
