### ISSUE TITLE
Quali browser supportare ?

### ISSUE THREAD

**Issue by gunzip** [italia-it/designer.italia.it#91]
È necessario integrare i testi specificando quali browser supportare (in particolare se supportare Explorer 8) e in che misura (fallback).

**Comment by renatius** [comment]
Io sarei per **non** supportare IE8, per i seguenti motivi:

1) I dati di uso più recenti ne stimano la diffusione a circa lo 0.4% del totale [http://www.w3schools.com/browsers/browsers_explorer.asp]

2) molti siti di largo uso non lo supportano già da molto tempo (es: Facebook, Google) [https://www.quora.com/Internet-Explorer/What-major-companies-has-dropped-support-for-IE8-on-their-Apps]

3) il 12 Gennaio 2016 (cioè fra circa 40 giorni) IE8 andrà fuori supporto della stessa Microsoft (https://support.microsoft.com/en-us/gp/microsoft-internet-explorer)

4) dati i limiti di cui sopra penserei che la quasi totalità delle persone che hanno ancora IE8 (o sono costrette al lavoro ad usare IE in compatibility mode) hanno comunque accesso a un browser alternativo più moderno.

5) IE8 è un browser molto diverso dai browser moderni. Ad esempio non supporta media queries, border-box, font .woff, etc... Pertanto scrivere un layer di compatibilità per IE8 (fossero anche solo fallback) è comunque parecchio lavoro e i risultati, dal punto di vista visuale e di esperienza d'uso, sono spesso mediocri.

**Comment by gunzip** [comment]
@renatius premesso che qui siamo tutti schierati per non supportarlo :)
Ti riporto le stats sul sto AgID di novembre:

![image](https://cloud.githubusercontent.com/assets/148224/11589045/8eff250e-9a85-11e5-8c1d-1a8bd14cbc3b.png)

il sito è visitato in gran parte da pc di pubbliche amministrazioni, di cui una grossa percentuale probabilmente monta ancora Windows Xp (sic.). è un fattore che terrei in considerazione.

**Comment by darkmartin** [comment]
Come giustamente fatto notare da @gunzip  in Italia i dati sono meno rosei che nel resto del mondo, e stiamo comunque considerando un contesto PA - anche se considerei tutti i browser, non solo IE, per avere una percentuale di utilizzo veritiera di una versione piuttosto che di un'altra.
Propongo di ragionare più per *feature* supportate, senza escludere completamente un browser o l'altro, riallacciandomi alla battaglia per il *progressive enhancement* di Jeremy Keith.
Quindi: 
- se il browser supporta le *media query* il sito utilizzarà le *media query* per il *rendering*;
- se queste non sono supportate il sito verrà reso con un layout leggibile, ma non identico (e questa disparità non dovrebbe essere segnalata come *issue* di accessibilità). 

Idem per i vari *border-radius* e compagnia: includere tutti senza dover per forza garantire la stessa esperienza.

**Comment by jdeyla** [comment]
Io ragionerei anche basandomi sulla **sicurezza**, non solo le features. 
Io pensavo che la scelta di bootstrap avesse già definito una soglia di ingresso, comunque ben venga i *progressive enhancement* ma in 3 passi:
- la sicurezza è un obbligo per le PA. 
- Gli utenti con vecchi IE sono tendenzialmente di PA. 
- IE8 è, e diventerà sempre più "insicuro".

Smettere di supportare browser insicuri favorisce l'aggiornamento delle tecnlogie.

Da noi in Regione Emilia-Romagna ci sono forse antichissime applicaizoni interne che vanno con IE, ma forniamo anche Firefox: chi ha detto che un browser che va bene per dentro, debba anche essere usato fuori e chi ha detto che se hai XP non puoi avere Firefox o fartelo installare da chi può?

**Comment by fiaschi** [comment]
Inps ha abbandonato Internet Explorer 8 da circa un anno e mezzo, con l'abbandono di Windows XP in favore di windows 7. La gran parte dei nuovi sviluppi non tengono conto del supporto a questo browser, ma sinceramente, visti anche i dati di DigitPA, io sarei per continuare a supportarlo.

**Comment by renatius** [comment]
Ma è un costo enorme. E, a mio parere, ingiustificato. Se quei browser IE8 fossero tra i normali cittadini (cioè fra i destinatari dei servizi delle PA) allora sarebbe comprensibile e giustissimo farlo. Ma sono invece praticamente tutti all'interno delle PA stesse. Dove peraltro - come dice @jdeyla e come confermo anch'io per la mia parte - sospetto si trovino (per forza di cosa) quasi sempre in coesistenza con le versioni recenti, se non addirittura ultime, di altri browser.

Da quello che vedo i numeri portati da @gunzip sono le percentuali relative fra le varie versioni di IE, non i dati totali fra tutti i browser. Se consideriamo che IE, a livello consumer (quindi cittadini) in Italia, è ormai sotto il 20% del totale, la percentuale parziale del 16,6% andrebbe quindi  ricalcolata come se fosse un 3.0 - 4.0% del totale [che è appunto in linea con quanto riportato ad esempio qui: http://www.internetpost.it/classifica-web-browser-2015-chrome-vincitore-assoluto/]

**Comment by darkmartin** [comment]
> Ma è un costo enorme. E, a mio parere, ingiustificato. 
-- @renatius 

Appunto parlavo di specificare le modalità di supporto. Basta anche una semplice tabella come avviene nella [Perfida Albione](https://www.gov.uk/service-manual/user-centred-design/browsers-and-devices.html).
Se qualcuno naviga con IE8 è probabilmente perché non ha scelta, non perché gli piace.

**Comment by renatius** [comment]
E come mai potrebbe piacergli? :)

**Comment by gunzip** [comment]
@renatius esatto, più o meno è  il 4% del totale il che non è trascurabile. riporto dalla pagina linkata da @darkmartin di gov.uk:

>Although Internet Explorer version 8 is only used by a minority (3.6% of visits to GOV.UK in the last year) this still accounts for a significant number of individuals that government services must take into account.

mi sembra una buona idea impostare una pagina che ricalchi https://www.gov.uk/service-manual/user-centred-design/browsers-and-devices.html 

inoltre poiché la considerazione di @jdeyla sulla sicurezza è molto interessante, la integrerei in qualche modo (qualcuno si offre per una bozza ? :) trovando il modo migliore di comunicare che IE8 va supportato garantendo l'accessibilità ai contenuti, ma non (necessariamente) la stessa *user experience*

**Comment by darkmartin** [comment]
> trovando il modo migliore di comunicare che IE8 va supportato garantendo l'accessibilità ai contenuti, ma non (necessariamente) la stessa *user experience*

Dovremmo trovare un equivalente in lingua italiana di *compliant* e *functional* per il supporto. Diciamo supporto "completo" e "funzionale"?

**Comment by fiaschi** [comment]
"conforme" e "funzionale" ;)

**Comment by renatius** [comment]
@gunzip però la pagina continua con:

> However, over time this will change. So it’s important to set thresholds for abandoning support and for adopting new and emergent platforms. Windows 10 and Microsoft Edge highlight this dilemma – recently launched products might not appear in any data but it is likely that they’ll eventually enjoy widespread use.

Infatti fino allo scorso Ottobre invece di IE8 nel testo c'erano IE6 e IE7:

https://github.com/alphagov/government-service-design-manual/commit/f5ff095e8d2031568e7c9a150b79e50f979d65c0

Ora, le linee guida oggi sono in alfa e sono (almeno rispetto a quanto visibile in governo.it) piuttosto basic. Per essere utilizzabili per progettare e realizzare un sito intero manca ancora un pò di roba. Poi andrebbe anche realizzato il sito. Considerato quanto esposto prima, quale sarà la percentuale di uso di IE8 per allora?

**Comment by matteocrippa** [comment]
IE 8 è un software del 2009, ha i suoi 7 anni di vita, con i limiti che ne consegue. Soprattutto per il comparto sicurezza.

I siti di PA potrebbero fornire anche un supporto di formazione digitale ai visitatori cercando di istruirli e informarli nell' avere software più sicuri, dato che comunque saranno quelli con i quali andranno ad accedere a dati personali.

Garantire la sicurezza e creare una campagna di informatizzazione anche per i meno informatici potrebbe essere una soluzione interessante e da valutare su questo 5% di utenza.

**Comment by fiaschi** [comment]
La questione sicurezza è molto interessante e convincente, un po' perché è più che ragionevole e poi è un'argomentazione spendibile anche con le singole PA restie all'aggiornamento.
Si potrebbe ragionare sulla falsa riga della tabella di compatibilità di gov.uk con un vantaggio temporale rispetto a loro che ci permetterebbe di tralasciare IE7, lavorare su una compatibilità funzionale per IE8 e iniziare con la compatibilità conforme da IE9+?

**Comment by giovannicuccu** [comment]
Mi inserisco in questa discussione in quanto molto probabilmente potrei essere o un utilizzatore del risultato finale o realizzare qualcosa che debba essere aderente alle linee guida definitive che  verranno pubblicate. vorrei rimarcare chiaramente quanto detto da @renatius: quando si uscirà pubblicamente con le indicazioni? 
ie8 è in costante calo e le percentuali di utilizzo di ie8 fra 6 mesi saranno diversi da quelle attuali (a tutto scapito di ie8). Se poi si aggiunge anche il tempo che le pubbliche amministrazioni comincino ad usarle effettivamente forse sarebbe il caso di non supportarlo proprio. Se si ipotizza che le linee guida finali siano pronte nella seconda metà del 2016 per una progressiva adozione dal 2017 ha senso pensare ancora a ie8?

**Comment by gunzip** [comment]
@giovannicuccu supporto IE8 funzionale ma non conforme (parafrasando: va bene che aspettarsi che la resa su IE8 non sia conforme alle LG, ma i contenuti devono essere accessibili, evitare cioè che venga mostrata una pagina bianca :)

qualcuno vorrebbe proporre una pagina con le indicazioni secondo quanto descritto in https://github.com/italia-it/designer.italia.it/issues/91#issuecomment-161980876 ?

**Comment by umbros** [comment]
Oltre ogni altra considerazione su versioni datate dei browser, penso sia chiarificatrice l'avviso n.1 del sistema SPID (che entro il 2017 dovrà essere adottato da tutte le Amministrazioni Pubbliche) scaricabile al link seguente: http://www.agid.gov.it/sites/default/files/documentazione/spid_-_avviso_n1_-_sicurezza_canale_trasmissione.pdf . Per il supporto ai browser ritengo, quindi, che si possa far riferimento alla tabella: https://en.wikipedia.org/wiki/Template:TLS/SSL_support_history_of_web_browsers e in generale a tutti quei browser che supportano, senza attività di implementazione, la versione TLS 1.2

**Comment by Jany-M** [comment]
Esistono dati su SO e browser in uso dalla PA in Italia?
Solitamente in ambiente corporate, questi due elementi sono dettati direttamente dall'azienda, proprio per assicurarsi che tecnologia e tools interni siano sempre accessibili, senza doversi quindi preoccupare di chi ha quale browser ecc.

**Comment by gunzip** [comment]
@Jany-M non ci sono dati aggregati a riguardo.

**Comment by gunzip** [comment]
aggiungo #134 come correlata

**Comment by gunzip** [comment]
sono passati un po' di mesi. orientativamente saremmo per IE >= 10. i dati dell'utilizzo dell'8 sono scesi ulteriormente e il 9 è ancora meno utilizzato. i motivi sono quelli già indicati nei commenti: 

- incoraggiare l'utilizzo di browser sicuri e che supportino gli ultimi standard di sicurezza (es. TLS)
- supportare IE8 è un costo
- l'utilizzo è marginale (e non vincolato)

**Comment by gunzip** [comment]
aggiunto capitolo du dispositivi http://design.italia.it/linee-guida/dispositivi/
