### ISSUE TITLE
Checkbox diverse da radio button

### ISSUE THREAD

**Issue by MarioVillani** [italia-it/designer.italia.it#92]
Nell'esempio http://localhost/agid-bootstrap/dist/dropdown.html le checkbox hanno lo stesso aspetto grafico dei radio button.
Sarebbe meglio mostrare le checkbox nella maniera standard(il quadratino checkabile) poiché visivamente si comunica che è possibile selezionare più voci.
Attendo vostri feedback.

**Comment by gunzip** [comment]
Va fatto come dici senza dubbio, la metto come TODO.

C'è una discussione in atto sul fatto di usare o meno Bootstrap #29; in questo periodo di interregno se qualcuno si offre volontario possiamo mettere un quadratino pieno e uno vuoto per le checkbox.

**Comment by MarioVillani** [comment]
Ci penso io. Se riesco in serata faccio una pull request.

**Comment by MarioVillani** [comment]
Avrei bisogno di qualcuno che disegni i png della checkbox, il mio amico grafico non è disponibile. Me ne occuperò poi io del codice(se possibile).

**Comment by gunzip** [comment]
ita-bootstrap è in fase di deprecazione.
