### ISSUE TITLE
Aggiungere link a piano di Crescita Digitale

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#93]
Nella Premessa si fa riferimento al piano di Crescita Digitale. Sarebbe preferibile che tale riferimento fosse un link al documento stesso.

![image](https://cloud.githubusercontent.com/assets/2411296/11600372/8382216c-9acc-11e5-883d-8e8c67b3d192.png)

**Comment by gunzip** [comment]
@celeghin linkiamo http://www.agid.gov.it/agenda-digitale/agenda-digitale-italiana ?
