### ISSUE TITLE
Aggiungere link a pagina successiva / precedente (ristrutturare il menu nei template)

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#94]
Per rendere più semplice la,navigazione (soprattutto in quei dispositivi dove il menù di navigazione laterale non è visibile di default e si è costretti ad agire tramite l'hamburgher menu) troverei utile avere  alla fine del testo di ogni pagina un link che porta alla pagina successiva delle linee guida.

**Comment by gunzip** [comment]
Mi sembra ragionevole. Ci sono un paio di alternative:

1. Si mette in un json la struttura dell'indice e si agisce sul templare delle pagina (post.html) 
2. Si generano tramite Java script estraendoli dell'HTML del menu

Escluderei di inserirli a mano in ogni pagina poiché bisognerebbe tenerli in sync con i cambiamenti del menu

**Comment by GianniSinni** [comment]
@gunzip attiverei non appena possibile (come era previsto d'altra parte sul template)

**Comment by fiaschi** [comment]
@gunzip condivido l'idea di non rendere le pagine dipendenti dalla struttura del menù. Personalmente, non amo nemmeno la soluzione 2, renderebbe quel javascript dipendente dalla struttura del DOM del menù. Credo che la soluzione 1 sia quella più corretta e pulita, si potrebbe estendere costruendo anche il menù laterale partendo dallo stesso json, in modo da avere una sola fonte comune.
