### ISSUE TITLE
Spaziatura degli elementi h2-h6

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#95]
Nelle attuali linee guida, i titoli di secondo e terzo livello sono spaziati in maniera da risultare praticamente equidistanti dal testo che li precede e dal testo che li segue.

Personalmente preferirei che i titoli di testo fossero invece spaziati in modo che la distanza dal testo che li precede sia approx 2x la distanza del testo cui si riferiscono in modo da risultare visivamente accorpati al contenuto che descrivono.

In allegato 2 esempi che usano questo tipo di spaziatura (da:
   http://alistapart.com/article/howtosizetextincss
   http://practicaltypography.com/why-there's-no-e-book-or-pdf.html
)

![image](https://cloud.githubusercontent.com/assets/2411296/11601460/a7de31e8-9ad3-11e5-8dbf-6a3bbe2cc3cf.png)

![image](https://cloud.githubusercontent.com/assets/2411296/11601459/a7a47566-9ad3-11e5-972a-4f21124ccb11.png)

**Comment by GianniSinni** [comment]
Giusta osservazione. Integriamo.

**Comment by gunzip** [comment]
mi sembra ok adesso, altrimenti riapriamo pure la issue.
