### ISSUE TITLE
Definire architettura informativa / indice definitivo dei testi delle linee guida

### ISSUE THREAD

**Issue by renatius** [italia-it/designer.italia.it#97]
Nella outline attuale la voce "mobile first" è situata come sotto voce di Accessibilità. 
Mi sarei aspettato di trovarla invece come voce di primo livello immediatamente prima della voce Griglie

![image](https://cloud.githubusercontent.com/assets/2411296/11610974/390075b8-9bb6-11e5-8858-a01cffca33a3.png)

**Comment by bussolon** [comment]
Forse bisognerebbe discutere l'architettura informativa del progetto

**Comment by gunzip** [comment]
@bussolon riservo questa issue alle discussioni sull'architettura informativa

**Comment by bussolon** [comment]
grazie

**Comment by gunzip** [comment]
direi che potrebbe essere utile una pagina su come strutturare l'A.I. anche nei testi stessi.

**Comment by bussolon** [comment]
@gunzip, @renatius, @fiaschi, (cc @didoo), ho provato a delineare una possibile metodologia e gerarchia per la progettazione delle linee guida. Essendo un documento lunghetto, l'ho pubblicato come post sul mio blog: [Linee guida PA: metodologia e gerarchia](http://www.bussolon.it/blog/2015/12/linee-guida-pa-metodologie-di-progettazione.html). Spero possa essere un contributo utile.

Stefano

**Comment by renatius** [comment]
@bussolon  super! :+1:

**Comment by gunzip** [comment]
@bussolon lo giro qui a chi si occupa del tema più direttamente. 

una proposta su cui si potrebbe iniziare ad argomentare da subito riguarda

>la mappa delle più importanti funzioni e servizi online di pertinenza di una pubblica amministrazione: registrarsi e creare un profilo, autenticarsi, procedure per fare una domanda, chiedere un documento o un certificato, contattare un referente o un ufficio, inviare una certificazione, richiedere e usare la firma digitale, e così via

in altre parole, in che misura, oltre l'adozione di uno stile visuale coerente, impostare UX e architettura dell'informazione uniformi ?

esempio: si potrebbe ipotizzare di raccogliere una serie di principi del tipo 
>*si deve*: tutti i servizi offerti dalla PA devono essere accesibili direttamente dalla home page

**Comment by fiaschi** [comment]
@bussolon concordo pienamente con quanto hai redatto.
@gunzip Si potrebbe partire da ciò che la norma vigente assorda (es. Amministrazione Trasparente in home) ed estendere il resto non toccato dalla normativa.

Ad ogni modo continuo a non avere chiaro quando parliamo del contenuto delle linee guida o del sito delle linee guida. Mi spiego meglio: qua si parla dell'AI di design.italia.it o di un'insieme di regole per l'AI dei futuri siti della PA?

**Comment by gunzip** [comment]
@fiaschi  hai ragione, creo un'altra issue #105

**Comment by gunzip** [comment]
l'indice si sta allungando (contenuti, architettura informativa) ed è previsto che si espanda ulteriormente (seo, mappe, quadro normativo, ...). si potrebbe raggruppare le indicazioni più strettamente attininenti al "visual" (header, form, bottoni, form, iconografia) sotto un'unica voce.

**Comment by gunzip** [comment]
stiamo rivedendo l'infoarchitettura delle LG per far spazio a nuovi capitoli da integrare riguardo

- ottimizzazione contenuti (seo)
- usabilità (capitolato hcd)
- normativa correlata

nonché pattern per service design 
#190

il nuovo indice è visibile su
http://designer.italia.it/
