### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fabiofabbrucci** [italia-it/designer.italia.it#98]
Ciao a tutti.
1. Quali siti oggi utilizzano questo progetto?
2. Quali siti si prevede utilizzeranno questa styleguide?
3. Esiste una roadmap visibile?
4. Chi cura (decide, pianifica) la roadmap di questo progetto?
5. Quali sono le persone (non gli enti) con cui dialogare su questi temi qui sopra?

Non so a chi porre queste domande quindi le lancio in broadcasting.
Ciao, Fabio.

**Comment by gunzip** [comment]
Posso rispondere alla 1: governo.it è il primo dei siti "pilota". 

Per il resto è pianificata una roadmap (3) sul wiki GitHub appena possibile (per ora fan fede le issue con MiIestone beta) e una pagina di "Credits" (4 e 5). La Roadmap è in ogni caso flessibile, dipende anche dalle proposte raccolte qui.

Il lavoro di queste settimane (dal momento del "lancio") ha l'obiettivo di individuare le risorse e definire i workflow / processi decisionali tra chi collabora al progetto (si sono aggiunti alcuni attori); non so darti delle tempistiche precise.

**Comment by MaoX17** [comment]
Buongiorno a tutti,
mi collego a questa issue perchè penso di essere "in tema".
Sto lavorando a un aggiornamento del "template" e dell'intero sistema con il quale gestiamo l'albo pretorio.
Ho deciso di iniziare a utilizzare queste lineee guida in modo da avere un'idea più precisa di quello che possono offrire e in modo anche da poter aiutare (per quanto mi sia possibile) nel debug.
Il link a cui poter consultare il progetto è:
http://albotest.provincia.prato.it/

Se poi volete dare anche pareri e suggerimenti... ve ne sarei immensamente grato :-)
Saluti

**Comment by saiballo** [comment]
la provincia di prato è una PA centrale o no? domando.

**Comment by gunzip** [comment]
@MaoX17 correggo il bug sul colore dei link visitati #106 appena posso (in generale puoi proporre anche tu modifiche tramite una pull request). grazie per il debug, è quello che serve. come consiglio eviterei di utilizzari i bottoni dove un più semplice link andrebbe bene (es. consultazioni di contenuti del sito)

@saiballo, regioni province e comuni sono amministrazioni locali

**Comment by saiballo** [comment]
e allora, se è amministrazione locale, il sito di MaoX17 non dovrebbe mai usare il colore #0066cc o sbaglio?

**Comment by gunzip** [comment]
@saiballo sicuramente non nell'header. per quanto riguarda i contenuti giro la questione e aggiorniamo i testi appena ho conferme.

**Comment by MaoX17** [comment]
@gunzip ok, grazie. La prossima volta provo a proporre la modifica direttamente.

**Comment by gunzip** [comment]
segnalo commento correlato 

https://github.com/italia-it/designer.italia.it/issues/47#issuecomment-167076854

**Comment by gunzip** [comment]
btw http://www.agid.gov.it/notizie/2016/01/11/agid-cerca-personale-specializzato-proveniente-altre-pa
